// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ai.sql

package db

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createAIInteraction = `-- name: CreateAIInteraction :one
INSERT INTO ai_interactions (user_id, feature, session_id, input_text, output_text, confidence_score, context, model_used, response_time_ms)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, user_id, feature, session_id, input_text, output_text, confidence_score, was_accurate, user_feedback, context, model_used, response_time_ms, reviewed_by, created_at
`

type CreateAIInteractionParams struct {
	UserID          uuid.UUID `json:"user_id"`
	Feature         AiFeature `json:"feature"`
	SessionID       *string   `json:"session_id"`
	InputText       string    `json:"input_text"`
	OutputText      string    `json:"output_text"`
	ConfidenceScore *float64  `json:"confidence_score"`
	Context         []byte    `json:"context"`
	ModelUsed       *string   `json:"model_used"`
	ResponseTimeMs  *int32    `json:"response_time_ms"`
}

func (q *Queries) CreateAIInteraction(ctx context.Context, arg CreateAIInteractionParams) (AiInteraction, error) {
	row := q.db.QueryRow(ctx, createAIInteraction,
		arg.UserID,
		arg.Feature,
		arg.SessionID,
		arg.InputText,
		arg.OutputText,
		arg.ConfidenceScore,
		arg.Context,
		arg.ModelUsed,
		arg.ResponseTimeMs,
	)
	var i AiInteraction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Feature,
		&i.SessionID,
		&i.InputText,
		&i.OutputText,
		&i.ConfidenceScore,
		&i.WasAccurate,
		&i.UserFeedback,
		&i.Context,
		&i.ModelUsed,
		&i.ResponseTimeMs,
		&i.ReviewedBy,
		&i.CreatedAt,
	)
	return i, err
}

const createAIModel = `-- name: CreateAIModel :one
INSERT INTO ai_models (model_name, model_version, model_type, training_data_summary, accuracy_metrics, config)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, model_name, model_version, model_type, training_data_summary, accuracy_metrics, bias_audit_results, deployment_status, config, created_at, updated_at
`

type CreateAIModelParams struct {
	ModelName           string      `json:"model_name"`
	ModelVersion        string      `json:"model_version"`
	ModelType           AiModelType `json:"model_type"`
	TrainingDataSummary []byte      `json:"training_data_summary"`
	AccuracyMetrics     []byte      `json:"accuracy_metrics"`
	Config              []byte      `json:"config"`
}

func (q *Queries) CreateAIModel(ctx context.Context, arg CreateAIModelParams) (AiModel, error) {
	row := q.db.QueryRow(ctx, createAIModel,
		arg.ModelName,
		arg.ModelVersion,
		arg.ModelType,
		arg.TrainingDataSummary,
		arg.AccuracyMetrics,
		arg.Config,
	)
	var i AiModel
	err := row.Scan(
		&i.ID,
		&i.ModelName,
		&i.ModelVersion,
		&i.ModelType,
		&i.TrainingDataSummary,
		&i.AccuracyMetrics,
		&i.BiasAuditResults,
		&i.DeploymentStatus,
		&i.Config,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createAIPrediction = `-- name: CreateAIPrediction :one
INSERT INTO ai_predictions (prediction_type, target_id, predicted_value, confidence_interval, model_version, features_used)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, prediction_type, target_id, predicted_value, actual_value, confidence_interval, model_version, features_used, was_reviewed, reviewed_by, created_at, expires_at
`

type CreateAIPredictionParams struct {
	PredictionType     PredictionType  `json:"prediction_type"`
	TargetID           uuid.UUID       `json:"target_id"`
	PredictedValue     json.RawMessage `json:"predicted_value"`
	ConfidenceInterval *float64        `json:"confidence_interval"`
	ModelVersion       *string         `json:"model_version"`
	FeaturesUsed       []byte          `json:"features_used"`
}

func (q *Queries) CreateAIPrediction(ctx context.Context, arg CreateAIPredictionParams) (AiPrediction, error) {
	row := q.db.QueryRow(ctx, createAIPrediction,
		arg.PredictionType,
		arg.TargetID,
		arg.PredictedValue,
		arg.ConfidenceInterval,
		arg.ModelVersion,
		arg.FeaturesUsed,
	)
	var i AiPrediction
	err := row.Scan(
		&i.ID,
		&i.PredictionType,
		&i.TargetID,
		&i.PredictedValue,
		&i.ActualValue,
		&i.ConfidenceInterval,
		&i.ModelVersion,
		&i.FeaturesUsed,
		&i.WasReviewed,
		&i.ReviewedBy,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const createContentModerationLog = `-- name: CreateContentModerationLog :one
INSERT INTO content_moderation_log (content_id, content_type, ai_flagged, ai_confidence, ai_reason)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, content_id, content_type, ai_flagged, ai_confidence, ai_reason, human_reviewed, human_decision, reviewed_by, created_at, reviewed_at
`

type CreateContentModerationLogParams struct {
	ContentID    uuid.UUID             `json:"content_id"`
	ContentType  ModerationContentType `json:"content_type"`
	AiFlagged    *bool                 `json:"ai_flagged"`
	AiConfidence *float64              `json:"ai_confidence"`
	AiReason     *string               `json:"ai_reason"`
}

func (q *Queries) CreateContentModerationLog(ctx context.Context, arg CreateContentModerationLogParams) (ContentModerationLog, error) {
	row := q.db.QueryRow(ctx, createContentModerationLog,
		arg.ContentID,
		arg.ContentType,
		arg.AiFlagged,
		arg.AiConfidence,
		arg.AiReason,
	)
	var i ContentModerationLog
	err := row.Scan(
		&i.ID,
		&i.ContentID,
		&i.ContentType,
		&i.AiFlagged,
		&i.AiConfidence,
		&i.AiReason,
		&i.HumanReviewed,
		&i.HumanDecision,
		&i.ReviewedBy,
		&i.CreatedAt,
		&i.ReviewedAt,
	)
	return i, err
}

const getAIInteractionStats = `-- name: GetAIInteractionStats :one
SELECT
    COUNT(*) as total_interactions,
    COUNT(DISTINCT user_id) as unique_users,
    COALESCE(AVG(confidence_score), 0) as avg_confidence,
    COALESCE(AVG(response_time_ms), 0) as avg_response_time
FROM ai_interactions
WHERE created_at >= COALESCE($1, NOW() - INTERVAL '30 days')
`

type GetAIInteractionStatsRow struct {
	TotalInteractions int64       `json:"total_interactions"`
	UniqueUsers       int64       `json:"unique_users"`
	AvgConfidence     interface{} `json:"avg_confidence"`
	AvgResponseTime   interface{} `json:"avg_response_time"`
}

func (q *Queries) GetAIInteractionStats(ctx context.Context, createdAt pgtype.Timestamptz) (GetAIInteractionStatsRow, error) {
	row := q.db.QueryRow(ctx, getAIInteractionStats, createdAt)
	var i GetAIInteractionStatsRow
	err := row.Scan(
		&i.TotalInteractions,
		&i.UniqueUsers,
		&i.AvgConfidence,
		&i.AvgResponseTime,
	)
	return i, err
}

const getAIModelByName = `-- name: GetAIModelByName :one
SELECT id, model_name, model_version, model_type, training_data_summary, accuracy_metrics, bias_audit_results, deployment_status, config, created_at, updated_at FROM ai_models WHERE model_name = $1
`

func (q *Queries) GetAIModelByName(ctx context.Context, modelName string) (AiModel, error) {
	row := q.db.QueryRow(ctx, getAIModelByName, modelName)
	var i AiModel
	err := row.Scan(
		&i.ID,
		&i.ModelName,
		&i.ModelVersion,
		&i.ModelType,
		&i.TrainingDataSummary,
		&i.AccuracyMetrics,
		&i.BiasAuditResults,
		&i.DeploymentStatus,
		&i.Config,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAISettings = `-- name: GetAISettings :one
SELECT id, user_id, chatbot_enabled, personalization_enabled, face_recognition_enabled, data_collection_consent, preferred_language, created_at, updated_at FROM ai_user_settings WHERE user_id = $1
`

func (q *Queries) GetAISettings(ctx context.Context, userID uuid.UUID) (AiUserSetting, error) {
	row := q.db.QueryRow(ctx, getAISettings, userID)
	var i AiUserSetting
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ChatbotEnabled,
		&i.PersonalizationEnabled,
		&i.FaceRecognitionEnabled,
		&i.DataCollectionConsent,
		&i.PreferredLanguage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrCreateAISettings = `-- name: GetOrCreateAISettings :one
INSERT INTO ai_user_settings (user_id) VALUES ($1)
ON CONFLICT (user_id) DO UPDATE SET user_id = EXCLUDED.user_id
RETURNING id, user_id, chatbot_enabled, personalization_enabled, face_recognition_enabled, data_collection_consent, preferred_language, created_at, updated_at
`

func (q *Queries) GetOrCreateAISettings(ctx context.Context, userID uuid.UUID) (AiUserSetting, error) {
	row := q.db.QueryRow(ctx, getOrCreateAISettings, userID)
	var i AiUserSetting
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ChatbotEnabled,
		&i.PersonalizationEnabled,
		&i.FaceRecognitionEnabled,
		&i.DataCollectionConsent,
		&i.PreferredLanguage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTodayInteractionCount = `-- name: GetTodayInteractionCount :one
SELECT COUNT(*)::int FROM ai_interactions
WHERE user_id = $1 AND created_at >= CURRENT_DATE
`

func (q *Queries) GetTodayInteractionCount(ctx context.Context, userID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, getTodayInteractionCount, userID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const listAIInteractionsBySession = `-- name: ListAIInteractionsBySession :many
SELECT id, user_id, feature, session_id, input_text, output_text, confidence_score, was_accurate, user_feedback, context, model_used, response_time_ms, reviewed_by, created_at FROM ai_interactions
WHERE session_id = $1 AND user_id = $2
ORDER BY created_at ASC
`

type ListAIInteractionsBySessionParams struct {
	SessionID *string   `json:"session_id"`
	UserID    uuid.UUID `json:"user_id"`
}

func (q *Queries) ListAIInteractionsBySession(ctx context.Context, arg ListAIInteractionsBySessionParams) ([]AiInteraction, error) {
	rows, err := q.db.Query(ctx, listAIInteractionsBySession, arg.SessionID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AiInteraction{}
	for rows.Next() {
		var i AiInteraction
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Feature,
			&i.SessionID,
			&i.InputText,
			&i.OutputText,
			&i.ConfidenceScore,
			&i.WasAccurate,
			&i.UserFeedback,
			&i.Context,
			&i.ModelUsed,
			&i.ResponseTimeMs,
			&i.ReviewedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAIInteractionsByUser = `-- name: ListAIInteractionsByUser :many
SELECT id, user_id, feature, session_id, input_text, output_text, confidence_score, was_accurate, user_feedback, context, model_used, response_time_ms, reviewed_by, created_at FROM ai_interactions
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListAIInteractionsByUserParams struct {
	UserID uuid.UUID `json:"user_id"`
	Limit  int32     `json:"limit"`
	Offset int32     `json:"offset"`
}

func (q *Queries) ListAIInteractionsByUser(ctx context.Context, arg ListAIInteractionsByUserParams) ([]AiInteraction, error) {
	rows, err := q.db.Query(ctx, listAIInteractionsByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AiInteraction{}
	for rows.Next() {
		var i AiInteraction
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Feature,
			&i.SessionID,
			&i.InputText,
			&i.OutputText,
			&i.ConfidenceScore,
			&i.WasAccurate,
			&i.UserFeedback,
			&i.Context,
			&i.ModelUsed,
			&i.ResponseTimeMs,
			&i.ReviewedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAIModels = `-- name: ListAIModels :many
SELECT id, model_name, model_version, model_type, training_data_summary, accuracy_metrics, bias_audit_results, deployment_status, config, created_at, updated_at FROM ai_models ORDER BY created_at DESC
`

func (q *Queries) ListAIModels(ctx context.Context) ([]AiModel, error) {
	rows, err := q.db.Query(ctx, listAIModels)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AiModel{}
	for rows.Next() {
		var i AiModel
		if err := rows.Scan(
			&i.ID,
			&i.ModelName,
			&i.ModelVersion,
			&i.ModelType,
			&i.TrainingDataSummary,
			&i.AccuracyMetrics,
			&i.BiasAuditResults,
			&i.DeploymentStatus,
			&i.Config,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAIPredictionsByType = `-- name: ListAIPredictionsByType :many
SELECT id, prediction_type, target_id, predicted_value, actual_value, confidence_interval, model_version, features_used, was_reviewed, reviewed_by, created_at, expires_at FROM ai_predictions
WHERE prediction_type = $1
ORDER BY created_at DESC
LIMIT $2
`

type ListAIPredictionsByTypeParams struct {
	PredictionType PredictionType `json:"prediction_type"`
	Limit          int32          `json:"limit"`
}

func (q *Queries) ListAIPredictionsByType(ctx context.Context, arg ListAIPredictionsByTypeParams) ([]AiPrediction, error) {
	rows, err := q.db.Query(ctx, listAIPredictionsByType, arg.PredictionType, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AiPrediction{}
	for rows.Next() {
		var i AiPrediction
		if err := rows.Scan(
			&i.ID,
			&i.PredictionType,
			&i.TargetID,
			&i.PredictedValue,
			&i.ActualValue,
			&i.ConfidenceInterval,
			&i.ModelVersion,
			&i.FeaturesUsed,
			&i.WasReviewed,
			&i.ReviewedBy,
			&i.CreatedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingModerations = `-- name: ListPendingModerations :many
SELECT id, content_id, content_type, ai_flagged, ai_confidence, ai_reason, human_reviewed, human_decision, reviewed_by, created_at, reviewed_at FROM content_moderation_log
WHERE human_reviewed = false
ORDER BY created_at DESC
LIMIT $1
`

func (q *Queries) ListPendingModerations(ctx context.Context, limit int32) ([]ContentModerationLog, error) {
	rows, err := q.db.Query(ctx, listPendingModerations, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ContentModerationLog{}
	for rows.Next() {
		var i ContentModerationLog
		if err := rows.Scan(
			&i.ID,
			&i.ContentID,
			&i.ContentType,
			&i.AiFlagged,
			&i.AiConfidence,
			&i.AiReason,
			&i.HumanReviewed,
			&i.HumanDecision,
			&i.ReviewedBy,
			&i.CreatedAt,
			&i.ReviewedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAIInteractionFeedback = `-- name: UpdateAIInteractionFeedback :exec
UPDATE ai_interactions SET user_feedback = $2, was_accurate = $3 WHERE id = $1
`

type UpdateAIInteractionFeedbackParams struct {
	ID           uuid.UUID `json:"id"`
	UserFeedback *string   `json:"user_feedback"`
	WasAccurate  *bool     `json:"was_accurate"`
}

func (q *Queries) UpdateAIInteractionFeedback(ctx context.Context, arg UpdateAIInteractionFeedbackParams) error {
	_, err := q.db.Exec(ctx, updateAIInteractionFeedback, arg.ID, arg.UserFeedback, arg.WasAccurate)
	return err
}

const updateAIModelStatus = `-- name: UpdateAIModelStatus :exec
UPDATE ai_models SET deployment_status = $2 WHERE id = $1
`

type UpdateAIModelStatusParams struct {
	ID               uuid.UUID     `json:"id"`
	DeploymentStatus AiModelStatus `json:"deployment_status"`
}

func (q *Queries) UpdateAIModelStatus(ctx context.Context, arg UpdateAIModelStatusParams) error {
	_, err := q.db.Exec(ctx, updateAIModelStatus, arg.ID, arg.DeploymentStatus)
	return err
}

const updateAIPredictionActual = `-- name: UpdateAIPredictionActual :exec
UPDATE ai_predictions SET actual_value = $2, was_reviewed = $3, reviewed_by = $4 WHERE id = $1
`

type UpdateAIPredictionActualParams struct {
	ID          uuid.UUID   `json:"id"`
	ActualValue []byte      `json:"actual_value"`
	WasReviewed *bool       `json:"was_reviewed"`
	ReviewedBy  pgtype.UUID `json:"reviewed_by"`
}

func (q *Queries) UpdateAIPredictionActual(ctx context.Context, arg UpdateAIPredictionActualParams) error {
	_, err := q.db.Exec(ctx, updateAIPredictionActual,
		arg.ID,
		arg.ActualValue,
		arg.WasReviewed,
		arg.ReviewedBy,
	)
	return err
}

const updateAISettings = `-- name: UpdateAISettings :exec
UPDATE ai_user_settings SET
    chatbot_enabled = COALESCE($2, chatbot_enabled),
    personalization_enabled = COALESCE($3, personalization_enabled),
    face_recognition_enabled = COALESCE($4, face_recognition_enabled),
    data_collection_consent = COALESCE($5, data_collection_consent),
    preferred_language = COALESCE($6, preferred_language)
WHERE user_id = $1
`

type UpdateAISettingsParams struct {
	UserID                 uuid.UUID `json:"user_id"`
	ChatbotEnabled         *bool     `json:"chatbot_enabled"`
	PersonalizationEnabled *bool     `json:"personalization_enabled"`
	FaceRecognitionEnabled *bool     `json:"face_recognition_enabled"`
	DataCollectionConsent  *bool     `json:"data_collection_consent"`
	PreferredLanguage      *string   `json:"preferred_language"`
}

func (q *Queries) UpdateAISettings(ctx context.Context, arg UpdateAISettingsParams) error {
	_, err := q.db.Exec(ctx, updateAISettings,
		arg.UserID,
		arg.ChatbotEnabled,
		arg.PersonalizationEnabled,
		arg.FaceRecognitionEnabled,
		arg.DataCollectionConsent,
		arg.PreferredLanguage,
	)
	return err
}

const updateModerationDecision = `-- name: UpdateModerationDecision :exec
UPDATE content_moderation_log
SET human_reviewed = true, human_decision = $2, reviewed_by = $3, reviewed_at = NOW()
WHERE id = $1
`

type UpdateModerationDecisionParams struct {
	ID            uuid.UUID           `json:"id"`
	HumanDecision *ModerationDecision `json:"human_decision"`
	ReviewedBy    pgtype.UUID         `json:"reviewed_by"`
}

func (q *Queries) UpdateModerationDecision(ctx context.Context, arg UpdateModerationDecisionParams) error {
	_, err := q.db.Exec(ctx, updateModerationDecision, arg.ID, arg.HumanDecision, arg.ReviewedBy)
	return err
}
