// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: approvals.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createSignupApproval = `-- name: CreateSignupApproval :one
INSERT INTO signup_approvals (
    user_id, signup_type, reg_no, level, status
) VALUES (
    $1, $2, $3, $4, $5
) RETURNING id, user_id, signup_type, status, reg_no, level, approved_by, approved_at, rejection_reason, created_at
`

type CreateSignupApprovalParams struct {
	UserID     uuid.UUID `json:"user_id"`
	SignupType string    `json:"signup_type"`
	RegNo      *string   `json:"reg_no"`
	Level      *int32    `json:"level"`
	Status     string    `json:"status"`
}

func (q *Queries) CreateSignupApproval(ctx context.Context, arg CreateSignupApprovalParams) (SignupApproval, error) {
	row := q.db.QueryRow(ctx, createSignupApproval,
		arg.UserID,
		arg.SignupType,
		arg.RegNo,
		arg.Level,
		arg.Status,
	)
	var i SignupApproval
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SignupType,
		&i.Status,
		&i.RegNo,
		&i.Level,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.RejectionReason,
		&i.CreatedAt,
	)
	return i, err
}

const getSignupApproval = `-- name: GetSignupApproval :one
SELECT id, user_id, signup_type, status, reg_no, level, approved_by, approved_at, rejection_reason, created_at FROM signup_approvals
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetSignupApproval(ctx context.Context, id uuid.UUID) (SignupApproval, error) {
	row := q.db.QueryRow(ctx, getSignupApproval, id)
	var i SignupApproval
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SignupType,
		&i.Status,
		&i.RegNo,
		&i.Level,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.RejectionReason,
		&i.CreatedAt,
	)
	return i, err
}

const getSignupApprovalByUserId = `-- name: GetSignupApprovalByUserId :one
SELECT id, user_id, signup_type, status, reg_no, level, approved_by, approved_at, rejection_reason, created_at FROM signup_approvals
WHERE user_id = $1 LIMIT 1
`

func (q *Queries) GetSignupApprovalByUserId(ctx context.Context, userID uuid.UUID) (SignupApproval, error) {
	row := q.db.QueryRow(ctx, getSignupApprovalByUserId, userID)
	var i SignupApproval
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SignupType,
		&i.Status,
		&i.RegNo,
		&i.Level,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.RejectionReason,
		&i.CreatedAt,
	)
	return i, err
}

const listPendingSignupApprovals = `-- name: ListPendingSignupApprovals :many
SELECT id, user_id, signup_type, status, reg_no, level, approved_by, approved_at, rejection_reason, created_at FROM signup_approvals
WHERE status = 'pending'
ORDER BY created_at ASC
`

func (q *Queries) ListPendingSignupApprovals(ctx context.Context) ([]SignupApproval, error) {
	rows, err := q.db.Query(ctx, listPendingSignupApprovals)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SignupApproval{}
	for rows.Next() {
		var i SignupApproval
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.SignupType,
			&i.Status,
			&i.RegNo,
			&i.Level,
			&i.ApprovedBy,
			&i.ApprovedAt,
			&i.RejectionReason,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingSignupApprovalsByLevel = `-- name: ListPendingSignupApprovalsByLevel :many
SELECT id, user_id, signup_type, status, reg_no, level, approved_by, approved_at, rejection_reason, created_at FROM signup_approvals
WHERE status = 'pending' AND level = $1
ORDER BY created_at ASC
`

func (q *Queries) ListPendingSignupApprovalsByLevel(ctx context.Context, level *int32) ([]SignupApproval, error) {
	rows, err := q.db.Query(ctx, listPendingSignupApprovalsByLevel, level)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SignupApproval{}
	for rows.Next() {
		var i SignupApproval
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.SignupType,
			&i.Status,
			&i.RegNo,
			&i.Level,
			&i.ApprovedBy,
			&i.ApprovedAt,
			&i.RejectionReason,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingSignupApprovalsByType = `-- name: ListPendingSignupApprovalsByType :many
SELECT id, user_id, signup_type, status, reg_no, level, approved_by, approved_at, rejection_reason, created_at FROM signup_approvals
WHERE status = 'pending' AND signup_type = $1
ORDER BY created_at ASC
`

func (q *Queries) ListPendingSignupApprovalsByType(ctx context.Context, signupType string) ([]SignupApproval, error) {
	rows, err := q.db.Query(ctx, listPendingSignupApprovalsByType, signupType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SignupApproval{}
	for rows.Next() {
		var i SignupApproval
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.SignupType,
			&i.Status,
			&i.RegNo,
			&i.Level,
			&i.ApprovedBy,
			&i.ApprovedAt,
			&i.RejectionReason,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSignupApproval = `-- name: UpdateSignupApproval :one
UPDATE signup_approvals
SET
    status = $2,
    approved_by = $3,
    approved_at = $4,
    rejection_reason = $5
WHERE id = $1
RETURNING id, user_id, signup_type, status, reg_no, level, approved_by, approved_at, rejection_reason, created_at
`

type UpdateSignupApprovalParams struct {
	ID              uuid.UUID          `json:"id"`
	Status          string             `json:"status"`
	ApprovedBy      pgtype.UUID        `json:"approved_by"`
	ApprovedAt      pgtype.Timestamptz `json:"approved_at"`
	RejectionReason *string            `json:"rejection_reason"`
}

func (q *Queries) UpdateSignupApproval(ctx context.Context, arg UpdateSignupApprovalParams) (SignupApproval, error) {
	row := q.db.QueryRow(ctx, updateSignupApproval,
		arg.ID,
		arg.Status,
		arg.ApprovedBy,
		arg.ApprovedAt,
		arg.RejectionReason,
	)
	var i SignupApproval
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SignupType,
		&i.Status,
		&i.RegNo,
		&i.Level,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.RejectionReason,
		&i.CreatedAt,
	)
	return i, err
}
