// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: assignments.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createAssignment = `-- name: CreateAssignment :one
INSERT INTO assignments (
    course_id, title, description, deadline, max_score, allowed_formats, file_url, uploaded_by_class_rep_id, created_by, session_id, semester_id, is_active
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12
) RETURNING id, course_id, title, description, deadline, max_score, allowed_formats, file_url, uploaded_by_class_rep_id, created_by, session_id, semester_id, is_active, created_at
`

type CreateAssignmentParams struct {
	CourseID             uuid.UUID          `json:"course_id"`
	Title                string             `json:"title"`
	Description          *string            `json:"description"`
	Deadline             pgtype.Timestamptz `json:"deadline"`
	MaxScore             int32              `json:"max_score"`
	AllowedFormats       []byte             `json:"allowed_formats"`
	FileUrl              *string            `json:"file_url"`
	UploadedByClassRepID pgtype.UUID        `json:"uploaded_by_class_rep_id"`
	CreatedBy            uuid.UUID          `json:"created_by"`
	SessionID            uuid.UUID          `json:"session_id"`
	SemesterID           uuid.UUID          `json:"semester_id"`
	IsActive             bool               `json:"is_active"`
}

func (q *Queries) CreateAssignment(ctx context.Context, arg CreateAssignmentParams) (Assignment, error) {
	row := q.db.QueryRow(ctx, createAssignment,
		arg.CourseID,
		arg.Title,
		arg.Description,
		arg.Deadline,
		arg.MaxScore,
		arg.AllowedFormats,
		arg.FileUrl,
		arg.UploadedByClassRepID,
		arg.CreatedBy,
		arg.SessionID,
		arg.SemesterID,
		arg.IsActive,
	)
	var i Assignment
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.Title,
		&i.Description,
		&i.Deadline,
		&i.MaxScore,
		&i.AllowedFormats,
		&i.FileUrl,
		&i.UploadedByClassRepID,
		&i.CreatedBy,
		&i.SessionID,
		&i.SemesterID,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const createAssignmentGrade = `-- name: CreateAssignmentGrade :one
INSERT INTO assignment_grades (
    assignment_id, student_id, score, feedback, is_late, graded_by
) VALUES (
    $1, $2, $3, $4, $5, $6
) RETURNING id, assignment_id, student_id, score, feedback, is_late, graded_by, graded_at
`

type CreateAssignmentGradeParams struct {
	AssignmentID uuid.UUID      `json:"assignment_id"`
	StudentID    uuid.UUID      `json:"student_id"`
	Score        pgtype.Numeric `json:"score"`
	Feedback     *string        `json:"feedback"`
	IsLate       bool           `json:"is_late"`
	GradedBy     uuid.UUID      `json:"graded_by"`
}

func (q *Queries) CreateAssignmentGrade(ctx context.Context, arg CreateAssignmentGradeParams) (AssignmentGrade, error) {
	row := q.db.QueryRow(ctx, createAssignmentGrade,
		arg.AssignmentID,
		arg.StudentID,
		arg.Score,
		arg.Feedback,
		arg.IsLate,
		arg.GradedBy,
	)
	var i AssignmentGrade
	err := row.Scan(
		&i.ID,
		&i.AssignmentID,
		&i.StudentID,
		&i.Score,
		&i.Feedback,
		&i.IsLate,
		&i.GradedBy,
		&i.GradedAt,
	)
	return i, err
}

const deleteAssignment = `-- name: DeleteAssignment :exec
DELETE FROM assignments
WHERE id = $1
`

func (q *Queries) DeleteAssignment(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteAssignment, id)
	return err
}

const deleteAssignmentGrade = `-- name: DeleteAssignmentGrade :exec
DELETE FROM assignment_grades
WHERE id = $1
`

func (q *Queries) DeleteAssignmentGrade(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteAssignmentGrade, id)
	return err
}

const getAssignment = `-- name: GetAssignment :one
SELECT id, course_id, title, description, deadline, max_score, allowed_formats, file_url, uploaded_by_class_rep_id, created_by, session_id, semester_id, is_active, created_at FROM assignments
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetAssignment(ctx context.Context, id uuid.UUID) (Assignment, error) {
	row := q.db.QueryRow(ctx, getAssignment, id)
	var i Assignment
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.Title,
		&i.Description,
		&i.Deadline,
		&i.MaxScore,
		&i.AllowedFormats,
		&i.FileUrl,
		&i.UploadedByClassRepID,
		&i.CreatedBy,
		&i.SessionID,
		&i.SemesterID,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const getAssignmentGrade = `-- name: GetAssignmentGrade :one
SELECT id, assignment_id, student_id, score, feedback, is_late, graded_by, graded_at FROM assignment_grades
WHERE assignment_id = $1 AND student_id = $2 LIMIT 1
`

type GetAssignmentGradeParams struct {
	AssignmentID uuid.UUID `json:"assignment_id"`
	StudentID    uuid.UUID `json:"student_id"`
}

func (q *Queries) GetAssignmentGrade(ctx context.Context, arg GetAssignmentGradeParams) (AssignmentGrade, error) {
	row := q.db.QueryRow(ctx, getAssignmentGrade, arg.AssignmentID, arg.StudentID)
	var i AssignmentGrade
	err := row.Scan(
		&i.ID,
		&i.AssignmentID,
		&i.StudentID,
		&i.Score,
		&i.Feedback,
		&i.IsLate,
		&i.GradedBy,
		&i.GradedAt,
	)
	return i, err
}

const listAssignmentGrades = `-- name: ListAssignmentGrades :many
SELECT id, assignment_id, student_id, score, feedback, is_late, graded_by, graded_at FROM assignment_grades
WHERE assignment_id = $1
ORDER BY graded_at DESC
`

func (q *Queries) ListAssignmentGrades(ctx context.Context, assignmentID uuid.UUID) ([]AssignmentGrade, error) {
	rows, err := q.db.Query(ctx, listAssignmentGrades, assignmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AssignmentGrade{}
	for rows.Next() {
		var i AssignmentGrade
		if err := rows.Scan(
			&i.ID,
			&i.AssignmentID,
			&i.StudentID,
			&i.Score,
			&i.Feedback,
			&i.IsLate,
			&i.GradedBy,
			&i.GradedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCourseAssignments = `-- name: ListCourseAssignments :many
SELECT id, course_id, title, description, deadline, max_score, allowed_formats, file_url, uploaded_by_class_rep_id, created_by, session_id, semester_id, is_active, created_at FROM assignments
WHERE course_id = $1 AND session_id = $2
ORDER BY created_at DESC
`

type ListCourseAssignmentsParams struct {
	CourseID  uuid.UUID `json:"course_id"`
	SessionID uuid.UUID `json:"session_id"`
}

func (q *Queries) ListCourseAssignments(ctx context.Context, arg ListCourseAssignmentsParams) ([]Assignment, error) {
	rows, err := q.db.Query(ctx, listCourseAssignments, arg.CourseID, arg.SessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Assignment{}
	for rows.Next() {
		var i Assignment
		if err := rows.Scan(
			&i.ID,
			&i.CourseID,
			&i.Title,
			&i.Description,
			&i.Deadline,
			&i.MaxScore,
			&i.AllowedFormats,
			&i.FileUrl,
			&i.UploadedByClassRepID,
			&i.CreatedBy,
			&i.SessionID,
			&i.SemesterID,
			&i.IsActive,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStudentAssignmentGrades = `-- name: ListStudentAssignmentGrades :many
SELECT id, assignment_id, student_id, score, feedback, is_late, graded_by, graded_at FROM assignment_grades
WHERE student_id = $1
ORDER BY graded_at DESC
`

func (q *Queries) ListStudentAssignmentGrades(ctx context.Context, studentID uuid.UUID) ([]AssignmentGrade, error) {
	rows, err := q.db.Query(ctx, listStudentAssignmentGrades, studentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AssignmentGrade{}
	for rows.Next() {
		var i AssignmentGrade
		if err := rows.Scan(
			&i.ID,
			&i.AssignmentID,
			&i.StudentID,
			&i.Score,
			&i.Feedback,
			&i.IsLate,
			&i.GradedBy,
			&i.GradedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAssignment = `-- name: UpdateAssignment :one
UPDATE assignments
SET
    title = $2,
    description = $3,
    deadline = $4,
    max_score = $5,
    allowed_formats = $6,
    file_url = $7,
    is_active = $8
WHERE id = $1
RETURNING id, course_id, title, description, deadline, max_score, allowed_formats, file_url, uploaded_by_class_rep_id, created_by, session_id, semester_id, is_active, created_at
`

type UpdateAssignmentParams struct {
	ID             uuid.UUID          `json:"id"`
	Title          string             `json:"title"`
	Description    *string            `json:"description"`
	Deadline       pgtype.Timestamptz `json:"deadline"`
	MaxScore       int32              `json:"max_score"`
	AllowedFormats []byte             `json:"allowed_formats"`
	FileUrl        *string            `json:"file_url"`
	IsActive       bool               `json:"is_active"`
}

func (q *Queries) UpdateAssignment(ctx context.Context, arg UpdateAssignmentParams) (Assignment, error) {
	row := q.db.QueryRow(ctx, updateAssignment,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.Deadline,
		arg.MaxScore,
		arg.AllowedFormats,
		arg.FileUrl,
		arg.IsActive,
	)
	var i Assignment
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.Title,
		&i.Description,
		&i.Deadline,
		&i.MaxScore,
		&i.AllowedFormats,
		&i.FileUrl,
		&i.UploadedByClassRepID,
		&i.CreatedBy,
		&i.SessionID,
		&i.SemesterID,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const updateAssignmentGrade = `-- name: UpdateAssignmentGrade :one
UPDATE assignment_grades
SET
    score = $2,
    feedback = $3,
    is_late = $4,
    graded_by = $5,
    graded_at = NOW()
WHERE id = $1
RETURNING id, assignment_id, student_id, score, feedback, is_late, graded_by, graded_at
`

type UpdateAssignmentGradeParams struct {
	ID       uuid.UUID      `json:"id"`
	Score    pgtype.Numeric `json:"score"`
	Feedback *string        `json:"feedback"`
	IsLate   bool           `json:"is_late"`
	GradedBy uuid.UUID      `json:"graded_by"`
}

func (q *Queries) UpdateAssignmentGrade(ctx context.Context, arg UpdateAssignmentGradeParams) (AssignmentGrade, error) {
	row := q.db.QueryRow(ctx, updateAssignmentGrade,
		arg.ID,
		arg.Score,
		arg.Feedback,
		arg.IsLate,
		arg.GradedBy,
	)
	var i AssignmentGrade
	err := row.Scan(
		&i.ID,
		&i.AssignmentID,
		&i.StudentID,
		&i.Score,
		&i.Feedback,
		&i.IsLate,
		&i.GradedBy,
		&i.GradedAt,
	)
	return i, err
}
