// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: attendance.sql

package db

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createAttendanceSheet = `-- name: CreateAttendanceSheet :one
INSERT INTO attendance_sheets (
    course_id, date, class_rep_id, attendance_data, session_id, status
) VALUES (
    $1, $2, $3, $4, $5, $6
) RETURNING id, course_id, date, class_rep_id, attendance_data, pdf_url, status, finalized_at, emailed_to_lecturer, session_id, created_at
`

type CreateAttendanceSheetParams struct {
	CourseID       uuid.UUID          `json:"course_id"`
	Date           pgtype.Timestamptz `json:"date"`
	ClassRepID     uuid.UUID          `json:"class_rep_id"`
	AttendanceData json.RawMessage    `json:"attendance_data"`
	SessionID      uuid.UUID          `json:"session_id"`
	Status         string             `json:"status"`
}

func (q *Queries) CreateAttendanceSheet(ctx context.Context, arg CreateAttendanceSheetParams) (AttendanceSheet, error) {
	row := q.db.QueryRow(ctx, createAttendanceSheet,
		arg.CourseID,
		arg.Date,
		arg.ClassRepID,
		arg.AttendanceData,
		arg.SessionID,
		arg.Status,
	)
	var i AttendanceSheet
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.Date,
		&i.ClassRepID,
		&i.AttendanceData,
		&i.PdfUrl,
		&i.Status,
		&i.FinalizedAt,
		&i.EmailedToLecturer,
		&i.SessionID,
		&i.CreatedAt,
	)
	return i, err
}

const deleteAttendanceSheet = `-- name: DeleteAttendanceSheet :exec
DELETE FROM attendance_sheets
WHERE id = $1
`

func (q *Queries) DeleteAttendanceSheet(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteAttendanceSheet, id)
	return err
}

const finalizeAttendanceSheet = `-- name: FinalizeAttendanceSheet :one
UPDATE attendance_sheets
SET
    status = 'finalized',
    finalized_at = NOW()
WHERE id = $1
RETURNING id, course_id, date, class_rep_id, attendance_data, pdf_url, status, finalized_at, emailed_to_lecturer, session_id, created_at
`

func (q *Queries) FinalizeAttendanceSheet(ctx context.Context, id uuid.UUID) (AttendanceSheet, error) {
	row := q.db.QueryRow(ctx, finalizeAttendanceSheet, id)
	var i AttendanceSheet
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.Date,
		&i.ClassRepID,
		&i.AttendanceData,
		&i.PdfUrl,
		&i.Status,
		&i.FinalizedAt,
		&i.EmailedToLecturer,
		&i.SessionID,
		&i.CreatedAt,
	)
	return i, err
}

const getAttendanceSheet = `-- name: GetAttendanceSheet :one
SELECT id, course_id, date, class_rep_id, attendance_data, pdf_url, status, finalized_at, emailed_to_lecturer, session_id, created_at FROM attendance_sheets
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetAttendanceSheet(ctx context.Context, id uuid.UUID) (AttendanceSheet, error) {
	row := q.db.QueryRow(ctx, getAttendanceSheet, id)
	var i AttendanceSheet
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.Date,
		&i.ClassRepID,
		&i.AttendanceData,
		&i.PdfUrl,
		&i.Status,
		&i.FinalizedAt,
		&i.EmailedToLecturer,
		&i.SessionID,
		&i.CreatedAt,
	)
	return i, err
}

const getAttendanceSummary = `-- name: GetAttendanceSummary :one
SELECT
    COUNT(*)::int                                                             AS total_classes,
    COUNT(*) FILTER (
        WHERE attendance_data @> jsonb_build_array(
            jsonb_build_object('student_id', $3::text, 'present', true)
        )
    )::int                                                                    AS attended_classes
FROM attendance_sheets
WHERE course_id = $1
  AND session_id = $2
  AND status = 'finalized'
`

type GetAttendanceSummaryParams struct {
	CourseID  uuid.UUID `json:"course_id"`
	SessionID uuid.UUID `json:"session_id"`
	Column3   string    `json:"column_3"`
}

type GetAttendanceSummaryRow struct {
	TotalClasses    int32 `json:"total_classes"`
	AttendedClasses int32 `json:"attended_classes"`
}

// Returns total classes held and attended for a student in a course/session
func (q *Queries) GetAttendanceSummary(ctx context.Context, arg GetAttendanceSummaryParams) (GetAttendanceSummaryRow, error) {
	row := q.db.QueryRow(ctx, getAttendanceSummary, arg.CourseID, arg.SessionID, arg.Column3)
	var i GetAttendanceSummaryRow
	err := row.Scan(&i.TotalClasses, &i.AttendedClasses)
	return i, err
}

const listCourseAttendanceSheets = `-- name: ListCourseAttendanceSheets :many
SELECT id, course_id, date, class_rep_id, attendance_data, pdf_url, status, finalized_at, emailed_to_lecturer, session_id, created_at FROM attendance_sheets
WHERE course_id = $1 AND session_id = $2
ORDER BY date DESC
LIMIT $3 OFFSET $4
`

type ListCourseAttendanceSheetsParams struct {
	CourseID  uuid.UUID `json:"course_id"`
	SessionID uuid.UUID `json:"session_id"`
	Limit     int32     `json:"limit"`
	Offset    int32     `json:"offset"`
}

func (q *Queries) ListCourseAttendanceSheets(ctx context.Context, arg ListCourseAttendanceSheetsParams) ([]AttendanceSheet, error) {
	rows, err := q.db.Query(ctx, listCourseAttendanceSheets,
		arg.CourseID,
		arg.SessionID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AttendanceSheet{}
	for rows.Next() {
		var i AttendanceSheet
		if err := rows.Scan(
			&i.ID,
			&i.CourseID,
			&i.Date,
			&i.ClassRepID,
			&i.AttendanceData,
			&i.PdfUrl,
			&i.Status,
			&i.FinalizedAt,
			&i.EmailedToLecturer,
			&i.SessionID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStudentAttendance = `-- name: ListStudentAttendance :many
SELECT id, course_id, date, class_rep_id, attendance_data, pdf_url, status, finalized_at, emailed_to_lecturer, session_id, created_at FROM attendance_sheets
WHERE session_id = $1
  AND attendance_data @> jsonb_build_array(jsonb_build_object('student_id', $2::text))
ORDER BY date DESC
`

type ListStudentAttendanceParams struct {
	SessionID uuid.UUID `json:"session_id"`
	Column2   string    `json:"column_2"`
}

// Returns attendance sheets for a session where the student appears in attendance_data
func (q *Queries) ListStudentAttendance(ctx context.Context, arg ListStudentAttendanceParams) ([]AttendanceSheet, error) {
	rows, err := q.db.Query(ctx, listStudentAttendance, arg.SessionID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AttendanceSheet{}
	for rows.Next() {
		var i AttendanceSheet
		if err := rows.Scan(
			&i.ID,
			&i.CourseID,
			&i.Date,
			&i.ClassRepID,
			&i.AttendanceData,
			&i.PdfUrl,
			&i.Status,
			&i.FinalizedAt,
			&i.EmailedToLecturer,
			&i.SessionID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAttendanceSheet = `-- name: UpdateAttendanceSheet :one
UPDATE attendance_sheets
SET
    attendance_data = $2,
    status = $3,
    pdf_url = $4,
    finalized_at = CASE WHEN $3 = 'finalized' THEN NOW() ELSE finalized_at END,
    emailed_to_lecturer = $5
WHERE id = $1
RETURNING id, course_id, date, class_rep_id, attendance_data, pdf_url, status, finalized_at, emailed_to_lecturer, session_id, created_at
`

type UpdateAttendanceSheetParams struct {
	ID                uuid.UUID       `json:"id"`
	AttendanceData    json.RawMessage `json:"attendance_data"`
	Status            string          `json:"status"`
	PdfUrl            *string         `json:"pdf_url"`
	EmailedToLecturer bool            `json:"emailed_to_lecturer"`
}

func (q *Queries) UpdateAttendanceSheet(ctx context.Context, arg UpdateAttendanceSheetParams) (AttendanceSheet, error) {
	row := q.db.QueryRow(ctx, updateAttendanceSheet,
		arg.ID,
		arg.AttendanceData,
		arg.Status,
		arg.PdfUrl,
		arg.EmailedToLecturer,
	)
	var i AttendanceSheet
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.Date,
		&i.ClassRepID,
		&i.AttendanceData,
		&i.PdfUrl,
		&i.Status,
		&i.FinalizedAt,
		&i.EmailedToLecturer,
		&i.SessionID,
		&i.CreatedAt,
	)
	return i, err
}
