// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: class_rep.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const castElectionVote = `-- name: CastElectionVote :one

INSERT INTO election_votes (
    election_id, nominee_id, voter_id
) VALUES (
    $1, $2, $3
) RETURNING id, election_id, nominee_id, voter_id, voted_at
`

type CastElectionVoteParams struct {
	ElectionID uuid.UUID `json:"election_id"`
	NomineeID  uuid.UUID `json:"nominee_id"`
	VoterID    uuid.UUID `json:"voter_id"`
}

// Vote Queries
func (q *Queries) CastElectionVote(ctx context.Context, arg CastElectionVoteParams) (ElectionVote, error) {
	row := q.db.QueryRow(ctx, castElectionVote, arg.ElectionID, arg.NomineeID, arg.VoterID)
	var i ElectionVote
	err := row.Scan(
		&i.ID,
		&i.ElectionID,
		&i.NomineeID,
		&i.VoterID,
		&i.VotedAt,
	)
	return i, err
}

const checkInStudent = `-- name: CheckInStudent :one
INSERT INTO attendance_checkins (
    session_id, student_id, method, present, remark
) VALUES (
    $1, $2, $3, $4, $5
) ON CONFLICT (session_id, student_id) DO UPDATE
SET present = EXCLUDED.present, method = EXCLUDED.method, remark = EXCLUDED.remark, checked_in_at = NOW()
RETURNING id, session_id, student_id, checked_in_at, method, present, remark
`

type CheckInStudentParams struct {
	SessionID uuid.UUID `json:"session_id"`
	StudentID uuid.UUID `json:"student_id"`
	Method    string    `json:"method"`
	Present   bool      `json:"present"`
	Remark    *string   `json:"remark"`
}

func (q *Queries) CheckInStudent(ctx context.Context, arg CheckInStudentParams) (AttendanceCheckin, error) {
	row := q.db.QueryRow(ctx, checkInStudent,
		arg.SessionID,
		arg.StudentID,
		arg.Method,
		arg.Present,
		arg.Remark,
	)
	var i AttendanceCheckin
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.StudentID,
		&i.CheckedInAt,
		&i.Method,
		&i.Present,
		&i.Remark,
	)
	return i, err
}

const completeElection = `-- name: CompleteElection :one
UPDATE class_rep_elections
SET status = 'completed', winner_id = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, level, academic_year, created_by, status, nomination_start, nomination_end, voting_start, voting_end, winner_id, total_votes, created_at, updated_at
`

type CompleteElectionParams struct {
	ID       uuid.UUID   `json:"id"`
	WinnerID pgtype.UUID `json:"winner_id"`
}

func (q *Queries) CompleteElection(ctx context.Context, arg CompleteElectionParams) (ClassRepElection, error) {
	row := q.db.QueryRow(ctx, completeElection, arg.ID, arg.WinnerID)
	var i ClassRepElection
	err := row.Scan(
		&i.ID,
		&i.Level,
		&i.AcademicYear,
		&i.CreatedBy,
		&i.Status,
		&i.NominationStart,
		&i.NominationEnd,
		&i.VotingStart,
		&i.VotingEnd,
		&i.WinnerID,
		&i.TotalVotes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createAttendanceSession = `-- name: CreateAttendanceSession :one

INSERT INTO attendance_sessions (
    course_id, class_rep_id, method, venue, status
) VALUES (
    $1, $2, $3, $4, $5
) RETURNING id, course_id, class_rep_id, session_id, semester_id, date, method, venue, status, started_at, closed_at, total_present, total_absent, total_students, created_at
`

type CreateAttendanceSessionParams struct {
	CourseID   uuid.UUID `json:"course_id"`
	ClassRepID uuid.UUID `json:"class_rep_id"`
	Method     string    `json:"method"`
	Venue      *string   `json:"venue"`
	Status     string    `json:"status"`
}

// Attendance Session Queries (enhanced)
func (q *Queries) CreateAttendanceSession(ctx context.Context, arg CreateAttendanceSessionParams) (AttendanceSession, error) {
	row := q.db.QueryRow(ctx, createAttendanceSession,
		arg.CourseID,
		arg.ClassRepID,
		arg.Method,
		arg.Venue,
		arg.Status,
	)
	var i AttendanceSession
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.ClassRepID,
		&i.SessionID,
		&i.SemesterID,
		&i.Date,
		&i.Method,
		&i.Venue,
		&i.Status,
		&i.StartedAt,
		&i.ClosedAt,
		&i.TotalPresent,
		&i.TotalAbsent,
		&i.TotalStudents,
		&i.CreatedAt,
	)
	return i, err
}

const createClassRepAssignment = `-- name: CreateClassRepAssignment :one

INSERT INTO class_rep_assignments (
    class_rep_id, level, academic_year, appointment_type, appointed_by, consecutive_terms
) VALUES (
    $1, $2, $3, $4, $5, $6
) RETURNING id, class_rep_id, level, academic_year, appointment_type, appointed_by, start_date, end_date, is_active, consecutive_terms, created_at, updated_at
`

type CreateClassRepAssignmentParams struct {
	ClassRepID       uuid.UUID   `json:"class_rep_id"`
	Level            int32       `json:"level"`
	AcademicYear     string      `json:"academic_year"`
	AppointmentType  string      `json:"appointment_type"`
	AppointedBy      pgtype.UUID `json:"appointed_by"`
	ConsecutiveTerms int32       `json:"consecutive_terms"`
}

// Class Rep Assignment Queries
func (q *Queries) CreateClassRepAssignment(ctx context.Context, arg CreateClassRepAssignmentParams) (ClassRepAssignment, error) {
	row := q.db.QueryRow(ctx, createClassRepAssignment,
		arg.ClassRepID,
		arg.Level,
		arg.AcademicYear,
		arg.AppointmentType,
		arg.AppointedBy,
		arg.ConsecutiveTerms,
	)
	var i ClassRepAssignment
	err := row.Scan(
		&i.ID,
		&i.ClassRepID,
		&i.Level,
		&i.AcademicYear,
		&i.AppointmentType,
		&i.AppointedBy,
		&i.StartDate,
		&i.EndDate,
		&i.IsActive,
		&i.ConsecutiveTerms,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createClassRepElection = `-- name: CreateClassRepElection :one

INSERT INTO class_rep_elections (
    level, academic_year, created_by, status, nomination_start, nomination_end, voting_start, voting_end
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
) RETURNING id, level, academic_year, created_by, status, nomination_start, nomination_end, voting_start, voting_end, winner_id, total_votes, created_at, updated_at
`

type CreateClassRepElectionParams struct {
	Level           int32              `json:"level"`
	AcademicYear    string             `json:"academic_year"`
	CreatedBy       uuid.UUID          `json:"created_by"`
	Status          string             `json:"status"`
	NominationStart pgtype.Timestamptz `json:"nomination_start"`
	NominationEnd   pgtype.Timestamptz `json:"nomination_end"`
	VotingStart     pgtype.Timestamptz `json:"voting_start"`
	VotingEnd       pgtype.Timestamptz `json:"voting_end"`
}

// Election Queries
func (q *Queries) CreateClassRepElection(ctx context.Context, arg CreateClassRepElectionParams) (ClassRepElection, error) {
	row := q.db.QueryRow(ctx, createClassRepElection,
		arg.Level,
		arg.AcademicYear,
		arg.CreatedBy,
		arg.Status,
		arg.NominationStart,
		arg.NominationEnd,
		arg.VotingStart,
		arg.VotingEnd,
	)
	var i ClassRepElection
	err := row.Scan(
		&i.ID,
		&i.Level,
		&i.AcademicYear,
		&i.CreatedBy,
		&i.Status,
		&i.NominationStart,
		&i.NominationEnd,
		&i.VotingStart,
		&i.VotingEnd,
		&i.WinnerID,
		&i.TotalVotes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createClassRepPerformanceReview = `-- name: CreateClassRepPerformanceReview :one
INSERT INTO class_rep_performance (class_rep_id, reviewed_by, academic_year, term, attendance_rate, reports_submitted, responsiveness_score, comments, rating)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, class_rep_id, reviewed_by, academic_year, term, attendance_rate, reports_submitted, responsiveness_score, comments, rating, created_at
`

type CreateClassRepPerformanceReviewParams struct {
	ClassRepID          uuid.UUID      `json:"class_rep_id"`
	ReviewedBy          uuid.UUID      `json:"reviewed_by"`
	AcademicYear        string         `json:"academic_year"`
	Term                string         `json:"term"`
	AttendanceRate      pgtype.Numeric `json:"attendance_rate"`
	ReportsSubmitted    int32          `json:"reports_submitted"`
	ResponsivenessScore *int32         `json:"responsiveness_score"`
	Comments            *string        `json:"comments"`
	Rating              *string        `json:"rating"`
}

func (q *Queries) CreateClassRepPerformanceReview(ctx context.Context, arg CreateClassRepPerformanceReviewParams) (ClassRepPerformance, error) {
	row := q.db.QueryRow(ctx, createClassRepPerformanceReview,
		arg.ClassRepID,
		arg.ReviewedBy,
		arg.AcademicYear,
		arg.Term,
		arg.AttendanceRate,
		arg.ReportsSubmitted,
		arg.ResponsivenessScore,
		arg.Comments,
		arg.Rating,
	)
	var i ClassRepPerformance
	err := row.Scan(
		&i.ID,
		&i.ClassRepID,
		&i.ReviewedBy,
		&i.AcademicYear,
		&i.Term,
		&i.AttendanceRate,
		&i.ReportsSubmitted,
		&i.ResponsivenessScore,
		&i.Comments,
		&i.Rating,
		&i.CreatedAt,
	)
	return i, err
}

const createClassRepReport = `-- name: CreateClassRepReport :one

INSERT INTO class_rep_reports (
    class_rep_id, report_type, title, content, level, academic_year, status
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
) RETURNING id, class_rep_id, report_type, title, content, level, academic_year, status, reviewed_by, review_notes, created_at, updated_at
`

type CreateClassRepReportParams struct {
	ClassRepID   uuid.UUID `json:"class_rep_id"`
	ReportType   string    `json:"report_type"`
	Title        string    `json:"title"`
	Content      string    `json:"content"`
	Level        *int32    `json:"level"`
	AcademicYear *string   `json:"academic_year"`
	Status       string    `json:"status"`
}

// Report Queries
func (q *Queries) CreateClassRepReport(ctx context.Context, arg CreateClassRepReportParams) (ClassRepReport, error) {
	row := q.db.QueryRow(ctx, createClassRepReport,
		arg.ClassRepID,
		arg.ReportType,
		arg.Title,
		arg.Content,
		arg.Level,
		arg.AcademicYear,
		arg.Status,
	)
	var i ClassRepReport
	err := row.Scan(
		&i.ID,
		&i.ClassRepID,
		&i.ReportType,
		&i.Title,
		&i.Content,
		&i.Level,
		&i.AcademicYear,
		&i.Status,
		&i.ReviewedBy,
		&i.ReviewNotes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createElectionNominee = `-- name: CreateElectionNominee :one

INSERT INTO election_nominees (
    election_id, student_id, manifesto, nominated_by, status
) VALUES (
    $1, $2, $3, $4, $5
) RETURNING id, election_id, student_id, manifesto, nominated_by, status, approved_by, created_at
`

type CreateElectionNomineeParams struct {
	ElectionID  uuid.UUID `json:"election_id"`
	StudentID   uuid.UUID `json:"student_id"`
	Manifesto   *string   `json:"manifesto"`
	NominatedBy uuid.UUID `json:"nominated_by"`
	Status      string    `json:"status"`
}

// Nominee Queries
func (q *Queries) CreateElectionNominee(ctx context.Context, arg CreateElectionNomineeParams) (ElectionNominee, error) {
	row := q.db.QueryRow(ctx, createElectionNominee,
		arg.ElectionID,
		arg.StudentID,
		arg.Manifesto,
		arg.NominatedBy,
		arg.Status,
	)
	var i ElectionNominee
	err := row.Scan(
		&i.ID,
		&i.ElectionID,
		&i.StudentID,
		&i.Manifesto,
		&i.NominatedBy,
		&i.Status,
		&i.ApprovedBy,
		&i.CreatedAt,
	)
	return i, err
}

const deactivateClassRepByID = `-- name: DeactivateClassRepByID :exec
UPDATE class_rep_assignments SET is_active = false WHERE id = $1
`

func (q *Queries) DeactivateClassRepByID(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deactivateClassRepByID, id)
	return err
}

const deactivateClassRepByLevel = `-- name: DeactivateClassRepByLevel :exec
UPDATE class_rep_assignments
SET is_active = false, end_date = NOW(), updated_at = NOW()
WHERE level = $1 AND academic_year = $2 AND is_active = true
`

type DeactivateClassRepByLevelParams struct {
	Level        int32  `json:"level"`
	AcademicYear string `json:"academic_year"`
}

func (q *Queries) DeactivateClassRepByLevel(ctx context.Context, arg DeactivateClassRepByLevelParams) error {
	_, err := q.db.Exec(ctx, deactivateClassRepByLevel, arg.Level, arg.AcademicYear)
	return err
}

const getActiveClassRepAssignment = `-- name: GetActiveClassRepAssignment :one
SELECT id, class_rep_id, level, academic_year, appointment_type, appointed_by, start_date, end_date, is_active, consecutive_terms, created_at, updated_at FROM class_rep_assignments
WHERE class_rep_id = $1 AND is_active = true
LIMIT 1
`

func (q *Queries) GetActiveClassRepAssignment(ctx context.Context, classRepID uuid.UUID) (ClassRepAssignment, error) {
	row := q.db.QueryRow(ctx, getActiveClassRepAssignment, classRepID)
	var i ClassRepAssignment
	err := row.Scan(
		&i.ID,
		&i.ClassRepID,
		&i.Level,
		&i.AcademicYear,
		&i.AppointmentType,
		&i.AppointedBy,
		&i.StartDate,
		&i.EndDate,
		&i.IsActive,
		&i.ConsecutiveTerms,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getClassRepElection = `-- name: GetClassRepElection :one
SELECT id, level, academic_year, created_by, status, nomination_start, nomination_end, voting_start, voting_end, winner_id, total_votes, created_at, updated_at FROM class_rep_elections
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetClassRepElection(ctx context.Context, id uuid.UUID) (ClassRepElection, error) {
	row := q.db.QueryRow(ctx, getClassRepElection, id)
	var i ClassRepElection
	err := row.Scan(
		&i.ID,
		&i.Level,
		&i.AcademicYear,
		&i.CreatedBy,
		&i.Status,
		&i.NominationStart,
		&i.NominationEnd,
		&i.VotingStart,
		&i.VotingEnd,
		&i.WinnerID,
		&i.TotalVotes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getElectionResults = `-- name: GetElectionResults :many
SELECT en.id, en.election_id, en.student_id, en.manifesto, en.nominated_by, en.status, en.approved_by, en.created_at, COUNT(ev.id)::int as vote_count
FROM election_nominees en
LEFT JOIN election_votes ev ON ev.nominee_id = en.id
WHERE en.election_id = $1
GROUP BY en.id
ORDER BY vote_count DESC
`

type GetElectionResultsRow struct {
	ID          uuid.UUID          `json:"id"`
	ElectionID  uuid.UUID          `json:"election_id"`
	StudentID   uuid.UUID          `json:"student_id"`
	Manifesto   *string            `json:"manifesto"`
	NominatedBy uuid.UUID          `json:"nominated_by"`
	Status      string             `json:"status"`
	ApprovedBy  pgtype.UUID        `json:"approved_by"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	VoteCount   int32              `json:"vote_count"`
}

func (q *Queries) GetElectionResults(ctx context.Context, electionID uuid.UUID) ([]GetElectionResultsRow, error) {
	rows, err := q.db.Query(ctx, getElectionResults, electionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetElectionResultsRow{}
	for rows.Next() {
		var i GetElectionResultsRow
		if err := rows.Scan(
			&i.ID,
			&i.ElectionID,
			&i.StudentID,
			&i.Manifesto,
			&i.NominatedBy,
			&i.Status,
			&i.ApprovedBy,
			&i.CreatedAt,
			&i.VoteCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getElectionWinner = `-- name: GetElectionWinner :one
SELECT en.id, en.election_id, en.student_id, en.manifesto, en.nominated_by, en.status, en.approved_by, en.created_at, COUNT(ev.id)::int as vote_count
FROM election_nominees en
LEFT JOIN election_votes ev ON ev.nominee_id = en.id
WHERE en.election_id = $1
GROUP BY en.id
ORDER BY vote_count DESC
LIMIT 1
`

type GetElectionWinnerRow struct {
	ID          uuid.UUID          `json:"id"`
	ElectionID  uuid.UUID          `json:"election_id"`
	StudentID   uuid.UUID          `json:"student_id"`
	Manifesto   *string            `json:"manifesto"`
	NominatedBy uuid.UUID          `json:"nominated_by"`
	Status      string             `json:"status"`
	ApprovedBy  pgtype.UUID        `json:"approved_by"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	VoteCount   int32              `json:"vote_count"`
}

func (q *Queries) GetElectionWinner(ctx context.Context, electionID uuid.UUID) (GetElectionWinnerRow, error) {
	row := q.db.QueryRow(ctx, getElectionWinner, electionID)
	var i GetElectionWinnerRow
	err := row.Scan(
		&i.ID,
		&i.ElectionID,
		&i.StudentID,
		&i.Manifesto,
		&i.NominatedBy,
		&i.Status,
		&i.ApprovedBy,
		&i.CreatedAt,
		&i.VoteCount,
	)
	return i, err
}

const incrementElectionVotes = `-- name: IncrementElectionVotes :exec
UPDATE class_rep_elections
SET total_votes = total_votes + 1, updated_at = NOW()
WHERE id = $1
`

func (q *Queries) IncrementElectionVotes(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, incrementElectionVotes, id)
	return err
}

const listActiveClassRepAssignments = `-- name: ListActiveClassRepAssignments :many
SELECT id, class_rep_id, level, academic_year, appointment_type, appointed_by, start_date, end_date, is_active, consecutive_terms, created_at, updated_at FROM class_rep_assignments
WHERE is_active = true
ORDER BY level, academic_year
`

func (q *Queries) ListActiveClassRepAssignments(ctx context.Context) ([]ClassRepAssignment, error) {
	rows, err := q.db.Query(ctx, listActiveClassRepAssignments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ClassRepAssignment{}
	for rows.Next() {
		var i ClassRepAssignment
		if err := rows.Scan(
			&i.ID,
			&i.ClassRepID,
			&i.Level,
			&i.AcademicYear,
			&i.AppointmentType,
			&i.AppointedBy,
			&i.StartDate,
			&i.EndDate,
			&i.IsActive,
			&i.ConsecutiveTerms,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllClassRepReports = `-- name: ListAllClassRepReports :many
SELECT cr.id, cr.class_rep_id, cr.report_type, cr.title, cr.content, cr.level, cr.academic_year, cr.status, cr.reviewed_by, cr.review_notes, cr.created_at, cr.updated_at, u.full_name as class_rep_name
FROM class_rep_reports cr
JOIN users u ON u.id = cr.class_rep_id
WHERE ($1::text IS NULL OR cr.status = $1)
ORDER BY cr.created_at DESC
`

type ListAllClassRepReportsRow struct {
	ID           uuid.UUID          `json:"id"`
	ClassRepID   uuid.UUID          `json:"class_rep_id"`
	ReportType   string             `json:"report_type"`
	Title        string             `json:"title"`
	Content      string             `json:"content"`
	Level        *int32             `json:"level"`
	AcademicYear *string            `json:"academic_year"`
	Status       string             `json:"status"`
	ReviewedBy   pgtype.UUID        `json:"reviewed_by"`
	ReviewNotes  *string            `json:"review_notes"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	ClassRepName string             `json:"class_rep_name"`
}

func (q *Queries) ListAllClassRepReports(ctx context.Context, dollar_1 string) ([]ListAllClassRepReportsRow, error) {
	rows, err := q.db.Query(ctx, listAllClassRepReports, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAllClassRepReportsRow{}
	for rows.Next() {
		var i ListAllClassRepReportsRow
		if err := rows.Scan(
			&i.ID,
			&i.ClassRepID,
			&i.ReportType,
			&i.Title,
			&i.Content,
			&i.Level,
			&i.AcademicYear,
			&i.Status,
			&i.ReviewedBy,
			&i.ReviewNotes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ClassRepName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAttendanceSessionCheckins = `-- name: ListAttendanceSessionCheckins :many
SELECT ac.id, ac.session_id, ac.student_id, ac.checked_in_at, ac.method, ac.present, ac.remark, u.full_name as student_name, s.matric_number
FROM attendance_checkins ac
JOIN users u ON u.id = ac.student_id
JOIN students s ON s.user_id = u.id
WHERE ac.session_id = $1
ORDER BY ac.checked_in_at
`

type ListAttendanceSessionCheckinsRow struct {
	ID           uuid.UUID          `json:"id"`
	SessionID    uuid.UUID          `json:"session_id"`
	StudentID    uuid.UUID          `json:"student_id"`
	CheckedInAt  pgtype.Timestamptz `json:"checked_in_at"`
	Method       string             `json:"method"`
	Present      bool               `json:"present"`
	Remark       *string            `json:"remark"`
	StudentName  string             `json:"student_name"`
	MatricNumber string             `json:"matric_number"`
}

func (q *Queries) ListAttendanceSessionCheckins(ctx context.Context, sessionID uuid.UUID) ([]ListAttendanceSessionCheckinsRow, error) {
	rows, err := q.db.Query(ctx, listAttendanceSessionCheckins, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAttendanceSessionCheckinsRow{}
	for rows.Next() {
		var i ListAttendanceSessionCheckinsRow
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.StudentID,
			&i.CheckedInAt,
			&i.Method,
			&i.Present,
			&i.Remark,
			&i.StudentName,
			&i.MatricNumber,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAttendanceSessionsByRep = `-- name: ListAttendanceSessionsByRep :many
SELECT id, class_rep_id, course_id, date, method, venue, status, total_students, total_present, total_absent, created_at
FROM attendance_sessions
WHERE class_rep_id = $1
ORDER BY created_at DESC
`

type ListAttendanceSessionsByRepRow struct {
	ID            uuid.UUID          `json:"id"`
	ClassRepID    uuid.UUID          `json:"class_rep_id"`
	CourseID      uuid.UUID          `json:"course_id"`
	Date          pgtype.Timestamptz `json:"date"`
	Method        string             `json:"method"`
	Venue         *string            `json:"venue"`
	Status        string             `json:"status"`
	TotalStudents int32              `json:"total_students"`
	TotalPresent  int32              `json:"total_present"`
	TotalAbsent   int32              `json:"total_absent"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListAttendanceSessionsByRep(ctx context.Context, classRepID uuid.UUID) ([]ListAttendanceSessionsByRepRow, error) {
	rows, err := q.db.Query(ctx, listAttendanceSessionsByRep, classRepID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAttendanceSessionsByRepRow{}
	for rows.Next() {
		var i ListAttendanceSessionsByRepRow
		if err := rows.Scan(
			&i.ID,
			&i.ClassRepID,
			&i.CourseID,
			&i.Date,
			&i.Method,
			&i.Venue,
			&i.Status,
			&i.TotalStudents,
			&i.TotalPresent,
			&i.TotalAbsent,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listClassRepElections = `-- name: ListClassRepElections :many
SELECT id, level, academic_year, created_by, status, nomination_start, nomination_end, voting_start, voting_end, winner_id, total_votes, created_at, updated_at FROM class_rep_elections
WHERE ($1::int IS NULL OR level = $1)
ORDER BY created_at DESC
`

func (q *Queries) ListClassRepElections(ctx context.Context, dollar_1 int32) ([]ClassRepElection, error) {
	rows, err := q.db.Query(ctx, listClassRepElections, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ClassRepElection{}
	for rows.Next() {
		var i ClassRepElection
		if err := rows.Scan(
			&i.ID,
			&i.Level,
			&i.AcademicYear,
			&i.CreatedBy,
			&i.Status,
			&i.NominationStart,
			&i.NominationEnd,
			&i.VotingStart,
			&i.VotingEnd,
			&i.WinnerID,
			&i.TotalVotes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listClassRepPerformanceReviews = `-- name: ListClassRepPerformanceReviews :many
SELECT id, class_rep_id, reviewed_by, academic_year, term, attendance_rate, reports_submitted, responsiveness_score, comments, rating, created_at
FROM class_rep_performance
WHERE class_rep_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListClassRepPerformanceReviews(ctx context.Context, classRepID uuid.UUID) ([]ClassRepPerformance, error) {
	rows, err := q.db.Query(ctx, listClassRepPerformanceReviews, classRepID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ClassRepPerformance{}
	for rows.Next() {
		var i ClassRepPerformance
		if err := rows.Scan(
			&i.ID,
			&i.ClassRepID,
			&i.ReviewedBy,
			&i.AcademicYear,
			&i.Term,
			&i.AttendanceRate,
			&i.ReportsSubmitted,
			&i.ResponsivenessScore,
			&i.Comments,
			&i.Rating,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listClassRepReportsByRep = `-- name: ListClassRepReportsByRep :many
SELECT id, class_rep_id, report_type, title, content, level, academic_year, status, reviewed_by, review_notes, created_at, updated_at FROM class_rep_reports
WHERE class_rep_id = $1
  AND ($2::text IS NULL OR status = $2)
ORDER BY created_at DESC
`

type ListClassRepReportsByRepParams struct {
	ClassRepID uuid.UUID `json:"class_rep_id"`
	Column2    string    `json:"column_2"`
}

func (q *Queries) ListClassRepReportsByRep(ctx context.Context, arg ListClassRepReportsByRepParams) ([]ClassRepReport, error) {
	rows, err := q.db.Query(ctx, listClassRepReportsByRep, arg.ClassRepID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ClassRepReport{}
	for rows.Next() {
		var i ClassRepReport
		if err := rows.Scan(
			&i.ID,
			&i.ClassRepID,
			&i.ReportType,
			&i.Title,
			&i.Content,
			&i.Level,
			&i.AcademicYear,
			&i.Status,
			&i.ReviewedBy,
			&i.ReviewNotes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listElectionNominees = `-- name: ListElectionNominees :many
SELECT en.id, en.election_id, en.student_id, en.manifesto, en.nominated_by, en.status, en.approved_by, en.created_at, u.full_name as student_name
FROM election_nominees en
JOIN users u ON u.id = en.student_id
WHERE en.election_id = $1
ORDER BY en.created_at
`

type ListElectionNomineesRow struct {
	ID          uuid.UUID          `json:"id"`
	ElectionID  uuid.UUID          `json:"election_id"`
	StudentID   uuid.UUID          `json:"student_id"`
	Manifesto   *string            `json:"manifesto"`
	NominatedBy uuid.UUID          `json:"nominated_by"`
	Status      string             `json:"status"`
	ApprovedBy  pgtype.UUID        `json:"approved_by"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	StudentName string             `json:"student_name"`
}

func (q *Queries) ListElectionNominees(ctx context.Context, electionID uuid.UUID) ([]ListElectionNomineesRow, error) {
	rows, err := q.db.Query(ctx, listElectionNominees, electionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListElectionNomineesRow{}
	for rows.Next() {
		var i ListElectionNomineesRow
		if err := rows.Scan(
			&i.ID,
			&i.ElectionID,
			&i.StudentID,
			&i.Manifesto,
			&i.NominatedBy,
			&i.Status,
			&i.ApprovedBy,
			&i.CreatedAt,
			&i.StudentName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingCourseRegistrationsByLevel = `-- name: ListPendingCourseRegistrationsByLevel :many
SELECT cr.id, cr.student_id, s.level, cr.session_id, cr.status, cr.created_at,
       u.full_name as student_name, st.matric_number,
       COUNT(rc.id) as courses_count
FROM course_registrations cr
JOIN students st ON st.id = cr.student_id
JOIN users u ON u.id = st.user_id
JOIN students s ON s.id = cr.student_id
LEFT JOIN registered_courses rc ON rc.registration_id = cr.id
WHERE cr.status = 'pending' AND s.level = $1
GROUP BY cr.id, cr.student_id, s.level, cr.session_id, cr.status, cr.created_at, u.full_name, st.matric_number
ORDER BY cr.created_at DESC
`

type ListPendingCourseRegistrationsByLevelRow struct {
	ID           uuid.UUID          `json:"id"`
	StudentID    uuid.UUID          `json:"student_id"`
	Level        int32              `json:"level"`
	SessionID    uuid.UUID          `json:"session_id"`
	Status       string             `json:"status"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	StudentName  string             `json:"student_name"`
	MatricNumber string             `json:"matric_number"`
	CoursesCount int64              `json:"courses_count"`
}

func (q *Queries) ListPendingCourseRegistrationsByLevel(ctx context.Context, level int32) ([]ListPendingCourseRegistrationsByLevelRow, error) {
	rows, err := q.db.Query(ctx, listPendingCourseRegistrationsByLevel, level)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPendingCourseRegistrationsByLevelRow{}
	for rows.Next() {
		var i ListPendingCourseRegistrationsByLevelRow
		if err := rows.Scan(
			&i.ID,
			&i.StudentID,
			&i.Level,
			&i.SessionID,
			&i.Status,
			&i.CreatedAt,
			&i.StudentName,
			&i.MatricNumber,
			&i.CoursesCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStudentsByLevel = `-- name: ListStudentsByLevel :many
SELECT id, user_id, matric_number, level, entry_year, current_session_id, current_semester, cgpa, total_credits_earned, total_credits_required, academic_standing, graduation_status, is_defaulter, defaulter_reason, created_at, updated_at, admission_mode, year_admitted, onboarding_completed FROM students
WHERE level = $1
ORDER BY matric_number
`

func (q *Queries) ListStudentsByLevel(ctx context.Context, level int32) ([]Student, error) {
	rows, err := q.db.Query(ctx, listStudentsByLevel, level)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Student{}
	for rows.Next() {
		var i Student
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.MatricNumber,
			&i.Level,
			&i.EntryYear,
			&i.CurrentSessionID,
			&i.CurrentSemester,
			&i.Cgpa,
			&i.TotalCreditsEarned,
			&i.TotalCreditsRequired,
			&i.AcademicStanding,
			&i.GraduationStatus,
			&i.IsDefaulter,
			&i.DefaulterReason,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AdmissionMode,
			&i.YearAdmitted,
			&i.OnboardingCompleted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAttendanceSessionCounts = `-- name: UpdateAttendanceSessionCounts :exec
UPDATE attendance_sessions AS asess
SET
    total_present = (SELECT COUNT(*)::int FROM attendance_checkins WHERE session_id = asess.id AND present = true),
    total_absent = (SELECT COUNT(*)::int FROM attendance_checkins WHERE session_id = asess.id AND present = false),
    total_students = (SELECT COUNT(*)::int FROM attendance_checkins WHERE session_id = asess.id)
WHERE asess.id = $1
`

func (q *Queries) UpdateAttendanceSessionCounts(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, updateAttendanceSessionCounts, id)
	return err
}

const updateAttendanceSessionStatus = `-- name: UpdateAttendanceSessionStatus :one
UPDATE attendance_sessions
SET status = $2,
    started_at = CASE WHEN $2 = 'open' THEN NOW() ELSE started_at END,
    closed_at = CASE WHEN $2 = 'closed' OR $2 = 'finalized' THEN NOW() ELSE closed_at END
WHERE id = $1
RETURNING id, course_id, class_rep_id, session_id, semester_id, date, method, venue, status, started_at, closed_at, total_present, total_absent, total_students, created_at
`

type UpdateAttendanceSessionStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) UpdateAttendanceSessionStatus(ctx context.Context, arg UpdateAttendanceSessionStatusParams) (AttendanceSession, error) {
	row := q.db.QueryRow(ctx, updateAttendanceSessionStatus, arg.ID, arg.Status)
	var i AttendanceSession
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.ClassRepID,
		&i.SessionID,
		&i.SemesterID,
		&i.Date,
		&i.Method,
		&i.Venue,
		&i.Status,
		&i.StartedAt,
		&i.ClosedAt,
		&i.TotalPresent,
		&i.TotalAbsent,
		&i.TotalStudents,
		&i.CreatedAt,
	)
	return i, err
}

const updateClassRepReportStatus = `-- name: UpdateClassRepReportStatus :one
UPDATE class_rep_reports
SET status = $2, reviewed_by = $3, review_notes = $4, updated_at = NOW()
WHERE id = $1
RETURNING id, class_rep_id, report_type, title, content, level, academic_year, status, reviewed_by, review_notes, created_at, updated_at
`

type UpdateClassRepReportStatusParams struct {
	ID          uuid.UUID   `json:"id"`
	Status      string      `json:"status"`
	ReviewedBy  pgtype.UUID `json:"reviewed_by"`
	ReviewNotes *string     `json:"review_notes"`
}

func (q *Queries) UpdateClassRepReportStatus(ctx context.Context, arg UpdateClassRepReportStatusParams) (ClassRepReport, error) {
	row := q.db.QueryRow(ctx, updateClassRepReportStatus,
		arg.ID,
		arg.Status,
		arg.ReviewedBy,
		arg.ReviewNotes,
	)
	var i ClassRepReport
	err := row.Scan(
		&i.ID,
		&i.ClassRepID,
		&i.ReportType,
		&i.Title,
		&i.Content,
		&i.Level,
		&i.AcademicYear,
		&i.Status,
		&i.ReviewedBy,
		&i.ReviewNotes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateElectionNomineeStatus = `-- name: UpdateElectionNomineeStatus :one
UPDATE election_nominees SET status = $1 WHERE id = $2
RETURNING id, election_id, student_id, manifesto, status, created_at
`

type UpdateElectionNomineeStatusParams struct {
	Status string    `json:"status"`
	ID     uuid.UUID `json:"id"`
}

type UpdateElectionNomineeStatusRow struct {
	ID         uuid.UUID          `json:"id"`
	ElectionID uuid.UUID          `json:"election_id"`
	StudentID  uuid.UUID          `json:"student_id"`
	Manifesto  *string            `json:"manifesto"`
	Status     string             `json:"status"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) UpdateElectionNomineeStatus(ctx context.Context, arg UpdateElectionNomineeStatusParams) (UpdateElectionNomineeStatusRow, error) {
	row := q.db.QueryRow(ctx, updateElectionNomineeStatus, arg.Status, arg.ID)
	var i UpdateElectionNomineeStatusRow
	err := row.Scan(
		&i.ID,
		&i.ElectionID,
		&i.StudentID,
		&i.Manifesto,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}
