// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: communications.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countNotificationsByCategory = `-- name: CountNotificationsByCategory :many
SELECT category, COUNT(*)::int as count FROM notifications
WHERE user_id = $1 AND is_read = false
GROUP BY category
`

type CountNotificationsByCategoryRow struct {
	Category *string `json:"category"`
	Count    int32   `json:"count"`
}

func (q *Queries) CountNotificationsByCategory(ctx context.Context, userID uuid.UUID) ([]CountNotificationsByCategoryRow, error) {
	rows, err := q.db.Query(ctx, countNotificationsByCategory, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountNotificationsByCategoryRow{}
	for rows.Next() {
		var i CountNotificationsByCategoryRow
		if err := rows.Scan(&i.Category, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createAnnouncement = `-- name: CreateAnnouncement :one
INSERT INTO announcements (
    title, content, is_pinned, target_level, target_audience, expires_at, created_by
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
) RETURNING id, title, content, is_pinned, target_level, target_audience, expires_at, created_by, created_at, summary, priority, category, target_levels, target_departments, attachments, requires_acknowledgment, status, scheduled_for, read_count, acknowledged_count, pin_order, updated_at
`

type CreateAnnouncementParams struct {
	Title          string             `json:"title"`
	Content        string             `json:"content"`
	IsPinned       bool               `json:"is_pinned"`
	TargetLevel    *int32             `json:"target_level"`
	TargetAudience []byte             `json:"target_audience"`
	ExpiresAt      pgtype.Timestamptz `json:"expires_at"`
	CreatedBy      uuid.UUID          `json:"created_by"`
}

func (q *Queries) CreateAnnouncement(ctx context.Context, arg CreateAnnouncementParams) (Announcement, error) {
	row := q.db.QueryRow(ctx, createAnnouncement,
		arg.Title,
		arg.Content,
		arg.IsPinned,
		arg.TargetLevel,
		arg.TargetAudience,
		arg.ExpiresAt,
		arg.CreatedBy,
	)
	var i Announcement
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Content,
		&i.IsPinned,
		&i.TargetLevel,
		&i.TargetAudience,
		&i.ExpiresAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.Summary,
		&i.Priority,
		&i.Category,
		&i.TargetLevels,
		&i.TargetDepartments,
		&i.Attachments,
		&i.RequiresAcknowledgment,
		&i.Status,
		&i.ScheduledFor,
		&i.ReadCount,
		&i.AcknowledgedCount,
		&i.PinOrder,
		&i.UpdatedAt,
	)
	return i, err
}

const createNotification = `-- name: CreateNotification :one
INSERT INTO notifications (
    user_id, type, title, message, action_url, email_sent, category, priority, sender_id, entity_type, entity_id, action_label, image_url, metadata
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14
) RETURNING id, user_id, type, title, message, is_read, action_url, email_sent, created_at, category, priority, sender_id, entity_type, entity_id, action_label, image_url, metadata, expires_at
`

type CreateNotificationParams struct {
	UserID      uuid.UUID   `json:"user_id"`
	Type        string      `json:"type"`
	Title       string      `json:"title"`
	Message     string      `json:"message"`
	ActionUrl   *string     `json:"action_url"`
	EmailSent   bool        `json:"email_sent"`
	Category    *string     `json:"category"`
	Priority    *string     `json:"priority"`
	SenderID    pgtype.UUID `json:"sender_id"`
	EntityType  *string     `json:"entity_type"`
	EntityID    pgtype.UUID `json:"entity_id"`
	ActionLabel *string     `json:"action_label"`
	ImageUrl    *string     `json:"image_url"`
	Metadata    []byte      `json:"metadata"`
}

func (q *Queries) CreateNotification(ctx context.Context, arg CreateNotificationParams) (Notification, error) {
	row := q.db.QueryRow(ctx, createNotification,
		arg.UserID,
		arg.Type,
		arg.Title,
		arg.Message,
		arg.ActionUrl,
		arg.EmailSent,
		arg.Category,
		arg.Priority,
		arg.SenderID,
		arg.EntityType,
		arg.EntityID,
		arg.ActionLabel,
		arg.ImageUrl,
		arg.Metadata,
	)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.Title,
		&i.Message,
		&i.IsRead,
		&i.ActionUrl,
		&i.EmailSent,
		&i.CreatedAt,
		&i.Category,
		&i.Priority,
		&i.SenderID,
		&i.EntityType,
		&i.EntityID,
		&i.ActionLabel,
		&i.ImageUrl,
		&i.Metadata,
		&i.ExpiresAt,
	)
	return i, err
}

const createNotificationForUser = `-- name: CreateNotificationForUser :one
INSERT INTO notifications (
    user_id, type, title, message, action_url, email_sent, category, priority, sender_id, entity_type, entity_id, action_label, image_url, metadata
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14
) RETURNING id, user_id, type, title, message, is_read, action_url, email_sent, created_at, category, priority, sender_id, entity_type, entity_id, action_label, image_url, metadata, expires_at
`

type CreateNotificationForUserParams struct {
	UserID      uuid.UUID   `json:"user_id"`
	Type        string      `json:"type"`
	Title       string      `json:"title"`
	Message     string      `json:"message"`
	ActionUrl   *string     `json:"action_url"`
	EmailSent   bool        `json:"email_sent"`
	Category    *string     `json:"category"`
	Priority    *string     `json:"priority"`
	SenderID    pgtype.UUID `json:"sender_id"`
	EntityType  *string     `json:"entity_type"`
	EntityID    pgtype.UUID `json:"entity_id"`
	ActionLabel *string     `json:"action_label"`
	ImageUrl    *string     `json:"image_url"`
	Metadata    []byte      `json:"metadata"`
}

func (q *Queries) CreateNotificationForUser(ctx context.Context, arg CreateNotificationForUserParams) (Notification, error) {
	row := q.db.QueryRow(ctx, createNotificationForUser,
		arg.UserID,
		arg.Type,
		arg.Title,
		arg.Message,
		arg.ActionUrl,
		arg.EmailSent,
		arg.Category,
		arg.Priority,
		arg.SenderID,
		arg.EntityType,
		arg.EntityID,
		arg.ActionLabel,
		arg.ImageUrl,
		arg.Metadata,
	)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.Title,
		&i.Message,
		&i.IsRead,
		&i.ActionUrl,
		&i.EmailSent,
		&i.CreatedAt,
		&i.Category,
		&i.Priority,
		&i.SenderID,
		&i.EntityType,
		&i.EntityID,
		&i.ActionLabel,
		&i.ImageUrl,
		&i.Metadata,
		&i.ExpiresAt,
	)
	return i, err
}

const deleteAnnouncement = `-- name: DeleteAnnouncement :exec
DELETE FROM announcements
WHERE id = $1
`

func (q *Queries) DeleteAnnouncement(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteAnnouncement, id)
	return err
}

const deleteNotification = `-- name: DeleteNotification :exec
DELETE FROM notifications
WHERE id = $1 AND user_id = $2
`

type DeleteNotificationParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteNotification(ctx context.Context, arg DeleteNotificationParams) error {
	_, err := q.db.Exec(ctx, deleteNotification, arg.ID, arg.UserID)
	return err
}

const getAnnouncement = `-- name: GetAnnouncement :one
SELECT id, title, content, is_pinned, target_level, target_audience, expires_at, created_by, created_at, summary, priority, category, target_levels, target_departments, attachments, requires_acknowledgment, status, scheduled_for, read_count, acknowledged_count, pin_order, updated_at FROM announcements
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetAnnouncement(ctx context.Context, id uuid.UUID) (Announcement, error) {
	row := q.db.QueryRow(ctx, getAnnouncement, id)
	var i Announcement
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Content,
		&i.IsPinned,
		&i.TargetLevel,
		&i.TargetAudience,
		&i.ExpiresAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.Summary,
		&i.Priority,
		&i.Category,
		&i.TargetLevels,
		&i.TargetDepartments,
		&i.Attachments,
		&i.RequiresAcknowledgment,
		&i.Status,
		&i.ScheduledFor,
		&i.ReadCount,
		&i.AcknowledgedCount,
		&i.PinOrder,
		&i.UpdatedAt,
	)
	return i, err
}

const getNotification = `-- name: GetNotification :one
SELECT id, user_id, type, title, message, is_read, action_url, email_sent, created_at, category, priority, sender_id, entity_type, entity_id, action_label, image_url, metadata, expires_at FROM notifications
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetNotification(ctx context.Context, id uuid.UUID) (Notification, error) {
	row := q.db.QueryRow(ctx, getNotification, id)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.Title,
		&i.Message,
		&i.IsRead,
		&i.ActionUrl,
		&i.EmailSent,
		&i.CreatedAt,
		&i.Category,
		&i.Priority,
		&i.SenderID,
		&i.EntityType,
		&i.EntityID,
		&i.ActionLabel,
		&i.ImageUrl,
		&i.Metadata,
		&i.ExpiresAt,
	)
	return i, err
}

const listActiveAnnouncements = `-- name: ListActiveAnnouncements :many
SELECT id, title, content, is_pinned, target_level, target_audience, expires_at, created_by, created_at, summary, priority, category, target_levels, target_departments, attachments, requires_acknowledgment, status, scheduled_for, read_count, acknowledged_count, pin_order, updated_at FROM announcements
WHERE (expires_at IS NULL OR expires_at > NOW())
ORDER BY is_pinned DESC, created_at DESC
LIMIT $1 OFFSET $2
`

type ListActiveAnnouncementsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListActiveAnnouncements(ctx context.Context, arg ListActiveAnnouncementsParams) ([]Announcement, error) {
	rows, err := q.db.Query(ctx, listActiveAnnouncements, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Announcement{}
	for rows.Next() {
		var i Announcement
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Content,
			&i.IsPinned,
			&i.TargetLevel,
			&i.TargetAudience,
			&i.ExpiresAt,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.Summary,
			&i.Priority,
			&i.Category,
			&i.TargetLevels,
			&i.TargetDepartments,
			&i.Attachments,
			&i.RequiresAcknowledgment,
			&i.Status,
			&i.ScheduledFor,
			&i.ReadCount,
			&i.AcknowledgedCount,
			&i.PinOrder,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnreadUserNotifications = `-- name: ListUnreadUserNotifications :many
SELECT id, user_id, type, title, message, is_read, action_url, email_sent, created_at, category, priority, sender_id, entity_type, entity_id, action_label, image_url, metadata, expires_at FROM notifications
WHERE user_id = $1 AND is_read = false
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListUnreadUserNotificationsParams struct {
	UserID uuid.UUID `json:"user_id"`
	Limit  int32     `json:"limit"`
	Offset int32     `json:"offset"`
}

func (q *Queries) ListUnreadUserNotifications(ctx context.Context, arg ListUnreadUserNotificationsParams) ([]Notification, error) {
	rows, err := q.db.Query(ctx, listUnreadUserNotifications, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Notification{}
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Type,
			&i.Title,
			&i.Message,
			&i.IsRead,
			&i.ActionUrl,
			&i.EmailSent,
			&i.CreatedAt,
			&i.Category,
			&i.Priority,
			&i.SenderID,
			&i.EntityType,
			&i.EntityID,
			&i.ActionLabel,
			&i.ImageUrl,
			&i.Metadata,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserNotifications = `-- name: ListUserNotifications :many
SELECT id, user_id, type, title, message, is_read, action_url, email_sent, created_at, category, priority, sender_id, entity_type, entity_id, action_label, image_url, metadata, expires_at FROM notifications
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListUserNotificationsParams struct {
	UserID uuid.UUID `json:"user_id"`
	Limit  int32     `json:"limit"`
	Offset int32     `json:"offset"`
}

func (q *Queries) ListUserNotifications(ctx context.Context, arg ListUserNotificationsParams) ([]Notification, error) {
	rows, err := q.db.Query(ctx, listUserNotifications, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Notification{}
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Type,
			&i.Title,
			&i.Message,
			&i.IsRead,
			&i.ActionUrl,
			&i.EmailSent,
			&i.CreatedAt,
			&i.Category,
			&i.Priority,
			&i.SenderID,
			&i.EntityType,
			&i.EntityID,
			&i.ActionLabel,
			&i.ImageUrl,
			&i.Metadata,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserNotificationsByCategory = `-- name: ListUserNotificationsByCategory :many
SELECT id, user_id, type, title, message, is_read, action_url, email_sent, created_at, category, priority, sender_id, entity_type, entity_id, action_label, image_url, metadata, expires_at FROM notifications
WHERE user_id = $1 AND category = $2
ORDER BY created_at DESC
LIMIT $3 OFFSET $4
`

type ListUserNotificationsByCategoryParams struct {
	UserID   uuid.UUID `json:"user_id"`
	Category *string   `json:"category"`
	Limit    int32     `json:"limit"`
	Offset   int32     `json:"offset"`
}

func (q *Queries) ListUserNotificationsByCategory(ctx context.Context, arg ListUserNotificationsByCategoryParams) ([]Notification, error) {
	rows, err := q.db.Query(ctx, listUserNotificationsByCategory,
		arg.UserID,
		arg.Category,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Notification{}
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Type,
			&i.Title,
			&i.Message,
			&i.IsRead,
			&i.ActionUrl,
			&i.EmailSent,
			&i.CreatedAt,
			&i.Category,
			&i.Priority,
			&i.SenderID,
			&i.EntityType,
			&i.EntityID,
			&i.ActionLabel,
			&i.ImageUrl,
			&i.Metadata,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAllUserNotificationsAsRead = `-- name: MarkAllUserNotificationsAsRead :exec
UPDATE notifications
SET is_read = true
WHERE user_id = $1 AND is_read = false
`

func (q *Queries) MarkAllUserNotificationsAsRead(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, markAllUserNotificationsAsRead, userID)
	return err
}

const markNotificationAsRead = `-- name: MarkNotificationAsRead :one
UPDATE notifications
SET is_read = true
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, type, title, message, is_read, action_url, email_sent, created_at, category, priority, sender_id, entity_type, entity_id, action_label, image_url, metadata, expires_at
`

type MarkNotificationAsReadParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) MarkNotificationAsRead(ctx context.Context, arg MarkNotificationAsReadParams) (Notification, error) {
	row := q.db.QueryRow(ctx, markNotificationAsRead, arg.ID, arg.UserID)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.Title,
		&i.Message,
		&i.IsRead,
		&i.ActionUrl,
		&i.EmailSent,
		&i.CreatedAt,
		&i.Category,
		&i.Priority,
		&i.SenderID,
		&i.EntityType,
		&i.EntityID,
		&i.ActionLabel,
		&i.ImageUrl,
		&i.Metadata,
		&i.ExpiresAt,
	)
	return i, err
}

const updateAnnouncement = `-- name: UpdateAnnouncement :one
UPDATE announcements
SET
    title = $2,
    content = $3,
    is_pinned = $4,
    target_level = $5,
    target_audience = $6,
    expires_at = $7
WHERE id = $1
RETURNING id, title, content, is_pinned, target_level, target_audience, expires_at, created_by, created_at, summary, priority, category, target_levels, target_departments, attachments, requires_acknowledgment, status, scheduled_for, read_count, acknowledged_count, pin_order, updated_at
`

type UpdateAnnouncementParams struct {
	ID             uuid.UUID          `json:"id"`
	Title          string             `json:"title"`
	Content        string             `json:"content"`
	IsPinned       bool               `json:"is_pinned"`
	TargetLevel    *int32             `json:"target_level"`
	TargetAudience []byte             `json:"target_audience"`
	ExpiresAt      pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) UpdateAnnouncement(ctx context.Context, arg UpdateAnnouncementParams) (Announcement, error) {
	row := q.db.QueryRow(ctx, updateAnnouncement,
		arg.ID,
		arg.Title,
		arg.Content,
		arg.IsPinned,
		arg.TargetLevel,
		arg.TargetAudience,
		arg.ExpiresAt,
	)
	var i Announcement
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Content,
		&i.IsPinned,
		&i.TargetLevel,
		&i.TargetAudience,
		&i.ExpiresAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.Summary,
		&i.Priority,
		&i.Category,
		&i.TargetLevels,
		&i.TargetDepartments,
		&i.Attachments,
		&i.RequiresAcknowledgment,
		&i.Status,
		&i.ScheduledFor,
		&i.ReadCount,
		&i.AcknowledgedCount,
		&i.PinOrder,
		&i.UpdatedAt,
	)
	return i, err
}
