// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: course_registrations.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createCourseRegistration = `-- name: CreateCourseRegistration :one
INSERT INTO course_registrations (
    student_id, session_id, semester_id, total_units, status
) VALUES (
    $1, $2, $3, $4, $5
) RETURNING id, student_id, session_id, semester_id, total_units, status, approved_by, approved_at, created_at
`

type CreateCourseRegistrationParams struct {
	StudentID  uuid.UUID `json:"student_id"`
	SessionID  uuid.UUID `json:"session_id"`
	SemesterID uuid.UUID `json:"semester_id"`
	TotalUnits int32     `json:"total_units"`
	Status     string    `json:"status"`
}

func (q *Queries) CreateCourseRegistration(ctx context.Context, arg CreateCourseRegistrationParams) (CourseRegistration, error) {
	row := q.db.QueryRow(ctx, createCourseRegistration,
		arg.StudentID,
		arg.SessionID,
		arg.SemesterID,
		arg.TotalUnits,
		arg.Status,
	)
	var i CourseRegistration
	err := row.Scan(
		&i.ID,
		&i.StudentID,
		&i.SessionID,
		&i.SemesterID,
		&i.TotalUnits,
		&i.Status,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createRegisteredCourse = `-- name: CreateRegisteredCourse :one
INSERT INTO registered_courses (
    registration_id, course_id, status, is_carryover, previous_attempt_id
) VALUES (
    $1, $2, $3, $4, $5
) RETURNING id, registration_id, course_id, status, is_carryover, previous_attempt_id, created_at
`

type CreateRegisteredCourseParams struct {
	RegistrationID    uuid.UUID   `json:"registration_id"`
	CourseID          uuid.UUID   `json:"course_id"`
	Status            string      `json:"status"`
	IsCarryover       bool        `json:"is_carryover"`
	PreviousAttemptID pgtype.UUID `json:"previous_attempt_id"`
}

func (q *Queries) CreateRegisteredCourse(ctx context.Context, arg CreateRegisteredCourseParams) (RegisteredCourse, error) {
	row := q.db.QueryRow(ctx, createRegisteredCourse,
		arg.RegistrationID,
		arg.CourseID,
		arg.Status,
		arg.IsCarryover,
		arg.PreviousAttemptID,
	)
	var i RegisteredCourse
	err := row.Scan(
		&i.ID,
		&i.RegistrationID,
		&i.CourseID,
		&i.Status,
		&i.IsCarryover,
		&i.PreviousAttemptID,
		&i.CreatedAt,
	)
	return i, err
}

const deleteRegisteredCourse = `-- name: DeleteRegisteredCourse :exec
DELETE FROM registered_courses
WHERE id = $1
`

func (q *Queries) DeleteRegisteredCourse(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteRegisteredCourse, id)
	return err
}

const getCourseRegistration = `-- name: GetCourseRegistration :one
SELECT id, student_id, session_id, semester_id, total_units, status, approved_by, approved_at, created_at FROM course_registrations
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetCourseRegistration(ctx context.Context, id uuid.UUID) (CourseRegistration, error) {
	row := q.db.QueryRow(ctx, getCourseRegistration, id)
	var i CourseRegistration
	err := row.Scan(
		&i.ID,
		&i.StudentID,
		&i.SessionID,
		&i.SemesterID,
		&i.TotalUnits,
		&i.Status,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getRegisteredCourse = `-- name: GetRegisteredCourse :one
SELECT id, registration_id, course_id, status, is_carryover, previous_attempt_id, created_at FROM registered_courses
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetRegisteredCourse(ctx context.Context, id uuid.UUID) (RegisteredCourse, error) {
	row := q.db.QueryRow(ctx, getRegisteredCourse, id)
	var i RegisteredCourse
	err := row.Scan(
		&i.ID,
		&i.RegistrationID,
		&i.CourseID,
		&i.Status,
		&i.IsCarryover,
		&i.PreviousAttemptID,
		&i.CreatedAt,
	)
	return i, err
}

const listRegisteredCoursesByRegistration = `-- name: ListRegisteredCoursesByRegistration :many
SELECT id, registration_id, course_id, status, is_carryover, previous_attempt_id, created_at FROM registered_courses
WHERE registration_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListRegisteredCoursesByRegistration(ctx context.Context, registrationID uuid.UUID) ([]RegisteredCourse, error) {
	rows, err := q.db.Query(ctx, listRegisteredCoursesByRegistration, registrationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RegisteredCourse{}
	for rows.Next() {
		var i RegisteredCourse
		if err := rows.Scan(
			&i.ID,
			&i.RegistrationID,
			&i.CourseID,
			&i.Status,
			&i.IsCarryover,
			&i.PreviousAttemptID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStudentCourseRegistrations = `-- name: ListStudentCourseRegistrations :many
SELECT id, student_id, session_id, semester_id, total_units, status, approved_by, approved_at, created_at FROM course_registrations
WHERE student_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListStudentCourseRegistrations(ctx context.Context, studentID uuid.UUID) ([]CourseRegistration, error) {
	rows, err := q.db.Query(ctx, listStudentCourseRegistrations, studentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CourseRegistration{}
	for rows.Next() {
		var i CourseRegistration
		if err := rows.Scan(
			&i.ID,
			&i.StudentID,
			&i.SessionID,
			&i.SemesterID,
			&i.TotalUnits,
			&i.Status,
			&i.ApprovedBy,
			&i.ApprovedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCourseRegistration = `-- name: UpdateCourseRegistration :one
UPDATE course_registrations
SET
    total_units = $2,
    status = $3,
    approved_by = $4,
    approved_at = $5
WHERE id = $1
RETURNING id, student_id, session_id, semester_id, total_units, status, approved_by, approved_at, created_at
`

type UpdateCourseRegistrationParams struct {
	ID         uuid.UUID          `json:"id"`
	TotalUnits int32              `json:"total_units"`
	Status     string             `json:"status"`
	ApprovedBy pgtype.UUID        `json:"approved_by"`
	ApprovedAt pgtype.Timestamptz `json:"approved_at"`
}

func (q *Queries) UpdateCourseRegistration(ctx context.Context, arg UpdateCourseRegistrationParams) (CourseRegistration, error) {
	row := q.db.QueryRow(ctx, updateCourseRegistration,
		arg.ID,
		arg.TotalUnits,
		arg.Status,
		arg.ApprovedBy,
		arg.ApprovedAt,
	)
	var i CourseRegistration
	err := row.Scan(
		&i.ID,
		&i.StudentID,
		&i.SessionID,
		&i.SemesterID,
		&i.TotalUnits,
		&i.Status,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.CreatedAt,
	)
	return i, err
}

const updateRegisteredCourse = `-- name: UpdateRegisteredCourse :one
UPDATE registered_courses
SET
    status = $2,
    is_carryover = $3,
    previous_attempt_id = $4
WHERE id = $1
RETURNING id, registration_id, course_id, status, is_carryover, previous_attempt_id, created_at
`

type UpdateRegisteredCourseParams struct {
	ID                uuid.UUID   `json:"id"`
	Status            string      `json:"status"`
	IsCarryover       bool        `json:"is_carryover"`
	PreviousAttemptID pgtype.UUID `json:"previous_attempt_id"`
}

func (q *Queries) UpdateRegisteredCourse(ctx context.Context, arg UpdateRegisteredCourseParams) (RegisteredCourse, error) {
	row := q.db.QueryRow(ctx, updateRegisteredCourse,
		arg.ID,
		arg.Status,
		arg.IsCarryover,
		arg.PreviousAttemptID,
	)
	var i RegisteredCourse
	err := row.Scan(
		&i.ID,
		&i.RegistrationID,
		&i.CourseID,
		&i.Status,
		&i.IsCarryover,
		&i.PreviousAttemptID,
		&i.CreatedAt,
	)
	return i, err
}
