// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: course_subcategories.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createCourseSubcategory = `-- name: CreateCourseSubcategory :one

INSERT INTO course_subcategories (
    course_id, name, weight_percentage
) VALUES (
    $1, $2, $3
) RETURNING id, course_id, name, weight_percentage, is_active, created_at
`

type CreateCourseSubcategoryParams struct {
	CourseID         uuid.UUID `json:"course_id"`
	Name             string    `json:"name"`
	WeightPercentage int32     `json:"weight_percentage"`
}

// ==================== COURSE SUBCATEGORIES ====================
func (q *Queries) CreateCourseSubcategory(ctx context.Context, arg CreateCourseSubcategoryParams) (CourseSubcategory, error) {
	row := q.db.QueryRow(ctx, createCourseSubcategory, arg.CourseID, arg.Name, arg.WeightPercentage)
	var i CourseSubcategory
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.Name,
		&i.WeightPercentage,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const deleteCourseSubcategory = `-- name: DeleteCourseSubcategory :exec
UPDATE course_subcategories SET is_active = false WHERE id = $1
`

func (q *Queries) DeleteCourseSubcategory(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteCourseSubcategory, id)
	return err
}

const getCourseSubcategory = `-- name: GetCourseSubcategory :one
SELECT id, course_id, name, weight_percentage, is_active, created_at FROM course_subcategories
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetCourseSubcategory(ctx context.Context, id uuid.UUID) (CourseSubcategory, error) {
	row := q.db.QueryRow(ctx, getCourseSubcategory, id)
	var i CourseSubcategory
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.Name,
		&i.WeightPercentage,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const listCourseSubcategories = `-- name: ListCourseSubcategories :many
SELECT id, course_id, name, weight_percentage, is_active, created_at FROM course_subcategories
WHERE course_id = $1 AND is_active = true
ORDER BY name
`

func (q *Queries) ListCourseSubcategories(ctx context.Context, courseID uuid.UUID) ([]CourseSubcategory, error) {
	rows, err := q.db.Query(ctx, listCourseSubcategories, courseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CourseSubcategory{}
	for rows.Next() {
		var i CourseSubcategory
		if err := rows.Scan(
			&i.ID,
			&i.CourseID,
			&i.Name,
			&i.WeightPercentage,
			&i.IsActive,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCourseSubcategory = `-- name: UpdateCourseSubcategory :one
UPDATE course_subcategories
SET name = $2, weight_percentage = $3, is_active = $4
WHERE id = $1
RETURNING id, course_id, name, weight_percentage, is_active, created_at
`

type UpdateCourseSubcategoryParams struct {
	ID               uuid.UUID `json:"id"`
	Name             string    `json:"name"`
	WeightPercentage int32     `json:"weight_percentage"`
	IsActive         bool      `json:"is_active"`
}

func (q *Queries) UpdateCourseSubcategory(ctx context.Context, arg UpdateCourseSubcategoryParams) (CourseSubcategory, error) {
	row := q.db.QueryRow(ctx, updateCourseSubcategory,
		arg.ID,
		arg.Name,
		arg.WeightPercentage,
		arg.IsActive,
	)
	var i CourseSubcategory
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.Name,
		&i.WeightPercentage,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}
