// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: donations.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const getDonation = `-- name: GetDonation :one
SELECT id, donor_id, channel, amount, currency, payment_id, receipt_url, message, is_anonymous, recognized_tier, status, created_at, updated_at, paystack_reference FROM alumni_donations WHERE id = $1 LIMIT 1
`

func (q *Queries) GetDonation(ctx context.Context, id uuid.UUID) (AlumniDonation, error) {
	row := q.db.QueryRow(ctx, getDonation, id)
	var i AlumniDonation
	err := row.Scan(
		&i.ID,
		&i.DonorID,
		&i.Channel,
		&i.Amount,
		&i.Currency,
		&i.PaymentID,
		&i.ReceiptUrl,
		&i.Message,
		&i.IsAnonymous,
		&i.RecognizedTier,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PaystackReference,
	)
	return i, err
}

const getDonorTotal = `-- name: GetDonorTotal :one
SELECT COALESCE(SUM(amount), 0) as total
FROM alumni_donations
WHERE donor_id = $1 AND status = 'completed'
`

func (q *Queries) GetDonorTotal(ctx context.Context, donorID uuid.UUID) (interface{}, error) {
	row := q.db.QueryRow(ctx, getDonorTotal, donorID)
	var total interface{}
	err := row.Scan(&total)
	return total, err
}

const updateDonationStatus = `-- name: UpdateDonationStatus :exec
UPDATE alumni_donations SET status = $2 WHERE id = $1
`

type UpdateDonationStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) UpdateDonationStatus(ctx context.Context, arg UpdateDonationStatusParams) error {
	_, err := q.db.Exec(ctx, updateDonationStatus, arg.ID, arg.Status)
	return err
}
