// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: manuals.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

const checkManualPurchased = `-- name: CheckManualPurchased :one
SELECT EXISTS(
    SELECT 1 FROM manual_purchases
    WHERE student_id = $1 AND manual_id = $2
) AS is_purchased
`

type CheckManualPurchasedParams struct {
	StudentID uuid.UUID `json:"student_id"`
	ManualID  uuid.UUID `json:"manual_id"`
}

func (q *Queries) CheckManualPurchased(ctx context.Context, arg CheckManualPurchasedParams) (bool, error) {
	row := q.db.QueryRow(ctx, checkManualPurchased, arg.StudentID, arg.ManualID)
	var is_purchased bool
	err := row.Scan(&is_purchased)
	return is_purchased, err
}

const checkPracticalEnrolled = `-- name: CheckPracticalEnrolled :one
SELECT EXISTS(
    SELECT 1 FROM practical_enrollments
    WHERE student_id = $1 AND course_id = $2 AND session_id = $3
) AS is_enrolled
`

type CheckPracticalEnrolledParams struct {
	StudentID uuid.UUID `json:"student_id"`
	CourseID  uuid.UUID `json:"course_id"`
	SessionID uuid.UUID `json:"session_id"`
}

func (q *Queries) CheckPracticalEnrolled(ctx context.Context, arg CheckPracticalEnrolledParams) (bool, error) {
	row := q.db.QueryRow(ctx, checkPracticalEnrolled, arg.StudentID, arg.CourseID, arg.SessionID)
	var is_enrolled bool
	err := row.Scan(&is_enrolled)
	return is_enrolled, err
}

const createManual = `-- name: CreateManual :one

INSERT INTO manuals (
    title, description, level, price, file_url, cover_image_url, course_id, session_id, created_by
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
) RETURNING id, title, description, level, price, file_url, cover_image_url, course_id, session_id, is_active, created_by, created_at, updated_at
`

type CreateManualParams struct {
	Title         string          `json:"title"`
	Description   *string         `json:"description"`
	Level         int32           `json:"level"`
	Price         decimal.Decimal `json:"price"`
	FileUrl       *string         `json:"file_url"`
	CoverImageUrl *string         `json:"cover_image_url"`
	CourseID      pgtype.UUID     `json:"course_id"`
	SessionID     pgtype.UUID     `json:"session_id"`
	CreatedBy     uuid.UUID       `json:"created_by"`
}

// ==================== MANUALS ====================
func (q *Queries) CreateManual(ctx context.Context, arg CreateManualParams) (Manual, error) {
	row := q.db.QueryRow(ctx, createManual,
		arg.Title,
		arg.Description,
		arg.Level,
		arg.Price,
		arg.FileUrl,
		arg.CoverImageUrl,
		arg.CourseID,
		arg.SessionID,
		arg.CreatedBy,
	)
	var i Manual
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Level,
		&i.Price,
		&i.FileUrl,
		&i.CoverImageUrl,
		&i.CourseID,
		&i.SessionID,
		&i.IsActive,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createManualPurchase = `-- name: CreateManualPurchase :one

INSERT INTO manual_purchases (
    student_id, manual_id, payment_id, qr_code_data, qr_code_url
) VALUES (
    $1, $2, $3, $4, $5
) RETURNING id, student_id, manual_id, payment_id, qr_code_data, qr_code_url, is_collected, collected_at, purchased_at
`

type CreateManualPurchaseParams struct {
	StudentID  uuid.UUID   `json:"student_id"`
	ManualID   uuid.UUID   `json:"manual_id"`
	PaymentID  pgtype.UUID `json:"payment_id"`
	QrCodeData *string     `json:"qr_code_data"`
	QrCodeUrl  *string     `json:"qr_code_url"`
}

// ==================== MANUAL PURCHASES ====================
func (q *Queries) CreateManualPurchase(ctx context.Context, arg CreateManualPurchaseParams) (ManualPurchase, error) {
	row := q.db.QueryRow(ctx, createManualPurchase,
		arg.StudentID,
		arg.ManualID,
		arg.PaymentID,
		arg.QrCodeData,
		arg.QrCodeUrl,
	)
	var i ManualPurchase
	err := row.Scan(
		&i.ID,
		&i.StudentID,
		&i.ManualID,
		&i.PaymentID,
		&i.QrCodeData,
		&i.QrCodeUrl,
		&i.IsCollected,
		&i.CollectedAt,
		&i.PurchasedAt,
	)
	return i, err
}

const createPracticalEnrollment = `-- name: CreatePracticalEnrollment :one

INSERT INTO practical_enrollments (
    student_id, course_id, manual_purchase_id, session_id, enrolled_via
) VALUES (
    $1, $2, $3, $4, $5
) RETURNING id, student_id, course_id, manual_purchase_id, session_id, enrolled_via, enrolled_at
`

type CreatePracticalEnrollmentParams struct {
	StudentID        uuid.UUID   `json:"student_id"`
	CourseID         uuid.UUID   `json:"course_id"`
	ManualPurchaseID pgtype.UUID `json:"manual_purchase_id"`
	SessionID        uuid.UUID   `json:"session_id"`
	EnrolledVia      string      `json:"enrolled_via"`
}

// ==================== PRACTICAL ENROLLMENTS ====================
func (q *Queries) CreatePracticalEnrollment(ctx context.Context, arg CreatePracticalEnrollmentParams) (PracticalEnrollment, error) {
	row := q.db.QueryRow(ctx, createPracticalEnrollment,
		arg.StudentID,
		arg.CourseID,
		arg.ManualPurchaseID,
		arg.SessionID,
		arg.EnrolledVia,
	)
	var i PracticalEnrollment
	err := row.Scan(
		&i.ID,
		&i.StudentID,
		&i.CourseID,
		&i.ManualPurchaseID,
		&i.SessionID,
		&i.EnrolledVia,
		&i.EnrolledAt,
	)
	return i, err
}

const createPrintQueueItem = `-- name: CreatePrintQueueItem :one

INSERT INTO manual_print_queue (
    purchase_id, student_id, manual_id
) VALUES (
    $1, $2, $3
) RETURNING id, purchase_id, student_id, manual_id, status, queued_at, printed_at, collected_at, processed_by
`

type CreatePrintQueueItemParams struct {
	PurchaseID uuid.UUID `json:"purchase_id"`
	StudentID  uuid.UUID `json:"student_id"`
	ManualID   uuid.UUID `json:"manual_id"`
}

// ==================== MANUAL PRINT QUEUE ====================
func (q *Queries) CreatePrintQueueItem(ctx context.Context, arg CreatePrintQueueItemParams) (ManualPrintQueue, error) {
	row := q.db.QueryRow(ctx, createPrintQueueItem, arg.PurchaseID, arg.StudentID, arg.ManualID)
	var i ManualPrintQueue
	err := row.Scan(
		&i.ID,
		&i.PurchaseID,
		&i.StudentID,
		&i.ManualID,
		&i.Status,
		&i.QueuedAt,
		&i.PrintedAt,
		&i.CollectedAt,
		&i.ProcessedBy,
	)
	return i, err
}

const deleteManual = `-- name: DeleteManual :exec
UPDATE manuals SET is_active = false, updated_at = NOW() WHERE id = $1
`

func (q *Queries) DeleteManual(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteManual, id)
	return err
}

const getManual = `-- name: GetManual :one
SELECT id, title, description, level, price, file_url, cover_image_url, course_id, session_id, is_active, created_by, created_at, updated_at FROM manuals
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetManual(ctx context.Context, id uuid.UUID) (Manual, error) {
	row := q.db.QueryRow(ctx, getManual, id)
	var i Manual
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Level,
		&i.Price,
		&i.FileUrl,
		&i.CoverImageUrl,
		&i.CourseID,
		&i.SessionID,
		&i.IsActive,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getManualPurchase = `-- name: GetManualPurchase :one
SELECT id, student_id, manual_id, payment_id, qr_code_data, qr_code_url, is_collected, collected_at, purchased_at FROM manual_purchases
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetManualPurchase(ctx context.Context, id uuid.UUID) (ManualPurchase, error) {
	row := q.db.QueryRow(ctx, getManualPurchase, id)
	var i ManualPurchase
	err := row.Scan(
		&i.ID,
		&i.StudentID,
		&i.ManualID,
		&i.PaymentID,
		&i.QrCodeData,
		&i.QrCodeUrl,
		&i.IsCollected,
		&i.CollectedAt,
		&i.PurchasedAt,
	)
	return i, err
}

const listManualPurchasesByManual = `-- name: ListManualPurchasesByManual :many
SELECT mp.id, mp.student_id, mp.manual_id, mp.payment_id, mp.qr_code_data, mp.qr_code_url, mp.is_collected, mp.collected_at, mp.purchased_at, s.matric_number, u.full_name
FROM manual_purchases mp
JOIN students s ON mp.student_id = s.id
JOIN users u ON s.user_id = u.id
WHERE mp.manual_id = $1
ORDER BY mp.purchased_at DESC
LIMIT $2 OFFSET $3
`

type ListManualPurchasesByManualParams struct {
	ManualID uuid.UUID `json:"manual_id"`
	Limit    int32     `json:"limit"`
	Offset   int32     `json:"offset"`
}

type ListManualPurchasesByManualRow struct {
	ID           uuid.UUID          `json:"id"`
	StudentID    uuid.UUID          `json:"student_id"`
	ManualID     uuid.UUID          `json:"manual_id"`
	PaymentID    pgtype.UUID        `json:"payment_id"`
	QrCodeData   *string            `json:"qr_code_data"`
	QrCodeUrl    *string            `json:"qr_code_url"`
	IsCollected  bool               `json:"is_collected"`
	CollectedAt  pgtype.Timestamptz `json:"collected_at"`
	PurchasedAt  pgtype.Timestamptz `json:"purchased_at"`
	MatricNumber string             `json:"matric_number"`
	FullName     string             `json:"full_name"`
}

func (q *Queries) ListManualPurchasesByManual(ctx context.Context, arg ListManualPurchasesByManualParams) ([]ListManualPurchasesByManualRow, error) {
	rows, err := q.db.Query(ctx, listManualPurchasesByManual, arg.ManualID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListManualPurchasesByManualRow{}
	for rows.Next() {
		var i ListManualPurchasesByManualRow
		if err := rows.Scan(
			&i.ID,
			&i.StudentID,
			&i.ManualID,
			&i.PaymentID,
			&i.QrCodeData,
			&i.QrCodeUrl,
			&i.IsCollected,
			&i.CollectedAt,
			&i.PurchasedAt,
			&i.MatricNumber,
			&i.FullName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listManuals = `-- name: ListManuals :many
SELECT id, title, description, level, price, file_url, cover_image_url, course_id, session_id, is_active, created_by, created_at, updated_at FROM manuals
WHERE is_active = true
ORDER BY level, title
LIMIT $1 OFFSET $2
`

type ListManualsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListManuals(ctx context.Context, arg ListManualsParams) ([]Manual, error) {
	rows, err := q.db.Query(ctx, listManuals, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Manual{}
	for rows.Next() {
		var i Manual
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Level,
			&i.Price,
			&i.FileUrl,
			&i.CoverImageUrl,
			&i.CourseID,
			&i.SessionID,
			&i.IsActive,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listManualsByLevel = `-- name: ListManualsByLevel :many
SELECT id, title, description, level, price, file_url, cover_image_url, course_id, session_id, is_active, created_by, created_at, updated_at FROM manuals
WHERE is_active = true AND level = $1
ORDER BY title
`

func (q *Queries) ListManualsByLevel(ctx context.Context, level int32) ([]Manual, error) {
	rows, err := q.db.Query(ctx, listManualsByLevel, level)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Manual{}
	for rows.Next() {
		var i Manual
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Level,
			&i.Price,
			&i.FileUrl,
			&i.CoverImageUrl,
			&i.CourseID,
			&i.SessionID,
			&i.IsActive,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPrintQueue = `-- name: ListPrintQueue :many
SELECT mpq.id, mpq.purchase_id, mpq.student_id, mpq.manual_id, mpq.status, mpq.queued_at, mpq.printed_at, mpq.collected_at, mpq.processed_by, m.title AS manual_title, u.full_name AS student_name, s.matric_number
FROM manual_print_queue mpq
JOIN manuals m ON mpq.manual_id = m.id
JOIN students s ON mpq.student_id = s.id
JOIN users u ON s.user_id = u.id
WHERE mpq.status = COALESCE($1, mpq.status)
ORDER BY mpq.queued_at
LIMIT $2 OFFSET $3
`

type ListPrintQueueParams struct {
	Status string `json:"status"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

type ListPrintQueueRow struct {
	ID           uuid.UUID          `json:"id"`
	PurchaseID   uuid.UUID          `json:"purchase_id"`
	StudentID    uuid.UUID          `json:"student_id"`
	ManualID     uuid.UUID          `json:"manual_id"`
	Status       string             `json:"status"`
	QueuedAt     pgtype.Timestamptz `json:"queued_at"`
	PrintedAt    pgtype.Timestamptz `json:"printed_at"`
	CollectedAt  pgtype.Timestamptz `json:"collected_at"`
	ProcessedBy  pgtype.UUID        `json:"processed_by"`
	ManualTitle  string             `json:"manual_title"`
	StudentName  string             `json:"student_name"`
	MatricNumber string             `json:"matric_number"`
}

func (q *Queries) ListPrintQueue(ctx context.Context, arg ListPrintQueueParams) ([]ListPrintQueueRow, error) {
	rows, err := q.db.Query(ctx, listPrintQueue, arg.Status, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPrintQueueRow{}
	for rows.Next() {
		var i ListPrintQueueRow
		if err := rows.Scan(
			&i.ID,
			&i.PurchaseID,
			&i.StudentID,
			&i.ManualID,
			&i.Status,
			&i.QueuedAt,
			&i.PrintedAt,
			&i.CollectedAt,
			&i.ProcessedBy,
			&i.ManualTitle,
			&i.StudentName,
			&i.MatricNumber,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStudentManualPurchases = `-- name: ListStudentManualPurchases :many
SELECT mp.id, mp.student_id, mp.manual_id, mp.payment_id, mp.qr_code_data, mp.qr_code_url, mp.is_collected, mp.collected_at, mp.purchased_at, m.title, m.level, m.price
FROM manual_purchases mp
JOIN manuals m ON mp.manual_id = m.id
WHERE mp.student_id = $1
ORDER BY mp.purchased_at DESC
`

type ListStudentManualPurchasesRow struct {
	ID          uuid.UUID          `json:"id"`
	StudentID   uuid.UUID          `json:"student_id"`
	ManualID    uuid.UUID          `json:"manual_id"`
	PaymentID   pgtype.UUID        `json:"payment_id"`
	QrCodeData  *string            `json:"qr_code_data"`
	QrCodeUrl   *string            `json:"qr_code_url"`
	IsCollected bool               `json:"is_collected"`
	CollectedAt pgtype.Timestamptz `json:"collected_at"`
	PurchasedAt pgtype.Timestamptz `json:"purchased_at"`
	Title       string             `json:"title"`
	Level       int32              `json:"level"`
	Price       decimal.Decimal    `json:"price"`
}

func (q *Queries) ListStudentManualPurchases(ctx context.Context, studentID uuid.UUID) ([]ListStudentManualPurchasesRow, error) {
	rows, err := q.db.Query(ctx, listStudentManualPurchases, studentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListStudentManualPurchasesRow{}
	for rows.Next() {
		var i ListStudentManualPurchasesRow
		if err := rows.Scan(
			&i.ID,
			&i.StudentID,
			&i.ManualID,
			&i.PaymentID,
			&i.QrCodeData,
			&i.QrCodeUrl,
			&i.IsCollected,
			&i.CollectedAt,
			&i.PurchasedAt,
			&i.Title,
			&i.Level,
			&i.Price,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStudentPracticalEnrollments = `-- name: ListStudentPracticalEnrollments :many
SELECT pe.id, pe.student_id, pe.course_id, pe.manual_purchase_id, pe.session_id, pe.enrolled_via, pe.enrolled_at, c.code AS course_code, c.title AS course_title
FROM practical_enrollments pe
JOIN courses c ON pe.course_id = c.id
WHERE pe.student_id = $1
ORDER BY pe.enrolled_at DESC
`

type ListStudentPracticalEnrollmentsRow struct {
	ID               uuid.UUID          `json:"id"`
	StudentID        uuid.UUID          `json:"student_id"`
	CourseID         uuid.UUID          `json:"course_id"`
	ManualPurchaseID pgtype.UUID        `json:"manual_purchase_id"`
	SessionID        uuid.UUID          `json:"session_id"`
	EnrolledVia      string             `json:"enrolled_via"`
	EnrolledAt       pgtype.Timestamptz `json:"enrolled_at"`
	CourseCode       string             `json:"course_code"`
	CourseTitle      string             `json:"course_title"`
}

func (q *Queries) ListStudentPracticalEnrollments(ctx context.Context, studentID uuid.UUID) ([]ListStudentPracticalEnrollmentsRow, error) {
	rows, err := q.db.Query(ctx, listStudentPracticalEnrollments, studentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListStudentPracticalEnrollmentsRow{}
	for rows.Next() {
		var i ListStudentPracticalEnrollmentsRow
		if err := rows.Scan(
			&i.ID,
			&i.StudentID,
			&i.CourseID,
			&i.ManualPurchaseID,
			&i.SessionID,
			&i.EnrolledVia,
			&i.EnrolledAt,
			&i.CourseCode,
			&i.CourseTitle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markManualCollected = `-- name: MarkManualCollected :one
UPDATE manual_purchases
SET is_collected = true, collected_at = NOW()
WHERE id = $1
RETURNING id, student_id, manual_id, payment_id, qr_code_data, qr_code_url, is_collected, collected_at, purchased_at
`

func (q *Queries) MarkManualCollected(ctx context.Context, id uuid.UUID) (ManualPurchase, error) {
	row := q.db.QueryRow(ctx, markManualCollected, id)
	var i ManualPurchase
	err := row.Scan(
		&i.ID,
		&i.StudentID,
		&i.ManualID,
		&i.PaymentID,
		&i.QrCodeData,
		&i.QrCodeUrl,
		&i.IsCollected,
		&i.CollectedAt,
		&i.PurchasedAt,
	)
	return i, err
}

const updateManual = `-- name: UpdateManual :one
UPDATE manuals
SET title = $2, description = $3, level = $4, price = $5,
    file_url = $6, cover_image_url = $7, is_active = $8,
    updated_at = NOW()
WHERE id = $1
RETURNING id, title, description, level, price, file_url, cover_image_url, course_id, session_id, is_active, created_by, created_at, updated_at
`

type UpdateManualParams struct {
	ID            uuid.UUID       `json:"id"`
	Title         string          `json:"title"`
	Description   *string         `json:"description"`
	Level         int32           `json:"level"`
	Price         decimal.Decimal `json:"price"`
	FileUrl       *string         `json:"file_url"`
	CoverImageUrl *string         `json:"cover_image_url"`
	IsActive      bool            `json:"is_active"`
}

func (q *Queries) UpdateManual(ctx context.Context, arg UpdateManualParams) (Manual, error) {
	row := q.db.QueryRow(ctx, updateManual,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.Level,
		arg.Price,
		arg.FileUrl,
		arg.CoverImageUrl,
		arg.IsActive,
	)
	var i Manual
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Level,
		&i.Price,
		&i.FileUrl,
		&i.CoverImageUrl,
		&i.CourseID,
		&i.SessionID,
		&i.IsActive,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePrintQueueStatus = `-- name: UpdatePrintQueueStatus :one
UPDATE manual_print_queue
SET status = $2, processed_by = $3,
    printed_at = CASE WHEN $2 = 'ready' THEN NOW() ELSE printed_at END,
    collected_at = CASE WHEN $2 = 'collected' THEN NOW() ELSE collected_at END
WHERE id = $1
RETURNING id, purchase_id, student_id, manual_id, status, queued_at, printed_at, collected_at, processed_by
`

type UpdatePrintQueueStatusParams struct {
	ID          uuid.UUID   `json:"id"`
	Status      string      `json:"status"`
	ProcessedBy pgtype.UUID `json:"processed_by"`
}

func (q *Queries) UpdatePrintQueueStatus(ctx context.Context, arg UpdatePrintQueueStatusParams) (ManualPrintQueue, error) {
	row := q.db.QueryRow(ctx, updatePrintQueueStatus, arg.ID, arg.Status, arg.ProcessedBy)
	var i ManualPrintQueue
	err := row.Scan(
		&i.ID,
		&i.PurchaseID,
		&i.StudentID,
		&i.ManualID,
		&i.Status,
		&i.QueuedAt,
		&i.PrintedAt,
		&i.CollectedAt,
		&i.ProcessedBy,
	)
	return i, err
}
