// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql/driver"
	"encoding/json"
	"fmt"
	"net/netip"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

type AcademicStanding string

const (
	AcademicStandingGoodStanding AcademicStanding = "good_standing"
	AcademicStandingProbation    AcademicStanding = "probation"
	AcademicStandingSuspension   AcademicStanding = "suspension"
)

func (e *AcademicStanding) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AcademicStanding(s)
	case string:
		*e = AcademicStanding(s)
	default:
		return fmt.Errorf("unsupported scan type for AcademicStanding: %T", src)
	}
	return nil
}

type NullAcademicStanding struct {
	AcademicStanding AcademicStanding `json:"academic_standing"`
	Valid            bool             `json:"valid"` // Valid is true if AcademicStanding is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAcademicStanding) Scan(value interface{}) error {
	if value == nil {
		ns.AcademicStanding, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AcademicStanding.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAcademicStanding) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AcademicStanding), nil
}

type AlumniVerificationStatus string

const (
	AlumniVerificationStatusPending  AlumniVerificationStatus = "pending"
	AlumniVerificationStatusVerified AlumniVerificationStatus = "verified"
	AlumniVerificationStatusRejected AlumniVerificationStatus = "rejected"
)

func (e *AlumniVerificationStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AlumniVerificationStatus(s)
	case string:
		*e = AlumniVerificationStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for AlumniVerificationStatus: %T", src)
	}
	return nil
}

type NullAlumniVerificationStatus struct {
	AlumniVerificationStatus AlumniVerificationStatus `json:"alumni_verification_status"`
	Valid                    bool                     `json:"valid"` // Valid is true if AlumniVerificationStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAlumniVerificationStatus) Scan(value interface{}) error {
	if value == nil {
		ns.AlumniVerificationStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AlumniVerificationStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAlumniVerificationStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AlumniVerificationStatus), nil
}

type ApplicationStatus string

const (
	ApplicationStatusPending     ApplicationStatus = "pending"
	ApplicationStatusReviewed    ApplicationStatus = "reviewed"
	ApplicationStatusShortlisted ApplicationStatus = "shortlisted"
	ApplicationStatusAccepted    ApplicationStatus = "accepted"
	ApplicationStatusRejected    ApplicationStatus = "rejected"
)

func (e *ApplicationStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ApplicationStatus(s)
	case string:
		*e = ApplicationStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ApplicationStatus: %T", src)
	}
	return nil
}

type NullApplicationStatus struct {
	ApplicationStatus ApplicationStatus `json:"application_status"`
	Valid             bool              `json:"valid"` // Valid is true if ApplicationStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullApplicationStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ApplicationStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ApplicationStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullApplicationStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ApplicationStatus), nil
}

type BackupStatus string

const (
	BackupStatusPending    BackupStatus = "pending"
	BackupStatusInProgress BackupStatus = "in_progress"
	BackupStatusCompleted  BackupStatus = "completed"
	BackupStatusFailed     BackupStatus = "failed"
)

func (e *BackupStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = BackupStatus(s)
	case string:
		*e = BackupStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for BackupStatus: %T", src)
	}
	return nil
}

type NullBackupStatus struct {
	BackupStatus BackupStatus `json:"backup_status"`
	Valid        bool         `json:"valid"` // Valid is true if BackupStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullBackupStatus) Scan(value interface{}) error {
	if value == nil {
		ns.BackupStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.BackupStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullBackupStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.BackupStatus), nil
}

type ChangeRequestStatus string

const (
	ChangeRequestStatusPending     ChangeRequestStatus = "pending"
	ChangeRequestStatusUnderReview ChangeRequestStatus = "under_review"
	ChangeRequestStatusApproved    ChangeRequestStatus = "approved"
	ChangeRequestStatusRejected    ChangeRequestStatus = "rejected"
	ChangeRequestStatusAppealed    ChangeRequestStatus = "appealed"
	ChangeRequestStatusClosed      ChangeRequestStatus = "closed"
)

func (e *ChangeRequestStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ChangeRequestStatus(s)
	case string:
		*e = ChangeRequestStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ChangeRequestStatus: %T", src)
	}
	return nil
}

type NullChangeRequestStatus struct {
	ChangeRequestStatus ChangeRequestStatus `json:"change_request_status"`
	Valid               bool                `json:"valid"` // Valid is true if ChangeRequestStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullChangeRequestStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ChangeRequestStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ChangeRequestStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullChangeRequestStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ChangeRequestStatus), nil
}

type ComplaintCategory string

const (
	ComplaintCategoryResultError       ComplaintCategory = "result_error"
	ComplaintCategoryPaymentIssue      ComplaintCategory = "payment_issue"
	ComplaintCategoryProfileIssue      ComplaintCategory = "profile_issue"
	ComplaintCategoryAttendanceDispute ComplaintCategory = "attendance_dispute"
	ComplaintCategoryAssignmentIssue   ComplaintCategory = "assignment_issue"
	ComplaintCategoryOther             ComplaintCategory = "other"
)

func (e *ComplaintCategory) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ComplaintCategory(s)
	case string:
		*e = ComplaintCategory(s)
	default:
		return fmt.Errorf("unsupported scan type for ComplaintCategory: %T", src)
	}
	return nil
}

type NullComplaintCategory struct {
	ComplaintCategory ComplaintCategory `json:"complaint_category"`
	Valid             bool              `json:"valid"` // Valid is true if ComplaintCategory is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullComplaintCategory) Scan(value interface{}) error {
	if value == nil {
		ns.ComplaintCategory, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ComplaintCategory.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullComplaintCategory) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ComplaintCategory), nil
}

type ComplaintPriority string

const (
	ComplaintPriorityLow    ComplaintPriority = "low"
	ComplaintPriorityMedium ComplaintPriority = "medium"
	ComplaintPriorityHigh   ComplaintPriority = "high"
)

func (e *ComplaintPriority) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ComplaintPriority(s)
	case string:
		*e = ComplaintPriority(s)
	default:
		return fmt.Errorf("unsupported scan type for ComplaintPriority: %T", src)
	}
	return nil
}

type NullComplaintPriority struct {
	ComplaintPriority ComplaintPriority `json:"complaint_priority"`
	Valid             bool              `json:"valid"` // Valid is true if ComplaintPriority is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullComplaintPriority) Scan(value interface{}) error {
	if value == nil {
		ns.ComplaintPriority, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ComplaintPriority.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullComplaintPriority) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ComplaintPriority), nil
}

type ComplaintStatus string

const (
	ComplaintStatusOpen     ComplaintStatus = "open"
	ComplaintStatusInReview ComplaintStatus = "in_review"
	ComplaintStatusResolved ComplaintStatus = "resolved"
	ComplaintStatusRejected ComplaintStatus = "rejected"
)

func (e *ComplaintStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ComplaintStatus(s)
	case string:
		*e = ComplaintStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ComplaintStatus: %T", src)
	}
	return nil
}

type NullComplaintStatus struct {
	ComplaintStatus ComplaintStatus `json:"complaint_status"`
	Valid           bool            `json:"valid"` // Valid is true if ComplaintStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullComplaintStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ComplaintStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ComplaintStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullComplaintStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ComplaintStatus), nil
}

type ConnectionStatus string

const (
	ConnectionStatusPending  ConnectionStatus = "pending"
	ConnectionStatusAccepted ConnectionStatus = "accepted"
	ConnectionStatusRejected ConnectionStatus = "rejected"
	ConnectionStatusBlocked  ConnectionStatus = "blocked"
)

func (e *ConnectionStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ConnectionStatus(s)
	case string:
		*e = ConnectionStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ConnectionStatus: %T", src)
	}
	return nil
}

type NullConnectionStatus struct {
	ConnectionStatus ConnectionStatus `json:"connection_status"`
	Valid            bool             `json:"valid"` // Valid is true if ConnectionStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullConnectionStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ConnectionStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ConnectionStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullConnectionStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ConnectionStatus), nil
}

type DocumentStatus string

const (
	DocumentStatusPending  DocumentStatus = "pending"
	DocumentStatusVerified DocumentStatus = "verified"
	DocumentStatusRejected DocumentStatus = "rejected"
)

func (e *DocumentStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = DocumentStatus(s)
	case string:
		*e = DocumentStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for DocumentStatus: %T", src)
	}
	return nil
}

type NullDocumentStatus struct {
	DocumentStatus DocumentStatus `json:"document_status"`
	Valid          bool           `json:"valid"` // Valid is true if DocumentStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullDocumentStatus) Scan(value interface{}) error {
	if value == nil {
		ns.DocumentStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.DocumentStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullDocumentStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.DocumentStatus), nil
}

type DocumentType string

const (
	DocumentTypeProfilePhoto    DocumentType = "profile_photo"
	DocumentTypeIDCard          DocumentType = "id_card"
	DocumentTypeTranscript      DocumentType = "transcript"
	DocumentTypeCertificate     DocumentType = "certificate"
	DocumentTypeAdmissionLetter DocumentType = "admission_letter"
	DocumentTypeSupportingDoc   DocumentType = "supporting_doc"
	DocumentTypeMedicalReport   DocumentType = "medical_report"
)

func (e *DocumentType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = DocumentType(s)
	case string:
		*e = DocumentType(s)
	default:
		return fmt.Errorf("unsupported scan type for DocumentType: %T", src)
	}
	return nil
}

type NullDocumentType struct {
	DocumentType DocumentType `json:"document_type"`
	Valid        bool         `json:"valid"` // Valid is true if DocumentType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullDocumentType) Scan(value interface{}) error {
	if value == nil {
		ns.DocumentType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.DocumentType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullDocumentType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.DocumentType), nil
}

type DonationChannel string

const (
	DonationChannelGeneral          DonationChannel = "general"
	DonationChannelScholarship      DonationChannel = "scholarship"
	DonationChannelProject          DonationChannel = "project"
	DonationChannelEventSponsorship DonationChannel = "event_sponsorship"
	DonationChannelEmergency        DonationChannel = "emergency"
)

func (e *DonationChannel) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = DonationChannel(s)
	case string:
		*e = DonationChannel(s)
	default:
		return fmt.Errorf("unsupported scan type for DonationChannel: %T", src)
	}
	return nil
}

type NullDonationChannel struct {
	DonationChannel DonationChannel `json:"donation_channel"`
	Valid           bool            `json:"valid"` // Valid is true if DonationChannel is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullDonationChannel) Scan(value interface{}) error {
	if value == nil {
		ns.DonationChannel, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.DonationChannel.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullDonationChannel) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.DonationChannel), nil
}

type DonationTier string

const (
	DonationTierNone     DonationTier = "none"
	DonationTierBronze   DonationTier = "bronze"
	DonationTierSilver   DonationTier = "silver"
	DonationTierGold     DonationTier = "gold"
	DonationTierPlatinum DonationTier = "platinum"
)

func (e *DonationTier) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = DonationTier(s)
	case string:
		*e = DonationTier(s)
	default:
		return fmt.Errorf("unsupported scan type for DonationTier: %T", src)
	}
	return nil
}

type NullDonationTier struct {
	DonationTier DonationTier `json:"donation_tier"`
	Valid        bool         `json:"valid"` // Valid is true if DonationTier is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullDonationTier) Scan(value interface{}) error {
	if value == nil {
		ns.DonationTier, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.DonationTier.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullDonationTier) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.DonationTier), nil
}

type Grade string

const (
	GradeA Grade = "A"
	GradeB Grade = "B"
	GradeC Grade = "C"
	GradeD Grade = "D"
	GradeE Grade = "E"
	GradeF Grade = "F"
)

func (e *Grade) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Grade(s)
	case string:
		*e = Grade(s)
	default:
		return fmt.Errorf("unsupported scan type for Grade: %T", src)
	}
	return nil
}

type NullGrade struct {
	Grade Grade `json:"grade"`
	Valid bool  `json:"valid"` // Valid is true if Grade is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullGrade) Scan(value interface{}) error {
	if value == nil {
		ns.Grade, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Grade.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullGrade) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Grade), nil
}

type JobType string

const (
	JobTypeFullTime   JobType = "full_time"
	JobTypePartTime   JobType = "part_time"
	JobTypeInternship JobType = "internship"
	JobTypeContract   JobType = "contract"
	JobTypeRemote     JobType = "remote"
)

func (e *JobType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = JobType(s)
	case string:
		*e = JobType(s)
	default:
		return fmt.Errorf("unsupported scan type for JobType: %T", src)
	}
	return nil
}

type NullJobType struct {
	JobType JobType `json:"job_type"`
	Valid   bool    `json:"valid"` // Valid is true if JobType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullJobType) Scan(value interface{}) error {
	if value == nil {
		ns.JobType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.JobType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullJobType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.JobType), nil
}

type LeaveStatus string

const (
	LeaveStatusPending   LeaveStatus = "pending"
	LeaveStatusApproved  LeaveStatus = "approved"
	LeaveStatusActive    LeaveStatus = "active"
	LeaveStatusCompleted LeaveStatus = "completed"
	LeaveStatusRejected  LeaveStatus = "rejected"
	LeaveStatusCancelled LeaveStatus = "cancelled"
)

func (e *LeaveStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = LeaveStatus(s)
	case string:
		*e = LeaveStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for LeaveStatus: %T", src)
	}
	return nil
}

type NullLeaveStatus struct {
	LeaveStatus LeaveStatus `json:"leave_status"`
	Valid       bool        `json:"valid"` // Valid is true if LeaveStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullLeaveStatus) Scan(value interface{}) error {
	if value == nil {
		ns.LeaveStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.LeaveStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullLeaveStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.LeaveStatus), nil
}

type LeaveType string

const (
	LeaveTypeSabbatical LeaveType = "sabbatical"
	LeaveTypeStudy      LeaveType = "study"
	LeaveTypeSick       LeaveType = "sick"
	LeaveTypeMaternity  LeaveType = "maternity"
	LeaveTypePaternity  LeaveType = "paternity"
	LeaveTypeConference LeaveType = "conference"
	LeaveTypePersonal   LeaveType = "personal"
)

func (e *LeaveType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = LeaveType(s)
	case string:
		*e = LeaveType(s)
	default:
		return fmt.Errorf("unsupported scan type for LeaveType: %T", src)
	}
	return nil
}

type NullLeaveType struct {
	LeaveType LeaveType `json:"leave_type"`
	Valid     bool      `json:"valid"` // Valid is true if LeaveType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullLeaveType) Scan(value interface{}) error {
	if value == nil {
		ns.LeaveType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.LeaveType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullLeaveType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.LeaveType), nil
}

type MentorshipStatus string

const (
	MentorshipStatusPending   MentorshipStatus = "pending"
	MentorshipStatusAccepted  MentorshipStatus = "accepted"
	MentorshipStatusActive    MentorshipStatus = "active"
	MentorshipStatusCompleted MentorshipStatus = "completed"
	MentorshipStatusDeclined  MentorshipStatus = "declined"
)

func (e *MentorshipStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MentorshipStatus(s)
	case string:
		*e = MentorshipStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for MentorshipStatus: %T", src)
	}
	return nil
}

type NullMentorshipStatus struct {
	MentorshipStatus MentorshipStatus `json:"mentorship_status"`
	Valid            bool             `json:"valid"` // Valid is true if MentorshipStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMentorshipStatus) Scan(value interface{}) error {
	if value == nil {
		ns.MentorshipStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MentorshipStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMentorshipStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MentorshipStatus), nil
}

type NotificationType string

const (
	NotificationTypeResultPublished   NotificationType = "result_published"
	NotificationTypePaymentDue        NotificationType = "payment_due"
	NotificationTypeComplaintResolved NotificationType = "complaint_resolved"
	NotificationTypeAssignmentGraded  NotificationType = "assignment_graded"
	NotificationTypeDeadlineReminder  NotificationType = "deadline_reminder"
	NotificationTypeExamConflict      NotificationType = "exam_conflict"
	NotificationTypeProfileApproved   NotificationType = "profile_approved"
	NotificationTypeAnnouncement      NotificationType = "announcement"
	NotificationTypeGeneral           NotificationType = "general"
)

func (e *NotificationType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = NotificationType(s)
	case string:
		*e = NotificationType(s)
	default:
		return fmt.Errorf("unsupported scan type for NotificationType: %T", src)
	}
	return nil
}

type NullNotificationType struct {
	NotificationType NotificationType `json:"notification_type"`
	Valid            bool             `json:"valid"` // Valid is true if NotificationType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullNotificationType) Scan(value interface{}) error {
	if value == nil {
		ns.NotificationType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.NotificationType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullNotificationType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.NotificationType), nil
}

type PaymentStatus string

const (
	PaymentStatusPending   PaymentStatus = "pending"
	PaymentStatusCompleted PaymentStatus = "completed"
	PaymentStatusFailed    PaymentStatus = "failed"
	PaymentStatusRefunded  PaymentStatus = "refunded"
)

func (e *PaymentStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PaymentStatus(s)
	case string:
		*e = PaymentStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for PaymentStatus: %T", src)
	}
	return nil
}

type NullPaymentStatus struct {
	PaymentStatus PaymentStatus `json:"payment_status"`
	Valid         bool          `json:"valid"` // Valid is true if PaymentStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPaymentStatus) Scan(value interface{}) error {
	if value == nil {
		ns.PaymentStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PaymentStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPaymentStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PaymentStatus), nil
}

type PaymentType string

const (
	PaymentTypeDeptDues      PaymentType = "dept_dues"
	PaymentTypeClassDues     PaymentType = "class_dues"
	PaymentTypeManual        PaymentType = "manual"
	PaymentTypeMaterials     PaymentType = "materials"
	PaymentTypeTranscriptFee PaymentType = "transcript_fee"
	PaymentTypeOther         PaymentType = "other"
)

func (e *PaymentType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PaymentType(s)
	case string:
		*e = PaymentType(s)
	default:
		return fmt.Errorf("unsupported scan type for PaymentType: %T", src)
	}
	return nil
}

type NullPaymentType struct {
	PaymentType PaymentType `json:"payment_type"`
	Valid       bool        `json:"valid"` // Valid is true if PaymentType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPaymentType) Scan(value interface{}) error {
	if value == nil {
		ns.PaymentType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PaymentType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPaymentType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PaymentType), nil
}

type ProfileChangeType string

const (
	ProfileChangeTypeSelfEdit        ProfileChangeType = "self_edit"
	ProfileChangeTypeHodEdit         ProfileChangeType = "hod_edit"
	ProfileChangeTypeHodApproved     ProfileChangeType = "hod_approved"
	ProfileChangeTypeBulkEdit        ProfileChangeType = "bulk_edit"
	ProfileChangeTypeSystemCorrected ProfileChangeType = "system_corrected"
)

func (e *ProfileChangeType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ProfileChangeType(s)
	case string:
		*e = ProfileChangeType(s)
	default:
		return fmt.Errorf("unsupported scan type for ProfileChangeType: %T", src)
	}
	return nil
}

type NullProfileChangeType struct {
	ProfileChangeType ProfileChangeType `json:"profile_change_type"`
	Valid             bool              `json:"valid"` // Valid is true if ProfileChangeType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullProfileChangeType) Scan(value interface{}) error {
	if value == nil {
		ns.ProfileChangeType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ProfileChangeType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullProfileChangeType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ProfileChangeType), nil
}

type ReportStatus string

const (
	ReportStatusGenerating ReportStatus = "generating"
	ReportStatusCompleted  ReportStatus = "completed"
	ReportStatusFailed     ReportStatus = "failed"
)

func (e *ReportStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ReportStatus(s)
	case string:
		*e = ReportStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ReportStatus: %T", src)
	}
	return nil
}

type NullReportStatus struct {
	ReportStatus ReportStatus `json:"report_status"`
	Valid        bool         `json:"valid"` // Valid is true if ReportStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullReportStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ReportStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ReportStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullReportStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ReportStatus), nil
}

type ResultStatus string

const (
	ResultStatusPending  ResultStatus = "pending"
	ResultStatusApproved ResultStatus = "approved"
	ResultStatusRejected ResultStatus = "rejected"
)

func (e *ResultStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ResultStatus(s)
	case string:
		*e = ResultStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ResultStatus: %T", src)
	}
	return nil
}

type NullResultStatus struct {
	ResultStatus ResultStatus `json:"result_status"`
	Valid        bool         `json:"valid"` // Valid is true if ResultStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullResultStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ResultStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ResultStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullResultStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ResultStatus), nil
}

type ScheduledFrequency string

const (
	ScheduledFrequencyDaily    ScheduledFrequency = "daily"
	ScheduledFrequencyWeekly   ScheduledFrequency = "weekly"
	ScheduledFrequencyMonthly  ScheduledFrequency = "monthly"
	ScheduledFrequencySemester ScheduledFrequency = "semester"
)

func (e *ScheduledFrequency) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ScheduledFrequency(s)
	case string:
		*e = ScheduledFrequency(s)
	default:
		return fmt.Errorf("unsupported scan type for ScheduledFrequency: %T", src)
	}
	return nil
}

type NullScheduledFrequency struct {
	ScheduledFrequency ScheduledFrequency `json:"scheduled_frequency"`
	Valid              bool               `json:"valid"` // Valid is true if ScheduledFrequency is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullScheduledFrequency) Scan(value interface{}) error {
	if value == nil {
		ns.ScheduledFrequency, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ScheduledFrequency.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullScheduledFrequency) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ScheduledFrequency), nil
}

type SemesterSeason string

const (
	SemesterSeasonHarmattan SemesterSeason = "harmattan"
	SemesterSeasonRain      SemesterSeason = "rain"
)

func (e *SemesterSeason) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SemesterSeason(s)
	case string:
		*e = SemesterSeason(s)
	default:
		return fmt.Errorf("unsupported scan type for SemesterSeason: %T", src)
	}
	return nil
}

type NullSemesterSeason struct {
	SemesterSeason SemesterSeason `json:"semester_season"`
	Valid          bool           `json:"valid"` // Valid is true if SemesterSeason is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSemesterSeason) Scan(value interface{}) error {
	if value == nil {
		ns.SemesterSeason, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SemesterSeason.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSemesterSeason) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SemesterSeason), nil
}

type SkillLevel string

const (
	SkillLevelBeginner     SkillLevel = "beginner"
	SkillLevelIntermediate SkillLevel = "intermediate"
	SkillLevelAdvanced     SkillLevel = "advanced"
	SkillLevelExpert       SkillLevel = "expert"
)

func (e *SkillLevel) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SkillLevel(s)
	case string:
		*e = SkillLevel(s)
	default:
		return fmt.Errorf("unsupported scan type for SkillLevel: %T", src)
	}
	return nil
}

type NullSkillLevel struct {
	SkillLevel SkillLevel `json:"skill_level"`
	Valid      bool       `json:"valid"` // Valid is true if SkillLevel is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSkillLevel) Scan(value interface{}) error {
	if value == nil {
		ns.SkillLevel, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SkillLevel.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSkillLevel) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SkillLevel), nil
}

type SubcategoryModule string

const (
	SubcategoryModuleCourses       SubcategoryModule = "courses"
	SubcategoryModuleDues          SubcategoryModule = "dues"
	SubcategoryModuleSkills        SubcategoryModule = "skills"
	SubcategoryModuleEvents        SubcategoryModule = "events"
	SubcategoryModuleAnnouncements SubcategoryModule = "announcements"
	SubcategoryModuleJobs          SubcategoryModule = "jobs"
	SubcategoryModuleGroups        SubcategoryModule = "groups"
)

func (e *SubcategoryModule) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SubcategoryModule(s)
	case string:
		*e = SubcategoryModule(s)
	default:
		return fmt.Errorf("unsupported scan type for SubcategoryModule: %T", src)
	}
	return nil
}

type NullSubcategoryModule struct {
	SubcategoryModule SubcategoryModule `json:"subcategory_module"`
	Valid             bool              `json:"valid"` // Valid is true if SubcategoryModule is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSubcategoryModule) Scan(value interface{}) error {
	if value == nil {
		ns.SubcategoryModule, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SubcategoryModule.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSubcategoryModule) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SubcategoryModule), nil
}

type TradeStatus string

const (
	TradeStatusPending   TradeStatus = "pending"
	TradeStatusAccepted  TradeStatus = "accepted"
	TradeStatusCompleted TradeStatus = "completed"
	TradeStatusCancelled TradeStatus = "cancelled"
)

func (e *TradeStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TradeStatus(s)
	case string:
		*e = TradeStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for TradeStatus: %T", src)
	}
	return nil
}

type NullTradeStatus struct {
	TradeStatus TradeStatus `json:"trade_status"`
	Valid       bool        `json:"valid"` // Valid is true if TradeStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTradeStatus) Scan(value interface{}) error {
	if value == nil {
		ns.TradeStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TradeStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTradeStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TradeStatus), nil
}

type TranscriptStatus string

const (
	TranscriptStatusRequested      TranscriptStatus = "requested"
	TranscriptStatusPendingPayment TranscriptStatus = "pending_payment"
	TranscriptStatusProcessing     TranscriptStatus = "processing"
	TranscriptStatusReady          TranscriptStatus = "ready"
	TranscriptStatusSent           TranscriptStatus = "sent"
)

func (e *TranscriptStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TranscriptStatus(s)
	case string:
		*e = TranscriptStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for TranscriptStatus: %T", src)
	}
	return nil
}

type NullTranscriptStatus struct {
	TranscriptStatus TranscriptStatus `json:"transcript_status"`
	Valid            bool             `json:"valid"` // Valid is true if TranscriptStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTranscriptStatus) Scan(value interface{}) error {
	if value == nil {
		ns.TranscriptStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TranscriptStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTranscriptStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TranscriptStatus), nil
}

type UserRole string

const (
	UserRoleHod                UserRole = "hod"
	UserRoleAdmin              UserRole = "admin"
	UserRoleLecturer           UserRole = "lecturer"
	UserRoleClassRep           UserRole = "class_rep"
	UserRoleStudent            UserRole = "student"
	UserRoleBursarDept         UserRole = "bursar_dept"
	UserRoleBursarClass        UserRole = "bursar_class"
	UserRoleProjectCoordinator UserRole = "project_coordinator"
	UserRoleEventCoordinator   UserRole = "event_coordinator"
	UserRoleAlumniRep          UserRole = "alumni_rep"
)

func (e *UserRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserRole(s)
	case string:
		*e = UserRole(s)
	default:
		return fmt.Errorf("unsupported scan type for UserRole: %T", src)
	}
	return nil
}

type NullUserRole struct {
	UserRole UserRole `json:"user_role"`
	Valid    bool     `json:"valid"` // Valid is true if UserRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserRole) Scan(value interface{}) error {
	if value == nil {
		ns.UserRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserRole), nil
}

type AcademicStandingRule struct {
	ID       uuid.UUID       `json:"id"`
	MinCgpa  decimal.Decimal `json:"min_cgpa"`
	MaxCgpa  decimal.Decimal `json:"max_cgpa"`
	Standing string          `json:"standing"`
	IsActive bool            `json:"is_active"`
}

type AdminPermission struct {
	ID                     uuid.UUID          `json:"id"`
	UserID                 uuid.UUID          `json:"user_id"`
	CanManageResults       bool               `json:"can_manage_results"`
	CanManageUsers         bool               `json:"can_manage_users"`
	CanManageFinance       bool               `json:"can_manage_finance"`
	CanManageCourses       bool               `json:"can_manage_courses"`
	CanViewAnalytics       bool               `json:"can_view_analytics"`
	CanManageAnnouncements bool               `json:"can_manage_announcements"`
	CanBackupData          bool               `json:"can_backup_data"`
	GrantedByHodID         uuid.UUID          `json:"granted_by_hod_id"`
	GrantedAt              pgtype.Timestamptz `json:"granted_at"`
	ExpiresAt              pgtype.Timestamptz `json:"expires_at"`
	IsActive               bool               `json:"is_active"`
}

type AlumniAuditLog struct {
	ID        uuid.UUID          `json:"id"`
	AlumniID  uuid.UUID          `json:"alumni_id"`
	Action    string             `json:"action"`
	ActorID   uuid.UUID          `json:"actor_id"`
	Details   []byte             `json:"details"`
	IpAddress *netip.Addr        `json:"ip_address"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type AlumniDonation struct {
	ID             uuid.UUID          `json:"id"`
	DonorID        uuid.UUID          `json:"donor_id"`
	Channel        DonationChannel    `json:"channel"`
	Amount         decimal.Decimal    `json:"amount"`
	Currency       string             `json:"currency"`
	PaymentID      pgtype.UUID        `json:"payment_id"`
	ReceiptUrl     *string            `json:"receipt_url"`
	Message        *string            `json:"message"`
	IsAnonymous    bool               `json:"is_anonymous"`
	RecognizedTier DonationTier       `json:"recognized_tier"`
	Status         string             `json:"status"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type AlumniEvent struct {
	ID              uuid.UUID          `json:"id"`
	Title           string             `json:"title"`
	Description     *string            `json:"description"`
	EventType       string             `json:"event_type"`
	Location        *string            `json:"location"`
	IsVirtual       bool               `json:"is_virtual"`
	VirtualLink     *string            `json:"virtual_link"`
	StartDate       pgtype.Timestamptz `json:"start_date"`
	EndDate         pgtype.Timestamptz `json:"end_date"`
	MaxAttendees    *int32             `json:"max_attendees"`
	IsActive        bool               `json:"is_active"`
	CreatedBy       uuid.UUID          `json:"created_by"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	TargetAudience  *string            `json:"target_audience"`
	Status          *string            `json:"status"`
	ApprovedBy      pgtype.UUID        `json:"approved_by"`
	RsvpCount       *int32             `json:"rsvp_count"`
	AttendanceCount *int32             `json:"attendance_count"`
}

type AlumniStatus struct {
	ID                      uuid.UUID                `json:"id"`
	UserID                  uuid.UUID                `json:"user_id"`
	GraduationYear          int32                    `json:"graduation_year"`
	GraduationClass         *string                  `json:"graduation_class"`
	VerificationStatus      AlumniVerificationStatus `json:"verification_status"`
	VerifiedBy              pgtype.UUID              `json:"verified_by"`
	VerifiedAt              pgtype.Timestamptz       `json:"verified_at"`
	IsMentorAvailable       bool                     `json:"is_mentor_available"`
	MentorSpecialization    *string                  `json:"mentor_specialization"`
	CurrentCompany          *string                  `json:"current_company"`
	CurrentPosition         *string                  `json:"current_position"`
	LinkedinUrl             *string                  `json:"linkedin_url"`
	Bio                     *string                  `json:"bio"`
	CreatedAt               pgtype.Timestamptz       `json:"created_at"`
	UpdatedAt               pgtype.Timestamptz       `json:"updated_at"`
	Location                *string                  `json:"location"`
	PortfolioUrl            *string                  `json:"portfolio_url"`
	Skills                  []byte                   `json:"skills"`
	MentorshipTopics        []byte                   `json:"mentorship_topics"`
	WillingToSpeak          *bool                    `json:"willing_to_speak"`
	EventInterests          []byte                   `json:"event_interests"`
	PrivacyLevel            *string                  `json:"privacy_level"`
	DonationTotal           pgtype.Numeric           `json:"donation_total"`
	MentorshipSessionsCount *int32                   `json:"mentorship_sessions_count"`
	JobsPostedCount         *int32                   `json:"jobs_posted_count"`
	EventsAttendedCount     *int32                   `json:"events_attended_count"`
	Status                  *string                  `json:"status"`
	MatricNumber            *string                  `json:"matric_number"`
	FullName                *string                  `json:"full_name"`
	Department              *string                  `json:"department"`
	CgpaAtGraduation        pgtype.Numeric           `json:"cgpa_at_graduation"`
	Email                   *string                  `json:"email"`
	Phone                   *string                  `json:"phone"`
	Industry                *string                  `json:"industry"`
	JobTitle                *string                  `json:"job_title"`
	ProfilePhoto            *string                  `json:"profile_photo"`
}

type AnalyticsSnapshot struct {
	ID           uuid.UUID          `json:"id"`
	SnapshotDate pgtype.Date        `json:"snapshot_date"`
	MetricName   string             `json:"metric_name"`
	MetricValue  decimal.Decimal    `json:"metric_value"`
	Dimension    []byte             `json:"dimension"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type Announcement struct {
	ID             uuid.UUID          `json:"id"`
	Title          string             `json:"title"`
	Content        string             `json:"content"`
	IsPinned       bool               `json:"is_pinned"`
	TargetLevel    *int32             `json:"target_level"`
	TargetAudience []byte             `json:"target_audience"`
	ExpiresAt      pgtype.Timestamptz `json:"expires_at"`
	CreatedBy      uuid.UUID          `json:"created_by"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type Assignment struct {
	ID                   uuid.UUID          `json:"id"`
	CourseID             uuid.UUID          `json:"course_id"`
	Title                string             `json:"title"`
	Description          *string            `json:"description"`
	Deadline             pgtype.Timestamptz `json:"deadline"`
	MaxScore             int32              `json:"max_score"`
	AllowedFormats       []byte             `json:"allowed_formats"`
	FileUrl              *string            `json:"file_url"`
	UploadedByClassRepID pgtype.UUID        `json:"uploaded_by_class_rep_id"`
	CreatedBy            uuid.UUID          `json:"created_by"`
	SessionID            uuid.UUID          `json:"session_id"`
	SemesterID           uuid.UUID          `json:"semester_id"`
	IsActive             bool               `json:"is_active"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
}

type AssignmentGrade struct {
	ID           uuid.UUID          `json:"id"`
	AssignmentID uuid.UUID          `json:"assignment_id"`
	StudentID    uuid.UUID          `json:"student_id"`
	Score        pgtype.Numeric     `json:"score"`
	Feedback     *string            `json:"feedback"`
	IsLate       bool               `json:"is_late"`
	GradedBy     uuid.UUID          `json:"graded_by"`
	GradedAt     pgtype.Timestamptz `json:"graded_at"`
}

type AttendanceCheckin struct {
	ID          uuid.UUID          `json:"id"`
	SessionID   uuid.UUID          `json:"session_id"`
	StudentID   uuid.UUID          `json:"student_id"`
	CheckedInAt pgtype.Timestamptz `json:"checked_in_at"`
	Method      string             `json:"method"`
	Present     bool               `json:"present"`
	Remark      *string            `json:"remark"`
}

type AttendanceSession struct {
	ID            uuid.UUID          `json:"id"`
	CourseID      uuid.UUID          `json:"course_id"`
	ClassRepID    uuid.UUID          `json:"class_rep_id"`
	SessionID     pgtype.UUID        `json:"session_id"`
	SemesterID    pgtype.UUID        `json:"semester_id"`
	Date          pgtype.Timestamptz `json:"date"`
	Method        string             `json:"method"`
	Venue         *string            `json:"venue"`
	Status        string             `json:"status"`
	StartedAt     pgtype.Timestamptz `json:"started_at"`
	ClosedAt      pgtype.Timestamptz `json:"closed_at"`
	TotalPresent  int32              `json:"total_present"`
	TotalAbsent   int32              `json:"total_absent"`
	TotalStudents int32              `json:"total_students"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type AttendanceSheet struct {
	ID                uuid.UUID          `json:"id"`
	CourseID          uuid.UUID          `json:"course_id"`
	Date              pgtype.Timestamptz `json:"date"`
	ClassRepID        uuid.UUID          `json:"class_rep_id"`
	AttendanceData    json.RawMessage    `json:"attendance_data"`
	PdfUrl            *string            `json:"pdf_url"`
	Status            string             `json:"status"`
	FinalizedAt       pgtype.Timestamptz `json:"finalized_at"`
	EmailedToLecturer bool               `json:"emailed_to_lecturer"`
	SessionID         uuid.UUID          `json:"session_id"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

type Backup struct {
	ID        uuid.UUID          `json:"id"`
	FileName  string             `json:"file_name"`
	S3Url     string             `json:"s3_url"`
	SizeMb    pgtype.Numeric     `json:"size_mb"`
	Status    BackupStatus       `json:"status"`
	CreatedBy pgtype.UUID        `json:"created_by"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type BursarAssignment struct {
	ID         uuid.UUID          `json:"id"`
	UserID     uuid.UUID          `json:"user_id"`
	Level      int32              `json:"level"`
	BursarType string             `json:"bursar_type"`
	SessionID  pgtype.UUID        `json:"session_id"`
	AssignedBy uuid.UUID          `json:"assigned_by"`
	IsActive   bool               `json:"is_active"`
	AssignedAt pgtype.Timestamptz `json:"assigned_at"`
	RevokedAt  pgtype.Timestamptz `json:"revoked_at"`
}

type CarryoverCourse struct {
	ID                uuid.UUID          `json:"id"`
	StudentID         uuid.UUID          `json:"student_id"`
	CourseID          uuid.UUID          `json:"course_id"`
	OriginalResultID  uuid.UUID          `json:"original_result_id"`
	OriginalSessionID uuid.UUID          `json:"original_session_id"`
	AttemptCount      int32              `json:"attempt_count"`
	MaxAttempts       int32              `json:"max_attempts"`
	IsResolved        bool               `json:"is_resolved"`
	ResolvedResultID  pgtype.UUID        `json:"resolved_result_id"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

type CgpaRule struct {
	ID         uuid.UUID          `json:"id"`
	MinScore   decimal.Decimal    `json:"min_score"`
	MaxScore   decimal.Decimal    `json:"max_score"`
	Grade      string             `json:"grade"`
	GradePoint decimal.Decimal    `json:"grade_point"`
	IsActive   bool               `json:"is_active"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type ClassRepAssignment struct {
	ID               uuid.UUID          `json:"id"`
	ClassRepID       uuid.UUID          `json:"class_rep_id"`
	Level            int32              `json:"level"`
	AcademicYear     string             `json:"academic_year"`
	AppointmentType  string             `json:"appointment_type"`
	AppointedBy      pgtype.UUID        `json:"appointed_by"`
	StartDate        pgtype.Timestamptz `json:"start_date"`
	EndDate          pgtype.Timestamptz `json:"end_date"`
	IsActive         bool               `json:"is_active"`
	ConsecutiveTerms int32              `json:"consecutive_terms"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type ClassRepElection struct {
	ID              uuid.UUID          `json:"id"`
	Level           int32              `json:"level"`
	AcademicYear    string             `json:"academic_year"`
	CreatedBy       uuid.UUID          `json:"created_by"`
	Status          string             `json:"status"`
	NominationStart pgtype.Timestamptz `json:"nomination_start"`
	NominationEnd   pgtype.Timestamptz `json:"nomination_end"`
	VotingStart     pgtype.Timestamptz `json:"voting_start"`
	VotingEnd       pgtype.Timestamptz `json:"voting_end"`
	WinnerID        pgtype.UUID        `json:"winner_id"`
	TotalVotes      int32              `json:"total_votes"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type ClassRepPerformance struct {
	ID                  uuid.UUID          `json:"id"`
	ClassRepID          uuid.UUID          `json:"class_rep_id"`
	ReviewedBy          uuid.UUID          `json:"reviewed_by"`
	AcademicYear        string             `json:"academic_year"`
	Term                string             `json:"term"`
	AttendanceRate      pgtype.Numeric     `json:"attendance_rate"`
	ReportsSubmitted    int32              `json:"reports_submitted"`
	ResponsivenessScore *int32             `json:"responsiveness_score"`
	Comments            *string            `json:"comments"`
	Rating              *string            `json:"rating"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
}

type ClassRepReport struct {
	ID           uuid.UUID          `json:"id"`
	ClassRepID   uuid.UUID          `json:"class_rep_id"`
	ReportType   string             `json:"report_type"`
	Title        string             `json:"title"`
	Content      string             `json:"content"`
	Level        *int32             `json:"level"`
	AcademicYear *string            `json:"academic_year"`
	Status       string             `json:"status"`
	ReviewedBy   pgtype.UUID        `json:"reviewed_by"`
	ReviewNotes  *string            `json:"review_notes"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type Complaint struct {
	ID         uuid.UUID          `json:"id"`
	StudentID  uuid.UUID          `json:"student_id"`
	Category   ComplaintCategory  `json:"category"`
	Subject    string             `json:"subject"`
	Body       string             `json:"body"`
	Priority   ComplaintPriority  `json:"priority"`
	Status     ComplaintStatus    `json:"status"`
	AssignedTo pgtype.UUID        `json:"assigned_to"`
	Resolution *string            `json:"resolution"`
	ResolvedAt pgtype.Timestamptz `json:"resolved_at"`
	ResolvedBy pgtype.UUID        `json:"resolved_by"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type Connection struct {
	ID          uuid.UUID          `json:"id"`
	RequesterID uuid.UUID          `json:"requester_id"`
	ReceiverID  uuid.UUID          `json:"receiver_id"`
	Status      ConnectionStatus   `json:"status"`
	Message     *string            `json:"message"`
	RespondedAt pgtype.Timestamptz `json:"responded_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type Course struct {
	ID             uuid.UUID          `json:"id"`
	Code           string             `json:"code"`
	Title          string             `json:"title"`
	Description    *string            `json:"description"`
	Unit           int32              `json:"unit"`
	Level          int32              `json:"level"`
	Semester       SemesterSeason     `json:"semester"`
	LecturerID     pgtype.UUID        `json:"lecturer_id"`
	PrerequisiteID pgtype.UUID        `json:"prerequisite_id"`
	MaxCreditHours *int32             `json:"max_credit_hours"`
	IsActive       bool               `json:"is_active"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	CourseType     string             `json:"course_type"`
}

type CourseRegistration struct {
	ID         uuid.UUID          `json:"id"`
	StudentID  uuid.UUID          `json:"student_id"`
	SessionID  uuid.UUID          `json:"session_id"`
	SemesterID uuid.UUID          `json:"semester_id"`
	TotalUnits int32              `json:"total_units"`
	Status     string             `json:"status"`
	ApprovedBy pgtype.UUID        `json:"approved_by"`
	ApprovedAt pgtype.Timestamptz `json:"approved_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type CourseSubcategory struct {
	ID               uuid.UUID          `json:"id"`
	CourseID         uuid.UUID          `json:"course_id"`
	Name             string             `json:"name"`
	WeightPercentage int32              `json:"weight_percentage"`
	IsActive         bool               `json:"is_active"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

type Due struct {
	ID          uuid.UUID          `json:"id"`
	Name        string             `json:"name"`
	Description *string            `json:"description"`
	Type        PaymentType        `json:"type"`
	Amount      decimal.Decimal    `json:"amount"`
	Level       *int32             `json:"level"`
	SessionID   pgtype.UUID        `json:"session_id"`
	SemesterID  pgtype.UUID        `json:"semester_id"`
	Deadline    pgtype.Timestamptz `json:"deadline"`
	IsActive    bool               `json:"is_active"`
	CreatedBy   uuid.UUID          `json:"created_by"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type ElectionNominee struct {
	ID          uuid.UUID          `json:"id"`
	ElectionID  uuid.UUID          `json:"election_id"`
	StudentID   uuid.UUID          `json:"student_id"`
	Manifesto   *string            `json:"manifesto"`
	NominatedBy uuid.UUID          `json:"nominated_by"`
	Status      string             `json:"status"`
	ApprovedBy  pgtype.UUID        `json:"approved_by"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type ElectionVote struct {
	ID         uuid.UUID          `json:"id"`
	ElectionID uuid.UUID          `json:"election_id"`
	NomineeID  uuid.UUID          `json:"nominee_id"`
	VoterID    uuid.UUID          `json:"voter_id"`
	VotedAt    pgtype.Timestamptz `json:"voted_at"`
}

type EventAttendee struct {
	ID           uuid.UUID          `json:"id"`
	EventID      uuid.UUID          `json:"event_id"`
	UserID       uuid.UUID          `json:"user_id"`
	RsvpStatus   string             `json:"rsvp_status"`
	RegisteredAt pgtype.Timestamptz `json:"registered_at"`
}

type Group struct {
	ID          uuid.UUID          `json:"id"`
	Name        string             `json:"name"`
	Description *string            `json:"description"`
	Category    string             `json:"category"`
	AvatarUrl   *string            `json:"avatar_url"`
	MaxMembers  *int32             `json:"max_members"`
	IsPrivate   bool               `json:"is_private"`
	CreatedBy   uuid.UUID          `json:"created_by"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type GroupMember struct {
	ID       uuid.UUID          `json:"id"`
	GroupID  uuid.UUID          `json:"group_id"`
	UserID   uuid.UUID          `json:"user_id"`
	Role     string             `json:"role"`
	JoinedAt pgtype.Timestamptz `json:"joined_at"`
}

type GroupMessage struct {
	ID        uuid.UUID          `json:"id"`
	GroupID   uuid.UUID          `json:"group_id"`
	SenderID  uuid.UUID          `json:"sender_id"`
	Content   string             `json:"content"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type JobApplication struct {
	ID          uuid.UUID          `json:"id"`
	JobID       uuid.UUID          `json:"job_id"`
	ApplicantID uuid.UUID          `json:"applicant_id"`
	Status      ApplicationStatus  `json:"status"`
	CoverLetter *string            `json:"cover_letter"`
	ResumeUrl   *string            `json:"resume_url"`
	ReviewedBy  pgtype.UUID        `json:"reviewed_by"`
	ReviewedAt  pgtype.Timestamptz `json:"reviewed_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type JobPost struct {
	ID                  uuid.UUID          `json:"id"`
	PostedBy            uuid.UUID          `json:"posted_by"`
	Title               string             `json:"title"`
	Company             string             `json:"company"`
	Location            *string            `json:"location"`
	JobType             JobType            `json:"job_type"`
	Description         string             `json:"description"`
	Requirements        *string            `json:"requirements"`
	SalaryRange         *string            `json:"salary_range"`
	ApplicationUrl      *string            `json:"application_url"`
	ApplicationDeadline pgtype.Timestamptz `json:"application_deadline"`
	IsActive            bool               `json:"is_active"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
	Industry            *string            `json:"industry"`
	Responsibilities    *string            `json:"responsibilities"`
	TargetLevels        []byte             `json:"target_levels"`
	TargetDepartments   []byte             `json:"target_departments"`
	ApplicationMethod   *string            `json:"application_method"`
	ApprovedBy          pgtype.UUID        `json:"approved_by"`
	ViewsCount          *int32             `json:"views_count"`
	ApplicationsCount   *int32             `json:"applications_count"`
}

type LecturerCourseAssignment struct {
	ID             uuid.UUID          `json:"id"`
	LecturerID     uuid.UUID          `json:"lecturer_id"`
	CourseID       uuid.UUID          `json:"course_id"`
	SessionID      uuid.UUID          `json:"session_id"`
	Semester       string             `json:"semester"`
	IsPrimary      bool               `json:"is_primary"`
	AssignedBy     uuid.UUID          `json:"assigned_by"`
	ReassignedFrom pgtype.UUID        `json:"reassigned_from"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type LecturerEvaluation struct {
	ID            uuid.UUID          `json:"id"`
	LecturerID    uuid.UUID          `json:"lecturer_id"`
	CourseID      uuid.UUID          `json:"course_id"`
	SessionID     uuid.UUID          `json:"session_id"`
	StudentAnonID uuid.UUID          `json:"student_anon_id"`
	Clarity       *int16             `json:"clarity"`
	Punctuality   *int16             `json:"punctuality"`
	Availability  *int16             `json:"availability"`
	Fairness      *int16             `json:"fairness"`
	Technology    *int16             `json:"technology"`
	Overall       *int16             `json:"overall"`
	Comments      *string            `json:"comments"`
	SubmittedAt   pgtype.Timestamptz `json:"submitted_at"`
}

type LecturerLeave struct {
	ID             uuid.UUID          `json:"id"`
	LecturerID     uuid.UUID          `json:"lecturer_id"`
	LeaveType      LeaveType          `json:"leave_type"`
	StartDate      pgtype.Date        `json:"start_date"`
	EndDate        pgtype.Date        `json:"end_date"`
	Reason         string             `json:"reason"`
	CourseHandover []byte             `json:"course_handover"`
	Status         LeaveStatus        `json:"status"`
	ApprovedBy     pgtype.UUID        `json:"approved_by"`
	ApprovedAt     pgtype.Timestamptz `json:"approved_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type LecturerPerformance struct {
	ID                  uuid.UUID          `json:"id"`
	LecturerID          uuid.UUID          `json:"lecturer_id"`
	SessionID           uuid.UUID          `json:"session_id"`
	StudentEvalScore    pgtype.Numeric     `json:"student_eval_score"`
	HodAssessmentScore  pgtype.Numeric     `json:"hod_assessment_score"`
	PeerReviewScore     pgtype.Numeric     `json:"peer_review_score"`
	ResearchOutputScore pgtype.Numeric     `json:"research_output_score"`
	OverallScore        pgtype.Numeric     `json:"overall_score"`
	HodComments         *string            `json:"hod_comments"`
	CreatedBy           pgtype.UUID        `json:"created_by"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
}

type Manual struct {
	ID            uuid.UUID          `json:"id"`
	Title         string             `json:"title"`
	Description   *string            `json:"description"`
	Level         int32              `json:"level"`
	Price         decimal.Decimal    `json:"price"`
	FileUrl       *string            `json:"file_url"`
	CoverImageUrl *string            `json:"cover_image_url"`
	CourseID      pgtype.UUID        `json:"course_id"`
	SessionID     pgtype.UUID        `json:"session_id"`
	IsActive      bool               `json:"is_active"`
	CreatedBy     uuid.UUID          `json:"created_by"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type ManualPrintQueue struct {
	ID          uuid.UUID          `json:"id"`
	PurchaseID  uuid.UUID          `json:"purchase_id"`
	StudentID   uuid.UUID          `json:"student_id"`
	ManualID    uuid.UUID          `json:"manual_id"`
	Status      string             `json:"status"`
	QueuedAt    pgtype.Timestamptz `json:"queued_at"`
	PrintedAt   pgtype.Timestamptz `json:"printed_at"`
	CollectedAt pgtype.Timestamptz `json:"collected_at"`
	ProcessedBy pgtype.UUID        `json:"processed_by"`
}

type ManualPurchase struct {
	ID          uuid.UUID          `json:"id"`
	StudentID   uuid.UUID          `json:"student_id"`
	ManualID    uuid.UUID          `json:"manual_id"`
	PaymentID   pgtype.UUID        `json:"payment_id"`
	QrCodeData  *string            `json:"qr_code_data"`
	QrCodeUrl   *string            `json:"qr_code_url"`
	IsCollected bool               `json:"is_collected"`
	CollectedAt pgtype.Timestamptz `json:"collected_at"`
	PurchasedAt pgtype.Timestamptz `json:"purchased_at"`
}

type MentorshipRequest struct {
	ID          uuid.UUID          `json:"id"`
	StudentID   uuid.UUID          `json:"student_id"`
	MentorID    uuid.UUID          `json:"mentor_id"`
	Status      MentorshipStatus   `json:"status"`
	Topic       string             `json:"topic"`
	Message     *string            `json:"message"`
	RespondedAt pgtype.Timestamptz `json:"responded_at"`
	StartedAt   pgtype.Timestamptz `json:"started_at"`
	EndedAt     pgtype.Timestamptz `json:"ended_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type MentorshipSession struct {
	ID              uuid.UUID          `json:"id"`
	MentorshipID    uuid.UUID          `json:"mentorship_id"`
	ScheduledAt     pgtype.Timestamptz `json:"scheduled_at"`
	Format          string             `json:"format"`
	Status          string             `json:"status"`
	Notes           *string            `json:"notes"`
	MentorConfirmed bool               `json:"mentor_confirmed"`
	MenteeConfirmed bool               `json:"mentee_confirmed"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type Message struct {
	ID         uuid.UUID          `json:"id"`
	SenderID   uuid.UUID          `json:"sender_id"`
	ReceiverID uuid.UUID          `json:"receiver_id"`
	Content    string             `json:"content"`
	IsRead     bool               `json:"is_read"`
	ReadAt     pgtype.Timestamptz `json:"read_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type Notification struct {
	ID        uuid.UUID          `json:"id"`
	UserID    uuid.UUID          `json:"user_id"`
	Type      NotificationType   `json:"type"`
	Title     string             `json:"title"`
	Message   string             `json:"message"`
	IsRead    bool               `json:"is_read"`
	ActionUrl *string            `json:"action_url"`
	EmailSent bool               `json:"email_sent"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Payment struct {
	ID                uuid.UUID          `json:"id"`
	StudentID         uuid.UUID          `json:"student_id"`
	BatchID           pgtype.UUID        `json:"batch_id"`
	DueID             uuid.UUID          `json:"due_id"`
	Type              PaymentType        `json:"type"`
	ItemName          string             `json:"item_name"`
	Amount            decimal.Decimal    `json:"amount"`
	PaystackReference *string            `json:"paystack_reference"`
	Status            PaymentStatus      `json:"status"`
	VerifiedBy        pgtype.UUID        `json:"verified_by"`
	VerifiedAt        pgtype.Timestamptz `json:"verified_at"`
	PaidAt            pgtype.Timestamptz `json:"paid_at"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	PaymentMethod     *string            `json:"payment_method"`
	BankReference     *string            `json:"bank_reference"`
	BankName          *string            `json:"bank_name"`
	ReceiptUrl        *string            `json:"receipt_url"`
	RecordedBy        pgtype.UUID        `json:"recorded_by"`
	Notes             *string            `json:"notes"`
}

type PaymentBatch struct {
	ID                uuid.UUID          `json:"id"`
	StudentID         uuid.UUID          `json:"student_id"`
	TotalAmount       decimal.Decimal    `json:"total_amount"`
	PaystackReference *string            `json:"paystack_reference"`
	Status            PaymentStatus      `json:"status"`
	ReceiptUrl        *string            `json:"receipt_url"`
	PaidAt            pgtype.Timestamptz `json:"paid_at"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

type PaymentCart struct {
	ID        uuid.UUID          `json:"id"`
	StudentID uuid.UUID          `json:"student_id"`
	DueID     uuid.UUID          `json:"due_id"`
	Amount    decimal.Decimal    `json:"amount"`
	AddedAt   pgtype.Timestamptz `json:"added_at"`
}

type PracticalEnrollment struct {
	ID               uuid.UUID          `json:"id"`
	StudentID        uuid.UUID          `json:"student_id"`
	CourseID         uuid.UUID          `json:"course_id"`
	ManualPurchaseID pgtype.UUID        `json:"manual_purchase_id"`
	SessionID        uuid.UUID          `json:"session_id"`
	EnrolledVia      string             `json:"enrolled_via"`
	EnrolledAt       pgtype.Timestamptz `json:"enrolled_at"`
}

type ProfileEditLog struct {
	ID            uuid.UUID          `json:"id"`
	StudentID     uuid.UUID          `json:"student_id"`
	FieldName     string             `json:"field_name"`
	OldValue      *string            `json:"old_value"`
	NewValue      *string            `json:"new_value"`
	ChangedBy     uuid.UUID          `json:"changed_by"`
	ChangedByRole string             `json:"changed_by_role"`
	ChangeType    ProfileChangeType  `json:"change_type"`
	Reason        *string            `json:"reason"`
	IpAddress     *string            `json:"ip_address"`
	RequestID     pgtype.UUID        `json:"request_id"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type ProfileUpdateRequest struct {
	ID              uuid.UUID          `json:"id"`
	StudentID       uuid.UUID          `json:"student_id"`
	FieldName       string             `json:"field_name"`
	OldValue        *string            `json:"old_value"`
	NewValue        string             `json:"new_value"`
	Status          string             `json:"status"`
	ApprovedBy      pgtype.UUID        `json:"approved_by"`
	ApprovedAt      pgtype.Timestamptz `json:"approved_at"`
	RejectionReason *string            `json:"rejection_reason"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type RegisteredCourse struct {
	ID                uuid.UUID          `json:"id"`
	RegistrationID    uuid.UUID          `json:"registration_id"`
	CourseID          uuid.UUID          `json:"course_id"`
	Status            string             `json:"status"`
	IsCarryover       bool               `json:"is_carryover"`
	PreviousAttemptID pgtype.UUID        `json:"previous_attempt_id"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

type Report struct {
	ID          uuid.UUID          `json:"id"`
	Title       string             `json:"title"`
	ReportType  string             `json:"report_type"`
	Format      string             `json:"format"`
	FileUrl     *string            `json:"file_url"`
	Status      ReportStatus       `json:"status"`
	GeneratedBy pgtype.UUID        `json:"generated_by"`
	Parameters  []byte             `json:"parameters"`
	RowCount    *int32             `json:"row_count"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	CompletedAt pgtype.Timestamptz `json:"completed_at"`
}

type Result struct {
	ID              uuid.UUID          `json:"id"`
	StudentID       uuid.UUID          `json:"student_id"`
	CourseID        uuid.UUID          `json:"course_id"`
	CaScore         decimal.Decimal    `json:"ca_score"`
	ExamScore       decimal.Decimal    `json:"exam_score"`
	TotalScore      decimal.Decimal    `json:"total_score"`
	Grade           *Grade             `json:"grade"`
	GradePoint      pgtype.Numeric     `json:"grade_point"`
	SessionID       uuid.UUID          `json:"session_id"`
	SemesterID      uuid.UUID          `json:"semester_id"`
	Status          ResultStatus       `json:"status"`
	ApprovedBy      pgtype.UUID        `json:"approved_by"`
	ApprovedAt      pgtype.Timestamptz `json:"approved_at"`
	RejectionReason *string            `json:"rejection_reason"`
	IsCarryover     bool               `json:"is_carryover"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type ResultAuditLog struct {
	ID           uuid.UUID          `json:"id"`
	ResultID     uuid.UUID          `json:"result_id"`
	FieldChanged string             `json:"field_changed"`
	OldValue     *string            `json:"old_value"`
	NewValue     *string            `json:"new_value"`
	Reason       string             `json:"reason"`
	EditedBy     uuid.UUID          `json:"edited_by"`
	IpAddress    *string            `json:"ip_address"`
	UserAgent    *string            `json:"user_agent"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type RoleAssignmentLog struct {
	ID              uuid.UUID          `json:"id"`
	UserID          uuid.UUID          `json:"user_id"`
	Role            UserRole           `json:"role"`
	Action          string             `json:"action"`
	PerformedBy     uuid.UUID          `json:"performed_by"`
	PerformedByRole *string            `json:"performed_by_role"`
	PreviousRoles   []byte             `json:"previous_roles"`
	NewRoles        []byte             `json:"new_roles"`
	Reason          *string            `json:"reason"`
	IpAddress       *string            `json:"ip_address"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type RolePromotion struct {
	ID         uuid.UUID          `json:"id"`
	UserID     uuid.UUID          `json:"user_id"`
	FromRole   *UserRole          `json:"from_role"`
	ToRole     UserRole           `json:"to_role"`
	PromotedBy uuid.UUID          `json:"promoted_by"`
	Reason     *string            `json:"reason"`
	IpAddress  *string            `json:"ip_address"`
	UserAgent  *string            `json:"user_agent"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type ScheduledReport struct {
	ID         uuid.UUID          `json:"id"`
	Title      string             `json:"title"`
	ReportType string             `json:"report_type"`
	Format     string             `json:"format"`
	Frequency  ScheduledFrequency `json:"frequency"`
	Recipients json.RawMessage    `json:"recipients"`
	Parameters []byte             `json:"parameters"`
	IsActive   bool               `json:"is_active"`
	LastRun    pgtype.Timestamptz `json:"last_run"`
	NextRun    pgtype.Timestamptz `json:"next_run"`
	CreatedBy  pgtype.UUID        `json:"created_by"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type Semester struct {
	ID                   uuid.UUID          `json:"id"`
	SessionID            uuid.UUID          `json:"session_id"`
	Name                 SemesterSeason     `json:"name"`
	StartDate            pgtype.Timestamptz `json:"start_date"`
	EndDate              pgtype.Timestamptz `json:"end_date"`
	RegistrationDeadline pgtype.Timestamptz `json:"registration_deadline"`
	IsActive             bool               `json:"is_active"`
}

type Session struct {
	ID         uuid.UUID          `json:"id"`
	Name       string             `json:"name"`
	StartDate  pgtype.Timestamptz `json:"start_date"`
	EndDate    pgtype.Timestamptz `json:"end_date"`
	IsActive   bool               `json:"is_active"`
	IsArchived bool               `json:"is_archived"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type SignupApproval struct {
	ID              uuid.UUID          `json:"id"`
	UserID          uuid.UUID          `json:"user_id"`
	SignupType      string             `json:"signup_type"`
	Status          string             `json:"status"`
	RegNo           *string            `json:"reg_no"`
	Level           *int32             `json:"level"`
	ApprovedBy      pgtype.UUID        `json:"approved_by"`
	ApprovedAt      pgtype.Timestamptz `json:"approved_at"`
	RejectionReason *string            `json:"rejection_reason"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type SkillCategory struct {
	ID          uuid.UUID          `json:"id"`
	Name        string             `json:"name"`
	Description *string            `json:"description"`
	Icon        *string            `json:"icon"`
	IsActive    bool               `json:"is_active"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type SkillListing struct {
	ID                uuid.UUID          `json:"id"`
	UserID            uuid.UUID          `json:"user_id"`
	CategoryID        uuid.UUID          `json:"category_id"`
	Title             string             `json:"title"`
	Description       *string            `json:"description"`
	SkillLevel        SkillLevel         `json:"skill_level"`
	Price             pgtype.Numeric     `json:"price"`
	IsFree            bool               `json:"is_free"`
	BarterAvailable   bool               `json:"barter_available"`
	BarterDescription *string            `json:"barter_description"`
	PortfolioUrl      *string            `json:"portfolio_url"`
	IsActive          bool               `json:"is_active"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

type SkillRating struct {
	ID          uuid.UUID          `json:"id"`
	TradeID     uuid.UUID          `json:"trade_id"`
	RaterID     uuid.UUID          `json:"rater_id"`
	RatedUserID uuid.UUID          `json:"rated_user_id"`
	Rating      int32              `json:"rating"`
	Review      *string            `json:"review"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type Staff struct {
	ID               uuid.UUID          `json:"id"`
	UserID           uuid.UUID          `json:"user_id"`
	StaffID          string             `json:"staff_id"`
	Department       string             `json:"department"`
	Rank             *string            `json:"rank"`
	Specialization   *string            `json:"specialization"`
	EmploymentDate   pgtype.Timestamptz `json:"employment_date"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	Title            *string            `json:"title"`
	FirstName        *string            `json:"first_name"`
	LastName         *string            `json:"last_name"`
	EmploymentType   *string            `json:"employment_type"`
	EmploymentStatus *string            `json:"employment_status"`
	Qualifications   []byte             `json:"qualifications"`
	Bio              *string            `json:"bio"`
	OfficeLocation   *string            `json:"office_location"`
	OfficeHours      []byte             `json:"office_hours"`
	Publications     []byte             `json:"publications"`
	DateJoined       pgtype.Date        `json:"date_joined"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type Student struct {
	ID                   uuid.UUID          `json:"id"`
	UserID               uuid.UUID          `json:"user_id"`
	MatricNumber         string             `json:"matric_number"`
	Level                int32              `json:"level"`
	EntryYear            int32              `json:"entry_year"`
	CurrentSessionID     pgtype.UUID        `json:"current_session_id"`
	CurrentSemester      *SemesterSeason    `json:"current_semester"`
	Cgpa                 pgtype.Numeric     `json:"cgpa"`
	TotalCreditsEarned   *int32             `json:"total_credits_earned"`
	TotalCreditsRequired *int32             `json:"total_credits_required"`
	AcademicStanding     *AcademicStanding  `json:"academic_standing"`
	GraduationStatus     *string            `json:"graduation_status"`
	IsDefaulter          bool               `json:"is_defaulter"`
	DefaulterReason      *string            `json:"defaulter_reason"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
	AdmissionMode        *string            `json:"admission_mode"`
	YearAdmitted         *int32             `json:"year_admitted"`
	OnboardingCompleted  bool               `json:"onboarding_completed"`
}

type StudentDocument struct {
	ID              uuid.UUID          `json:"id"`
	StudentID       uuid.UUID          `json:"student_id"`
	DocType         DocumentType       `json:"doc_type"`
	FileUrl         string             `json:"file_url"`
	FileName        string             `json:"file_name"`
	FileSize        int32              `json:"file_size"`
	UploadedBy      uuid.UUID          `json:"uploaded_by"`
	Status          DocumentStatus     `json:"status"`
	VerifiedBy      pgtype.UUID        `json:"verified_by"`
	VerifiedAt      pgtype.Timestamptz `json:"verified_at"`
	RejectionReason *string            `json:"rejection_reason"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type Subcategory struct {
	ID          uuid.UUID          `json:"id"`
	Module      SubcategoryModule  `json:"module"`
	Name        string             `json:"name"`
	Description *string            `json:"description"`
	Color       *string            `json:"color"`
	SortOrder   int32              `json:"sort_order"`
	IsActive    bool               `json:"is_active"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type SubcategoryAssignment struct {
	ID            uuid.UUID          `json:"id"`
	SubcategoryID uuid.UUID          `json:"subcategory_id"`
	EntityType    string             `json:"entity_type"`
	EntityID      uuid.UUID          `json:"entity_id"`
	AssignedAt    pgtype.Timestamptz `json:"assigned_at"`
	AssignedBy    pgtype.UUID        `json:"assigned_by"`
}

type Timetable struct {
	ID              uuid.UUID          `json:"id"`
	CourseID        uuid.UUID          `json:"course_id"`
	ExamDate        pgtype.Timestamptz `json:"exam_date"`
	StartTime       pgtype.Timestamptz `json:"start_time"`
	EndTime         pgtype.Timestamptz `json:"end_time"`
	Venue           string             `json:"venue"`
	SessionID       pgtype.UUID        `json:"session_id"`
	SemesterID      pgtype.UUID        `json:"semester_id"`
	HasConflict     bool               `json:"has_conflict"`
	ConflictDetails []byte             `json:"conflict_details"`
	CreatedBy       pgtype.UUID        `json:"created_by"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	DayOfWeek       *int32             `json:"day_of_week"`
	Level           *int32             `json:"level"`
	EntryType       string             `json:"entry_type"`
	ClassType       *string            `json:"class_type"`
	LecturerID      pgtype.UUID        `json:"lecturer_id"`
	ExamType        *string            `json:"exam_type"`
	Invigilators    *string            `json:"invigilators"`
	IsPublished     bool               `json:"is_published"`
	PublishedAt     pgtype.Timestamptz `json:"published_at"`
}

type TradeOffer struct {
	ID               uuid.UUID          `json:"id"`
	FromUserID       uuid.UUID          `json:"from_user_id"`
	ToUserID         uuid.UUID          `json:"to_user_id"`
	OfferedSkillID   uuid.UUID          `json:"offered_skill_id"`
	RequestedSkillID pgtype.UUID        `json:"requested_skill_id"`
	Status           TradeStatus        `json:"status"`
	Message          *string            `json:"message"`
	PriceOffered     pgtype.Numeric     `json:"price_offered"`
	IsBarter         bool               `json:"is_barter"`
	RespondedAt      pgtype.Timestamptz `json:"responded_at"`
	CompletedAt      pgtype.Timestamptz `json:"completed_at"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

type TranscriptRequest struct {
	ID           uuid.UUID          `json:"id"`
	StudentID    uuid.UUID          `json:"student_id"`
	Purpose      string             `json:"purpose"`
	Status       TranscriptStatus   `json:"status"`
	FeePaid      bool               `json:"fee_paid"`
	FeeAmount    pgtype.Numeric     `json:"fee_amount"`
	PdfUrl       *string            `json:"pdf_url"`
	QrCodeUrl    *string            `json:"qr_code_url"`
	SentViaEmail bool               `json:"sent_via_email"`
	EmailedAt    pgtype.Timestamptz `json:"emailed_at"`
	ProcessedBy  pgtype.UUID        `json:"processed_by"`
	ProcessedAt  pgtype.Timestamptz `json:"processed_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID                    uuid.UUID          `json:"id"`
	Email                 string             `json:"email"`
	PasswordHash          string             `json:"password_hash"`
	Role                  UserRole           `json:"role"`
	FullName              string             `json:"full_name"`
	Phone                 *string            `json:"phone"`
	AvatarUrl             *string            `json:"avatar_url"`
	IsActive              bool               `json:"is_active"`
	EmailVerified         bool               `json:"email_verified"`
	TwoFactorEnabled      bool               `json:"two_factor_enabled"`
	LastLoginAt           pgtype.Timestamptz `json:"last_login_at"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
	DeletedAt             pgtype.Timestamptz `json:"deleted_at"`
	CreatedByHodID        pgtype.UUID        `json:"created_by_hod_id"`
	IsApproved            bool               `json:"is_approved"`
	ApprovedBy            pgtype.UUID        `json:"approved_by"`
	ApprovedAt            pgtype.Timestamptz `json:"approved_at"`
	DateOfBirth           pgtype.Date        `json:"date_of_birth"`
	EmergencyContactName  *string            `json:"emergency_contact_name"`
	EmergencyContactPhone *string            `json:"emergency_contact_phone"`
	HomeAddress           *string            `json:"home_address"`
}

type UserReputation struct {
	ID                   uuid.UUID          `json:"id"`
	UserID               uuid.UUID          `json:"user_id"`
	TotalRatings         int32              `json:"total_ratings"`
	AverageRating        decimal.Decimal    `json:"average_rating"`
	TotalTradesCompleted int32              `json:"total_trades_completed"`
	ReputationScore      decimal.Decimal    `json:"reputation_score"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
}

type UserRoleAssignment struct {
	ID         uuid.UUID          `json:"id"`
	UserID     uuid.UUID          `json:"user_id"`
	Role       UserRole           `json:"role"`
	IsActive   bool               `json:"is_active"`
	AssignedBy pgtype.UUID        `json:"assigned_by"`
	AssignedAt pgtype.Timestamptz `json:"assigned_at"`
	RevokedAt  pgtype.Timestamptz `json:"revoked_at"`
}
