// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: profile_update_requests.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createProfileUpdateRequest = `-- name: CreateProfileUpdateRequest :one
INSERT INTO profile_update_requests (
    student_id, field_name, old_value, new_value, status
) VALUES (
    $1, $2, $3, $4, $5
) RETURNING id, student_id, field_name, old_value, new_value, status, approved_by, approved_at, rejection_reason, created_at
`

type CreateProfileUpdateRequestParams struct {
	StudentID uuid.UUID `json:"student_id"`
	FieldName string    `json:"field_name"`
	OldValue  *string   `json:"old_value"`
	NewValue  string    `json:"new_value"`
	Status    string    `json:"status"`
}

func (q *Queries) CreateProfileUpdateRequest(ctx context.Context, arg CreateProfileUpdateRequestParams) (ProfileUpdateRequest, error) {
	row := q.db.QueryRow(ctx, createProfileUpdateRequest,
		arg.StudentID,
		arg.FieldName,
		arg.OldValue,
		arg.NewValue,
		arg.Status,
	)
	var i ProfileUpdateRequest
	err := row.Scan(
		&i.ID,
		&i.StudentID,
		&i.FieldName,
		&i.OldValue,
		&i.NewValue,
		&i.Status,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.RejectionReason,
		&i.CreatedAt,
	)
	return i, err
}

const deleteProfileUpdateRequest = `-- name: DeleteProfileUpdateRequest :exec
DELETE FROM profile_update_requests
WHERE id = $1
`

func (q *Queries) DeleteProfileUpdateRequest(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteProfileUpdateRequest, id)
	return err
}

const getProfileUpdateRequest = `-- name: GetProfileUpdateRequest :one
SELECT id, student_id, field_name, old_value, new_value, status, approved_by, approved_at, rejection_reason, created_at FROM profile_update_requests
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetProfileUpdateRequest(ctx context.Context, id uuid.UUID) (ProfileUpdateRequest, error) {
	row := q.db.QueryRow(ctx, getProfileUpdateRequest, id)
	var i ProfileUpdateRequest
	err := row.Scan(
		&i.ID,
		&i.StudentID,
		&i.FieldName,
		&i.OldValue,
		&i.NewValue,
		&i.Status,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.RejectionReason,
		&i.CreatedAt,
	)
	return i, err
}

const listPendingProfileUpdateRequests = `-- name: ListPendingProfileUpdateRequests :many
SELECT id, student_id, field_name, old_value, new_value, status, approved_by, approved_at, rejection_reason, created_at FROM profile_update_requests
WHERE status = 'pending'
ORDER BY created_at ASC
LIMIT $1 OFFSET $2
`

type ListPendingProfileUpdateRequestsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListPendingProfileUpdateRequests(ctx context.Context, arg ListPendingProfileUpdateRequestsParams) ([]ProfileUpdateRequest, error) {
	rows, err := q.db.Query(ctx, listPendingProfileUpdateRequests, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProfileUpdateRequest{}
	for rows.Next() {
		var i ProfileUpdateRequest
		if err := rows.Scan(
			&i.ID,
			&i.StudentID,
			&i.FieldName,
			&i.OldValue,
			&i.NewValue,
			&i.Status,
			&i.ApprovedBy,
			&i.ApprovedAt,
			&i.RejectionReason,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStudentProfileUpdateRequests = `-- name: ListStudentProfileUpdateRequests :many
SELECT id, student_id, field_name, old_value, new_value, status, approved_by, approved_at, rejection_reason, created_at FROM profile_update_requests
WHERE student_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListStudentProfileUpdateRequests(ctx context.Context, studentID uuid.UUID) ([]ProfileUpdateRequest, error) {
	rows, err := q.db.Query(ctx, listStudentProfileUpdateRequests, studentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProfileUpdateRequest{}
	for rows.Next() {
		var i ProfileUpdateRequest
		if err := rows.Scan(
			&i.ID,
			&i.StudentID,
			&i.FieldName,
			&i.OldValue,
			&i.NewValue,
			&i.Status,
			&i.ApprovedBy,
			&i.ApprovedAt,
			&i.RejectionReason,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProfileUpdateRequestStatus = `-- name: UpdateProfileUpdateRequestStatus :one
UPDATE profile_update_requests
SET
    status = $2,
    approved_by = $3,
    approved_at = $4,
    rejection_reason = $5
WHERE id = $1
RETURNING id, student_id, field_name, old_value, new_value, status, approved_by, approved_at, rejection_reason, created_at
`

type UpdateProfileUpdateRequestStatusParams struct {
	ID              uuid.UUID          `json:"id"`
	Status          string             `json:"status"`
	ApprovedBy      pgtype.UUID        `json:"approved_by"`
	ApprovedAt      pgtype.Timestamptz `json:"approved_at"`
	RejectionReason *string            `json:"rejection_reason"`
}

func (q *Queries) UpdateProfileUpdateRequestStatus(ctx context.Context, arg UpdateProfileUpdateRequestStatusParams) (ProfileUpdateRequest, error) {
	row := q.db.QueryRow(ctx, updateProfileUpdateRequestStatus,
		arg.ID,
		arg.Status,
		arg.ApprovedBy,
		arg.ApprovedAt,
		arg.RejectionReason,
	)
	var i ProfileUpdateRequest
	err := row.Scan(
		&i.ID,
		&i.StudentID,
		&i.FieldName,
		&i.OldValue,
		&i.NewValue,
		&i.Status,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.RejectionReason,
		&i.CreatedAt,
	)
	return i, err
}
