// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: semesters.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createSemester = `-- name: CreateSemester :one
INSERT INTO semesters (
    session_id, name, start_date, end_date, registration_deadline
) VALUES (
    $1, $2, $3, $4, $5
) RETURNING id, session_id, name, start_date, end_date, registration_deadline, is_active
`

type CreateSemesterParams struct {
	SessionID            uuid.UUID          `json:"session_id"`
	Name                 SemesterSeason     `json:"name"`
	StartDate            pgtype.Timestamptz `json:"start_date"`
	EndDate              pgtype.Timestamptz `json:"end_date"`
	RegistrationDeadline pgtype.Timestamptz `json:"registration_deadline"`
}

func (q *Queries) CreateSemester(ctx context.Context, arg CreateSemesterParams) (Semester, error) {
	row := q.db.QueryRow(ctx, createSemester,
		arg.SessionID,
		arg.Name,
		arg.StartDate,
		arg.EndDate,
		arg.RegistrationDeadline,
	)
	var i Semester
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Name,
		&i.StartDate,
		&i.EndDate,
		&i.RegistrationDeadline,
		&i.IsActive,
	)
	return i, err
}

const deleteSemester = `-- name: DeleteSemester :exec
DELETE FROM semesters
WHERE id = $1
`

func (q *Queries) DeleteSemester(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteSemester, id)
	return err
}

const getActiveSemester = `-- name: GetActiveSemester :one
SELECT id, session_id, name, start_date, end_date, registration_deadline, is_active FROM semesters
WHERE is_active = true LIMIT 1
`

func (q *Queries) GetActiveSemester(ctx context.Context) (Semester, error) {
	row := q.db.QueryRow(ctx, getActiveSemester)
	var i Semester
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Name,
		&i.StartDate,
		&i.EndDate,
		&i.RegistrationDeadline,
		&i.IsActive,
	)
	return i, err
}

const getSemester = `-- name: GetSemester :one
SELECT id, session_id, name, start_date, end_date, registration_deadline, is_active FROM semesters
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetSemester(ctx context.Context, id uuid.UUID) (Semester, error) {
	row := q.db.QueryRow(ctx, getSemester, id)
	var i Semester
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Name,
		&i.StartDate,
		&i.EndDate,
		&i.RegistrationDeadline,
		&i.IsActive,
	)
	return i, err
}

const listSessionSemesters = `-- name: ListSessionSemesters :many
SELECT id, session_id, name, start_date, end_date, registration_deadline, is_active FROM semesters
WHERE session_id = $1
ORDER BY start_date DESC
`

func (q *Queries) ListSessionSemesters(ctx context.Context, sessionID uuid.UUID) ([]Semester, error) {
	rows, err := q.db.Query(ctx, listSessionSemesters, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Semester{}
	for rows.Next() {
		var i Semester
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.Name,
			&i.StartDate,
			&i.EndDate,
			&i.RegistrationDeadline,
			&i.IsActive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSemester = `-- name: UpdateSemester :one
UPDATE semesters
SET
    session_id = $2,
    name = $3,
    start_date = $4,
    end_date = $5,
    registration_deadline = $6,
    is_active = $7
WHERE id = $1
RETURNING id, session_id, name, start_date, end_date, registration_deadline, is_active
`

type UpdateSemesterParams struct {
	ID                   uuid.UUID          `json:"id"`
	SessionID            uuid.UUID          `json:"session_id"`
	Name                 SemesterSeason     `json:"name"`
	StartDate            pgtype.Timestamptz `json:"start_date"`
	EndDate              pgtype.Timestamptz `json:"end_date"`
	RegistrationDeadline pgtype.Timestamptz `json:"registration_deadline"`
	IsActive             bool               `json:"is_active"`
}

func (q *Queries) UpdateSemester(ctx context.Context, arg UpdateSemesterParams) (Semester, error) {
	row := q.db.QueryRow(ctx, updateSemester,
		arg.ID,
		arg.SessionID,
		arg.Name,
		arg.StartDate,
		arg.EndDate,
		arg.RegistrationDeadline,
		arg.IsActive,
	)
	var i Semester
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Name,
		&i.StartDate,
		&i.EndDate,
		&i.RegistrationDeadline,
		&i.IsActive,
	)
	return i, err
}
