// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: skills_trade.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

const createSkillCategory = `-- name: CreateSkillCategory :one

INSERT INTO skill_categories (name, description, icon) VALUES ($1, $2, $3) RETURNING id, name, description, icon, is_active, created_at
`

type CreateSkillCategoryParams struct {
	Name        string  `json:"name"`
	Description *string `json:"description"`
	Icon        *string `json:"icon"`
}

// ==================== SKILL CATEGORIES ====================
func (q *Queries) CreateSkillCategory(ctx context.Context, arg CreateSkillCategoryParams) (SkillCategory, error) {
	row := q.db.QueryRow(ctx, createSkillCategory, arg.Name, arg.Description, arg.Icon)
	var i SkillCategory
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Icon,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const createSkillListing = `-- name: CreateSkillListing :one

INSERT INTO skill_listings (
    user_id, category_id, title, description, skill_level, price, is_free, barter_available, barter_description, portfolio_url
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10) RETURNING id, user_id, category_id, title, description, skill_level, price, is_free, barter_available, barter_description, portfolio_url, is_active, created_at, updated_at
`

type CreateSkillListingParams struct {
	UserID            uuid.UUID      `json:"user_id"`
	CategoryID        uuid.UUID      `json:"category_id"`
	Title             string         `json:"title"`
	Description       *string        `json:"description"`
	SkillLevel        SkillLevel     `json:"skill_level"`
	Price             pgtype.Numeric `json:"price"`
	IsFree            bool           `json:"is_free"`
	BarterAvailable   bool           `json:"barter_available"`
	BarterDescription *string        `json:"barter_description"`
	PortfolioUrl      *string        `json:"portfolio_url"`
}

// ==================== SKILL LISTINGS ====================
func (q *Queries) CreateSkillListing(ctx context.Context, arg CreateSkillListingParams) (SkillListing, error) {
	row := q.db.QueryRow(ctx, createSkillListing,
		arg.UserID,
		arg.CategoryID,
		arg.Title,
		arg.Description,
		arg.SkillLevel,
		arg.Price,
		arg.IsFree,
		arg.BarterAvailable,
		arg.BarterDescription,
		arg.PortfolioUrl,
	)
	var i SkillListing
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CategoryID,
		&i.Title,
		&i.Description,
		&i.SkillLevel,
		&i.Price,
		&i.IsFree,
		&i.BarterAvailable,
		&i.BarterDescription,
		&i.PortfolioUrl,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createSkillRating = `-- name: CreateSkillRating :one

INSERT INTO skill_ratings (trade_id, rater_id, rated_user_id, rating, review)
VALUES ($1, $2, $3, $4, $5) RETURNING id, trade_id, rater_id, rated_user_id, rating, review, created_at
`

type CreateSkillRatingParams struct {
	TradeID     uuid.UUID `json:"trade_id"`
	RaterID     uuid.UUID `json:"rater_id"`
	RatedUserID uuid.UUID `json:"rated_user_id"`
	Rating      int32     `json:"rating"`
	Review      *string   `json:"review"`
}

// ==================== SKILL RATINGS ====================
func (q *Queries) CreateSkillRating(ctx context.Context, arg CreateSkillRatingParams) (SkillRating, error) {
	row := q.db.QueryRow(ctx, createSkillRating,
		arg.TradeID,
		arg.RaterID,
		arg.RatedUserID,
		arg.Rating,
		arg.Review,
	)
	var i SkillRating
	err := row.Scan(
		&i.ID,
		&i.TradeID,
		&i.RaterID,
		&i.RatedUserID,
		&i.Rating,
		&i.Review,
		&i.CreatedAt,
	)
	return i, err
}

const createTradeOffer = `-- name: CreateTradeOffer :one

INSERT INTO trade_offers (from_user_id, to_user_id, offered_skill_id, requested_skill_id, message, price_offered, is_barter)
VALUES ($1, $2, $3, $4, $5, $6, $7) RETURNING id, from_user_id, to_user_id, offered_skill_id, requested_skill_id, status, message, price_offered, is_barter, responded_at, completed_at, created_at
`

type CreateTradeOfferParams struct {
	FromUserID       uuid.UUID      `json:"from_user_id"`
	ToUserID         uuid.UUID      `json:"to_user_id"`
	OfferedSkillID   uuid.UUID      `json:"offered_skill_id"`
	RequestedSkillID pgtype.UUID    `json:"requested_skill_id"`
	Message          *string        `json:"message"`
	PriceOffered     pgtype.Numeric `json:"price_offered"`
	IsBarter         bool           `json:"is_barter"`
}

// ==================== TRADE OFFERS ====================
func (q *Queries) CreateTradeOffer(ctx context.Context, arg CreateTradeOfferParams) (TradeOffer, error) {
	row := q.db.QueryRow(ctx, createTradeOffer,
		arg.FromUserID,
		arg.ToUserID,
		arg.OfferedSkillID,
		arg.RequestedSkillID,
		arg.Message,
		arg.PriceOffered,
		arg.IsBarter,
	)
	var i TradeOffer
	err := row.Scan(
		&i.ID,
		&i.FromUserID,
		&i.ToUserID,
		&i.OfferedSkillID,
		&i.RequestedSkillID,
		&i.Status,
		&i.Message,
		&i.PriceOffered,
		&i.IsBarter,
		&i.RespondedAt,
		&i.CompletedAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteSkillListing = `-- name: DeleteSkillListing :exec
UPDATE skill_listings SET is_active = false, updated_at = NOW() WHERE id = $1
`

func (q *Queries) DeleteSkillListing(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteSkillListing, id)
	return err
}

const getSkillCategory = `-- name: GetSkillCategory :one
SELECT id, name, description, icon, is_active, created_at FROM skill_categories WHERE id = $1 LIMIT 1
`

func (q *Queries) GetSkillCategory(ctx context.Context, id uuid.UUID) (SkillCategory, error) {
	row := q.db.QueryRow(ctx, getSkillCategory, id)
	var i SkillCategory
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Icon,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const getSkillListing = `-- name: GetSkillListing :one
SELECT sl.id, sl.user_id, sl.category_id, sl.title, sl.description, sl.skill_level, sl.price, sl.is_free, sl.barter_available, sl.barter_description, sl.portfolio_url, sl.is_active, sl.created_at, sl.updated_at, sc.name AS category_name, u.full_name AS owner_name, u.avatar_url AS owner_avatar
FROM skill_listings sl
JOIN skill_categories sc ON sl.category_id = sc.id
JOIN users u ON sl.user_id = u.id
WHERE sl.id = $1 LIMIT 1
`

type GetSkillListingRow struct {
	ID                uuid.UUID          `json:"id"`
	UserID            uuid.UUID          `json:"user_id"`
	CategoryID        uuid.UUID          `json:"category_id"`
	Title             string             `json:"title"`
	Description       *string            `json:"description"`
	SkillLevel        SkillLevel         `json:"skill_level"`
	Price             pgtype.Numeric     `json:"price"`
	IsFree            bool               `json:"is_free"`
	BarterAvailable   bool               `json:"barter_available"`
	BarterDescription *string            `json:"barter_description"`
	PortfolioUrl      *string            `json:"portfolio_url"`
	IsActive          bool               `json:"is_active"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	CategoryName      string             `json:"category_name"`
	OwnerName         string             `json:"owner_name"`
	OwnerAvatar       *string            `json:"owner_avatar"`
}

func (q *Queries) GetSkillListing(ctx context.Context, id uuid.UUID) (GetSkillListingRow, error) {
	row := q.db.QueryRow(ctx, getSkillListing, id)
	var i GetSkillListingRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CategoryID,
		&i.Title,
		&i.Description,
		&i.SkillLevel,
		&i.Price,
		&i.IsFree,
		&i.BarterAvailable,
		&i.BarterDescription,
		&i.PortfolioUrl,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CategoryName,
		&i.OwnerName,
		&i.OwnerAvatar,
	)
	return i, err
}

const getTradeOffer = `-- name: GetTradeOffer :one
SELECT id, from_user_id, to_user_id, offered_skill_id, requested_skill_id, status, message, price_offered, is_barter, responded_at, completed_at, created_at FROM trade_offers WHERE id = $1 LIMIT 1
`

func (q *Queries) GetTradeOffer(ctx context.Context, id uuid.UUID) (TradeOffer, error) {
	row := q.db.QueryRow(ctx, getTradeOffer, id)
	var i TradeOffer
	err := row.Scan(
		&i.ID,
		&i.FromUserID,
		&i.ToUserID,
		&i.OfferedSkillID,
		&i.RequestedSkillID,
		&i.Status,
		&i.Message,
		&i.PriceOffered,
		&i.IsBarter,
		&i.RespondedAt,
		&i.CompletedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getUserReputation = `-- name: GetUserReputation :one

SELECT id, user_id, total_ratings, average_rating, total_trades_completed, reputation_score, updated_at FROM user_reputation WHERE user_id = $1 LIMIT 1
`

// ==================== USER REPUTATION ====================
func (q *Queries) GetUserReputation(ctx context.Context, userID uuid.UUID) (UserReputation, error) {
	row := q.db.QueryRow(ctx, getUserReputation, userID)
	var i UserReputation
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TotalRatings,
		&i.AverageRating,
		&i.TotalTradesCompleted,
		&i.ReputationScore,
		&i.UpdatedAt,
	)
	return i, err
}

const listSkillCategories = `-- name: ListSkillCategories :many
SELECT id, name, description, icon, is_active, created_at FROM skill_categories WHERE is_active = true ORDER BY name
`

func (q *Queries) ListSkillCategories(ctx context.Context) ([]SkillCategory, error) {
	rows, err := q.db.Query(ctx, listSkillCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SkillCategory{}
	for rows.Next() {
		var i SkillCategory
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Icon,
			&i.IsActive,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSkillListings = `-- name: ListSkillListings :many
SELECT sl.id, sl.user_id, sl.category_id, sl.title, sl.description, sl.skill_level, sl.price, sl.is_free, sl.barter_available, sl.barter_description, sl.portfolio_url, sl.is_active, sl.created_at, sl.updated_at, sc.name AS category_name, u.full_name AS owner_name, u.avatar_url AS owner_avatar
FROM skill_listings sl
JOIN skill_categories sc ON sl.category_id = sc.id
JOIN users u ON sl.user_id = u.id
WHERE sl.is_active = true
ORDER BY sl.created_at DESC
LIMIT $1 OFFSET $2
`

type ListSkillListingsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListSkillListingsRow struct {
	ID                uuid.UUID          `json:"id"`
	UserID            uuid.UUID          `json:"user_id"`
	CategoryID        uuid.UUID          `json:"category_id"`
	Title             string             `json:"title"`
	Description       *string            `json:"description"`
	SkillLevel        SkillLevel         `json:"skill_level"`
	Price             pgtype.Numeric     `json:"price"`
	IsFree            bool               `json:"is_free"`
	BarterAvailable   bool               `json:"barter_available"`
	BarterDescription *string            `json:"barter_description"`
	PortfolioUrl      *string            `json:"portfolio_url"`
	IsActive          bool               `json:"is_active"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	CategoryName      string             `json:"category_name"`
	OwnerName         string             `json:"owner_name"`
	OwnerAvatar       *string            `json:"owner_avatar"`
}

func (q *Queries) ListSkillListings(ctx context.Context, arg ListSkillListingsParams) ([]ListSkillListingsRow, error) {
	rows, err := q.db.Query(ctx, listSkillListings, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSkillListingsRow{}
	for rows.Next() {
		var i ListSkillListingsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CategoryID,
			&i.Title,
			&i.Description,
			&i.SkillLevel,
			&i.Price,
			&i.IsFree,
			&i.BarterAvailable,
			&i.BarterDescription,
			&i.PortfolioUrl,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CategoryName,
			&i.OwnerName,
			&i.OwnerAvatar,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserSkillListings = `-- name: ListUserSkillListings :many
SELECT sl.id, sl.user_id, sl.category_id, sl.title, sl.description, sl.skill_level, sl.price, sl.is_free, sl.barter_available, sl.barter_description, sl.portfolio_url, sl.is_active, sl.created_at, sl.updated_at, sc.name AS category_name
FROM skill_listings sl
JOIN skill_categories sc ON sl.category_id = sc.id
WHERE sl.user_id = $1 AND sl.is_active = true
ORDER BY sl.created_at DESC
`

type ListUserSkillListingsRow struct {
	ID                uuid.UUID          `json:"id"`
	UserID            uuid.UUID          `json:"user_id"`
	CategoryID        uuid.UUID          `json:"category_id"`
	Title             string             `json:"title"`
	Description       *string            `json:"description"`
	SkillLevel        SkillLevel         `json:"skill_level"`
	Price             pgtype.Numeric     `json:"price"`
	IsFree            bool               `json:"is_free"`
	BarterAvailable   bool               `json:"barter_available"`
	BarterDescription *string            `json:"barter_description"`
	PortfolioUrl      *string            `json:"portfolio_url"`
	IsActive          bool               `json:"is_active"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	CategoryName      string             `json:"category_name"`
}

func (q *Queries) ListUserSkillListings(ctx context.Context, userID uuid.UUID) ([]ListUserSkillListingsRow, error) {
	rows, err := q.db.Query(ctx, listUserSkillListings, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUserSkillListingsRow{}
	for rows.Next() {
		var i ListUserSkillListingsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CategoryID,
			&i.Title,
			&i.Description,
			&i.SkillLevel,
			&i.Price,
			&i.IsFree,
			&i.BarterAvailable,
			&i.BarterDescription,
			&i.PortfolioUrl,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CategoryName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserSkillRatings = `-- name: ListUserSkillRatings :many
SELECT sr.id, sr.trade_id, sr.rater_id, sr.rated_user_id, sr.rating, sr.review, sr.created_at, u.full_name AS rater_name
FROM skill_ratings sr JOIN users u ON sr.rater_id = u.id
WHERE sr.rated_user_id = $1
ORDER BY sr.created_at DESC LIMIT $2 OFFSET $3
`

type ListUserSkillRatingsParams struct {
	RatedUserID uuid.UUID `json:"rated_user_id"`
	Limit       int32     `json:"limit"`
	Offset      int32     `json:"offset"`
}

type ListUserSkillRatingsRow struct {
	ID          uuid.UUID          `json:"id"`
	TradeID     uuid.UUID          `json:"trade_id"`
	RaterID     uuid.UUID          `json:"rater_id"`
	RatedUserID uuid.UUID          `json:"rated_user_id"`
	Rating      int32              `json:"rating"`
	Review      *string            `json:"review"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	RaterName   string             `json:"rater_name"`
}

func (q *Queries) ListUserSkillRatings(ctx context.Context, arg ListUserSkillRatingsParams) ([]ListUserSkillRatingsRow, error) {
	rows, err := q.db.Query(ctx, listUserSkillRatings, arg.RatedUserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUserSkillRatingsRow{}
	for rows.Next() {
		var i ListUserSkillRatingsRow
		if err := rows.Scan(
			&i.ID,
			&i.TradeID,
			&i.RaterID,
			&i.RatedUserID,
			&i.Rating,
			&i.Review,
			&i.CreatedAt,
			&i.RaterName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserTradeOffers = `-- name: ListUserTradeOffers :many
SELECT id, from_user_id, to_user_id, offered_skill_id, requested_skill_id, status, message, price_offered, is_barter, responded_at, completed_at, created_at FROM trade_offers
WHERE from_user_id = $1 OR to_user_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListUserTradeOffersParams struct {
	FromUserID uuid.UUID `json:"from_user_id"`
	Limit      int32     `json:"limit"`
	Offset     int32     `json:"offset"`
}

func (q *Queries) ListUserTradeOffers(ctx context.Context, arg ListUserTradeOffersParams) ([]TradeOffer, error) {
	rows, err := q.db.Query(ctx, listUserTradeOffers, arg.FromUserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TradeOffer{}
	for rows.Next() {
		var i TradeOffer
		if err := rows.Scan(
			&i.ID,
			&i.FromUserID,
			&i.ToUserID,
			&i.OfferedSkillID,
			&i.RequestedSkillID,
			&i.Status,
			&i.Message,
			&i.PriceOffered,
			&i.IsBarter,
			&i.RespondedAt,
			&i.CompletedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSkillListing = `-- name: UpdateSkillListing :one
UPDATE skill_listings
SET title = $2, description = $3, skill_level = $4, price = $5, is_free = $6, barter_available = $7, barter_description = $8, portfolio_url = $9, is_active = $10, updated_at = NOW()
WHERE id = $1 RETURNING id, user_id, category_id, title, description, skill_level, price, is_free, barter_available, barter_description, portfolio_url, is_active, created_at, updated_at
`

type UpdateSkillListingParams struct {
	ID                uuid.UUID      `json:"id"`
	Title             string         `json:"title"`
	Description       *string        `json:"description"`
	SkillLevel        SkillLevel     `json:"skill_level"`
	Price             pgtype.Numeric `json:"price"`
	IsFree            bool           `json:"is_free"`
	BarterAvailable   bool           `json:"barter_available"`
	BarterDescription *string        `json:"barter_description"`
	PortfolioUrl      *string        `json:"portfolio_url"`
	IsActive          bool           `json:"is_active"`
}

func (q *Queries) UpdateSkillListing(ctx context.Context, arg UpdateSkillListingParams) (SkillListing, error) {
	row := q.db.QueryRow(ctx, updateSkillListing,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.SkillLevel,
		arg.Price,
		arg.IsFree,
		arg.BarterAvailable,
		arg.BarterDescription,
		arg.PortfolioUrl,
		arg.IsActive,
	)
	var i SkillListing
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CategoryID,
		&i.Title,
		&i.Description,
		&i.SkillLevel,
		&i.Price,
		&i.IsFree,
		&i.BarterAvailable,
		&i.BarterDescription,
		&i.PortfolioUrl,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTradeOfferStatus = `-- name: UpdateTradeOfferStatus :one
UPDATE trade_offers SET status = $2,
    responded_at = CASE WHEN $2 IN ('accepted', 'cancelled') THEN NOW() ELSE responded_at END,
    completed_at = CASE WHEN $2 = 'completed' THEN NOW() ELSE completed_at END
WHERE id = $1 RETURNING id, from_user_id, to_user_id, offered_skill_id, requested_skill_id, status, message, price_offered, is_barter, responded_at, completed_at, created_at
`

type UpdateTradeOfferStatusParams struct {
	ID     uuid.UUID   `json:"id"`
	Status TradeStatus `json:"status"`
}

func (q *Queries) UpdateTradeOfferStatus(ctx context.Context, arg UpdateTradeOfferStatusParams) (TradeOffer, error) {
	row := q.db.QueryRow(ctx, updateTradeOfferStatus, arg.ID, arg.Status)
	var i TradeOffer
	err := row.Scan(
		&i.ID,
		&i.FromUserID,
		&i.ToUserID,
		&i.OfferedSkillID,
		&i.RequestedSkillID,
		&i.Status,
		&i.Message,
		&i.PriceOffered,
		&i.IsBarter,
		&i.RespondedAt,
		&i.CompletedAt,
		&i.CreatedAt,
	)
	return i, err
}

const upsertUserReputation = `-- name: UpsertUserReputation :one
INSERT INTO user_reputation (user_id, total_ratings, average_rating, total_trades_completed, reputation_score)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (user_id) DO UPDATE
SET total_ratings = $2, average_rating = $3, total_trades_completed = $4, reputation_score = $5, updated_at = NOW()
RETURNING id, user_id, total_ratings, average_rating, total_trades_completed, reputation_score, updated_at
`

type UpsertUserReputationParams struct {
	UserID               uuid.UUID       `json:"user_id"`
	TotalRatings         int32           `json:"total_ratings"`
	AverageRating        decimal.Decimal `json:"average_rating"`
	TotalTradesCompleted int32           `json:"total_trades_completed"`
	ReputationScore      decimal.Decimal `json:"reputation_score"`
}

func (q *Queries) UpsertUserReputation(ctx context.Context, arg UpsertUserReputationParams) (UserReputation, error) {
	row := q.db.QueryRow(ctx, upsertUserReputation,
		arg.UserID,
		arg.TotalRatings,
		arg.AverageRating,
		arg.TotalTradesCompleted,
		arg.ReputationScore,
	)
	var i UserReputation
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TotalRatings,
		&i.AverageRating,
		&i.TotalTradesCompleted,
		&i.ReputationScore,
		&i.UpdatedAt,
	)
	return i, err
}
