// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: staff.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createStaff = `-- name: CreateStaff :one
INSERT INTO staff (
    user_id, staff_id, department, rank, specialization, employment_date
) VALUES (
    $1, $2, $3, $4, $5, $6
) RETURNING id, user_id, staff_id, department, rank, specialization, employment_date, created_at
`

type CreateStaffParams struct {
	UserID         uuid.UUID          `json:"user_id"`
	StaffID        string             `json:"staff_id"`
	Department     string             `json:"department"`
	Rank           *string            `json:"rank"`
	Specialization *string            `json:"specialization"`
	EmploymentDate pgtype.Timestamptz `json:"employment_date"`
}

func (q *Queries) CreateStaff(ctx context.Context, arg CreateStaffParams) (Staff, error) {
	row := q.db.QueryRow(ctx, createStaff,
		arg.UserID,
		arg.StaffID,
		arg.Department,
		arg.Rank,
		arg.Specialization,
		arg.EmploymentDate,
	)
	var i Staff
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.StaffID,
		&i.Department,
		&i.Rank,
		&i.Specialization,
		&i.EmploymentDate,
		&i.CreatedAt,
	)
	return i, err
}

const deleteStaff = `-- name: DeleteStaff :exec
DELETE FROM staff
WHERE id = $1
`

func (q *Queries) DeleteStaff(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteStaff, id)
	return err
}

const getStaff = `-- name: GetStaff :one
SELECT id, user_id, staff_id, department, rank, specialization, employment_date, created_at FROM staff
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetStaff(ctx context.Context, id uuid.UUID) (Staff, error) {
	row := q.db.QueryRow(ctx, getStaff, id)
	var i Staff
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.StaffID,
		&i.Department,
		&i.Rank,
		&i.Specialization,
		&i.EmploymentDate,
		&i.CreatedAt,
	)
	return i, err
}

const getStaffByStaffID = `-- name: GetStaffByStaffID :one
SELECT id, user_id, staff_id, department, rank, specialization, employment_date, created_at FROM staff
WHERE staff_id = $1 LIMIT 1
`

func (q *Queries) GetStaffByStaffID(ctx context.Context, staffID string) (Staff, error) {
	row := q.db.QueryRow(ctx, getStaffByStaffID, staffID)
	var i Staff
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.StaffID,
		&i.Department,
		&i.Rank,
		&i.Specialization,
		&i.EmploymentDate,
		&i.CreatedAt,
	)
	return i, err
}

const getStaffByUserID = `-- name: GetStaffByUserID :one
SELECT id, user_id, staff_id, department, rank, specialization, employment_date, created_at FROM staff
WHERE user_id = $1 LIMIT 1
`

func (q *Queries) GetStaffByUserID(ctx context.Context, userID uuid.UUID) (Staff, error) {
	row := q.db.QueryRow(ctx, getStaffByUserID, userID)
	var i Staff
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.StaffID,
		&i.Department,
		&i.Rank,
		&i.Specialization,
		&i.EmploymentDate,
		&i.CreatedAt,
	)
	return i, err
}

const listStaff = `-- name: ListStaff :many
SELECT id, user_id, staff_id, department, rank, specialization, employment_date, created_at FROM staff
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListStaffParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListStaff(ctx context.Context, arg ListStaffParams) ([]Staff, error) {
	rows, err := q.db.Query(ctx, listStaff, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Staff{}
	for rows.Next() {
		var i Staff
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.StaffID,
			&i.Department,
			&i.Rank,
			&i.Specialization,
			&i.EmploymentDate,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateStaff = `-- name: UpdateStaff :one
UPDATE staff
SET
    department = $2,
    rank = $3,
    specialization = $4,
    employment_date = COALESCE($5, employment_date)
WHERE id = $1
RETURNING id, user_id, staff_id, department, rank, specialization, employment_date, created_at
`

type UpdateStaffParams struct {
	ID             uuid.UUID          `json:"id"`
	Department     string             `json:"department"`
	Rank           *string            `json:"rank"`
	Specialization *string            `json:"specialization"`
	EmploymentDate pgtype.Timestamptz `json:"employment_date"`
}

func (q *Queries) UpdateStaff(ctx context.Context, arg UpdateStaffParams) (Staff, error) {
	row := q.db.QueryRow(ctx, updateStaff,
		arg.ID,
		arg.Department,
		arg.Rank,
		arg.Specialization,
		arg.EmploymentDate,
	)
	var i Staff
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.StaffID,
		&i.Department,
		&i.Rank,
		&i.Specialization,
		&i.EmploymentDate,
		&i.CreatedAt,
	)
	return i, err
}
