// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: students.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createStudent = `-- name: CreateStudent :one
INSERT INTO students (
    user_id, matric_number, level, entry_year, current_session_id, current_semester
) VALUES (
    $1, $2, $3, $4, $5, $6
) RETURNING id, user_id, matric_number, level, entry_year, current_session_id, current_semester, cgpa, total_credits_earned, total_credits_required, academic_standing, graduation_status, is_defaulter, defaulter_reason, created_at, updated_at
`

type CreateStudentParams struct {
	UserID           uuid.UUID          `json:"user_id"`
	MatricNumber     string             `json:"matric_number"`
	Level            int32              `json:"level"`
	EntryYear        int32              `json:"entry_year"`
	CurrentSessionID pgtype.UUID        `json:"current_session_id"`
	CurrentSemester  NullSemesterSeason `json:"current_semester"`
}

func (q *Queries) CreateStudent(ctx context.Context, arg CreateStudentParams) (Student, error) {
	row := q.db.QueryRow(ctx, createStudent,
		arg.UserID,
		arg.MatricNumber,
		arg.Level,
		arg.EntryYear,
		arg.CurrentSessionID,
		arg.CurrentSemester,
	)
	var i Student
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.MatricNumber,
		&i.Level,
		&i.EntryYear,
		&i.CurrentSessionID,
		&i.CurrentSemester,
		&i.Cgpa,
		&i.TotalCreditsEarned,
		&i.TotalCreditsRequired,
		&i.AcademicStanding,
		&i.GraduationStatus,
		&i.IsDefaulter,
		&i.DefaulterReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getStudent = `-- name: GetStudent :one
SELECT id, user_id, matric_number, level, entry_year, current_session_id, current_semester, cgpa, total_credits_earned, total_credits_required, academic_standing, graduation_status, is_defaulter, defaulter_reason, created_at, updated_at FROM students
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetStudent(ctx context.Context, id uuid.UUID) (Student, error) {
	row := q.db.QueryRow(ctx, getStudent, id)
	var i Student
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.MatricNumber,
		&i.Level,
		&i.EntryYear,
		&i.CurrentSessionID,
		&i.CurrentSemester,
		&i.Cgpa,
		&i.TotalCreditsEarned,
		&i.TotalCreditsRequired,
		&i.AcademicStanding,
		&i.GraduationStatus,
		&i.IsDefaulter,
		&i.DefaulterReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getStudentByMatric = `-- name: GetStudentByMatric :one
SELECT id, user_id, matric_number, level, entry_year, current_session_id, current_semester, cgpa, total_credits_earned, total_credits_required, academic_standing, graduation_status, is_defaulter, defaulter_reason, created_at, updated_at FROM students
WHERE matric_number = $1 LIMIT 1
`

func (q *Queries) GetStudentByMatric(ctx context.Context, matricNumber string) (Student, error) {
	row := q.db.QueryRow(ctx, getStudentByMatric, matricNumber)
	var i Student
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.MatricNumber,
		&i.Level,
		&i.EntryYear,
		&i.CurrentSessionID,
		&i.CurrentSemester,
		&i.Cgpa,
		&i.TotalCreditsEarned,
		&i.TotalCreditsRequired,
		&i.AcademicStanding,
		&i.GraduationStatus,
		&i.IsDefaulter,
		&i.DefaulterReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getStudentByUserId = `-- name: GetStudentByUserId :one
SELECT id, user_id, matric_number, level, entry_year, current_session_id, current_semester, cgpa, total_credits_earned, total_credits_required, academic_standing, graduation_status, is_defaulter, defaulter_reason, created_at, updated_at FROM students
WHERE user_id = $1 LIMIT 1
`

func (q *Queries) GetStudentByUserId(ctx context.Context, userID uuid.UUID) (Student, error) {
	row := q.db.QueryRow(ctx, getStudentByUserId, userID)
	var i Student
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.MatricNumber,
		&i.Level,
		&i.EntryYear,
		&i.CurrentSessionID,
		&i.CurrentSemester,
		&i.Cgpa,
		&i.TotalCreditsEarned,
		&i.TotalCreditsRequired,
		&i.AcademicStanding,
		&i.GraduationStatus,
		&i.IsDefaulter,
		&i.DefaulterReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listStudents = `-- name: ListStudents :many
SELECT id, user_id, matric_number, level, entry_year, current_session_id, current_semester, cgpa, total_credits_earned, total_credits_required, academic_standing, graduation_status, is_defaulter, defaulter_reason, created_at, updated_at FROM students
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListStudentsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListStudents(ctx context.Context, arg ListStudentsParams) ([]Student, error) {
	rows, err := q.db.Query(ctx, listStudents, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Student{}
	for rows.Next() {
		var i Student
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.MatricNumber,
			&i.Level,
			&i.EntryYear,
			&i.CurrentSessionID,
			&i.CurrentSemester,
			&i.Cgpa,
			&i.TotalCreditsEarned,
			&i.TotalCreditsRequired,
			&i.AcademicStanding,
			&i.GraduationStatus,
			&i.IsDefaulter,
			&i.DefaulterReason,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateStudentAcademicRecord = `-- name: UpdateStudentAcademicRecord :one
UPDATE students
SET
    cgpa = $2,
    total_credits_earned = $3,
    academic_standing = $4,
    graduation_status = $5,
    updated_at = NOW()
WHERE id = $1
RETURNING id, user_id, matric_number, level, entry_year, current_session_id, current_semester, cgpa, total_credits_earned, total_credits_required, academic_standing, graduation_status, is_defaulter, defaulter_reason, created_at, updated_at
`

type UpdateStudentAcademicRecordParams struct {
	ID                 uuid.UUID            `json:"id"`
	Cgpa               pgtype.Numeric       `json:"cgpa"`
	TotalCreditsEarned *int32               `json:"total_credits_earned"`
	AcademicStanding   NullAcademicStanding `json:"academic_standing"`
	GraduationStatus   *string              `json:"graduation_status"`
}

func (q *Queries) UpdateStudentAcademicRecord(ctx context.Context, arg UpdateStudentAcademicRecordParams) (Student, error) {
	row := q.db.QueryRow(ctx, updateStudentAcademicRecord,
		arg.ID,
		arg.Cgpa,
		arg.TotalCreditsEarned,
		arg.AcademicStanding,
		arg.GraduationStatus,
	)
	var i Student
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.MatricNumber,
		&i.Level,
		&i.EntryYear,
		&i.CurrentSessionID,
		&i.CurrentSemester,
		&i.Cgpa,
		&i.TotalCreditsEarned,
		&i.TotalCreditsRequired,
		&i.AcademicStanding,
		&i.GraduationStatus,
		&i.IsDefaulter,
		&i.DefaulterReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
