// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: timetable.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createTimetableEntry = `-- name: CreateTimetableEntry :one
INSERT INTO timetable (
    course_id,
    exam_date,
    start_time,
    end_time,
    venue,
    session_id,
    semester_id,
    has_conflict,
    conflict_details,
    created_by
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
) RETURNING id, course_id, exam_date, start_time, end_time, venue, session_id, semester_id, has_conflict, conflict_details, created_by, created_at
`

type CreateTimetableEntryParams struct {
	CourseID        uuid.UUID          `json:"course_id"`
	ExamDate        pgtype.Timestamptz `json:"exam_date"`
	StartTime       pgtype.Timestamptz `json:"start_time"`
	EndTime         pgtype.Timestamptz `json:"end_time"`
	Venue           string             `json:"venue"`
	SessionID       uuid.UUID          `json:"session_id"`
	SemesterID      uuid.UUID          `json:"semester_id"`
	HasConflict     bool               `json:"has_conflict"`
	ConflictDetails []byte             `json:"conflict_details"`
	CreatedBy       uuid.UUID          `json:"created_by"`
}

func (q *Queries) CreateTimetableEntry(ctx context.Context, arg CreateTimetableEntryParams) (Timetable, error) {
	row := q.db.QueryRow(ctx, createTimetableEntry,
		arg.CourseID,
		arg.ExamDate,
		arg.StartTime,
		arg.EndTime,
		arg.Venue,
		arg.SessionID,
		arg.SemesterID,
		arg.HasConflict,
		arg.ConflictDetails,
		arg.CreatedBy,
	)
	var i Timetable
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.ExamDate,
		&i.StartTime,
		&i.EndTime,
		&i.Venue,
		&i.SessionID,
		&i.SemesterID,
		&i.HasConflict,
		&i.ConflictDetails,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const deleteTimetableEntry = `-- name: DeleteTimetableEntry :exec
DELETE FROM timetable
WHERE id = $1
`

func (q *Queries) DeleteTimetableEntry(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteTimetableEntry, id)
	return err
}

const getTimetableEntry = `-- name: GetTimetableEntry :one
SELECT id, course_id, exam_date, start_time, end_time, venue, session_id, semester_id, has_conflict, conflict_details, created_by, created_at FROM timetable
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetTimetableEntry(ctx context.Context, id uuid.UUID) (Timetable, error) {
	row := q.db.QueryRow(ctx, getTimetableEntry, id)
	var i Timetable
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.ExamDate,
		&i.StartTime,
		&i.EndTime,
		&i.Venue,
		&i.SessionID,
		&i.SemesterID,
		&i.HasConflict,
		&i.ConflictDetails,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const listTimetableEntries = `-- name: ListTimetableEntries :many
SELECT id, course_id, exam_date, start_time, end_time, venue, session_id, semester_id, has_conflict, conflict_details, created_by, created_at FROM timetable
WHERE session_id = $1 AND semester_id = $2
ORDER BY exam_date, start_time
`

type ListTimetableEntriesParams struct {
	SessionID  uuid.UUID `json:"session_id"`
	SemesterID uuid.UUID `json:"semester_id"`
}

func (q *Queries) ListTimetableEntries(ctx context.Context, arg ListTimetableEntriesParams) ([]Timetable, error) {
	rows, err := q.db.Query(ctx, listTimetableEntries, arg.SessionID, arg.SemesterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Timetable{}
	for rows.Next() {
		var i Timetable
		if err := rows.Scan(
			&i.ID,
			&i.CourseID,
			&i.ExamDate,
			&i.StartTime,
			&i.EndTime,
			&i.Venue,
			&i.SessionID,
			&i.SemesterID,
			&i.HasConflict,
			&i.ConflictDetails,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTimetableEntry = `-- name: UpdateTimetableEntry :one
UPDATE timetable
SET 
    exam_date = $2,
    start_time = $3,
    end_time = $4,
    venue = $5,
    has_conflict = $6,
    conflict_details = $7
WHERE id = $1
RETURNING id, course_id, exam_date, start_time, end_time, venue, session_id, semester_id, has_conflict, conflict_details, created_by, created_at
`

type UpdateTimetableEntryParams struct {
	ID              uuid.UUID          `json:"id"`
	ExamDate        pgtype.Timestamptz `json:"exam_date"`
	StartTime       pgtype.Timestamptz `json:"start_time"`
	EndTime         pgtype.Timestamptz `json:"end_time"`
	Venue           string             `json:"venue"`
	HasConflict     bool               `json:"has_conflict"`
	ConflictDetails []byte             `json:"conflict_details"`
}

func (q *Queries) UpdateTimetableEntry(ctx context.Context, arg UpdateTimetableEntryParams) (Timetable, error) {
	row := q.db.QueryRow(ctx, updateTimetableEntry,
		arg.ID,
		arg.ExamDate,
		arg.StartTime,
		arg.EndTime,
		arg.Venue,
		arg.HasConflict,
		arg.ConflictDetails,
	)
	var i Timetable
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.ExamDate,
		&i.StartTime,
		&i.EndTime,
		&i.Venue,
		&i.SessionID,
		&i.SemesterID,
		&i.HasConflict,
		&i.ConflictDetails,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}
