// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: timetable.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createTimetableEntry = `-- name: CreateTimetableEntry :one
INSERT INTO timetable (
    course_id,
    exam_date,
    start_time,
    end_time,
    venue,
    session_id,
    semester_id,
    has_conflict,
    conflict_details,
    created_by,
    day_of_week,
    level,
    entry_type,
    class_type,
    exam_type,
    lecturer_id,
    invigilators,
    is_published
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18
) RETURNING id, course_id, exam_date, start_time, end_time, venue, session_id, semester_id, has_conflict, conflict_details, created_by, created_at, day_of_week, level, entry_type, class_type, lecturer_id, exam_type, invigilators, is_published, published_at
`

type CreateTimetableEntryParams struct {
	CourseID        uuid.UUID          `json:"course_id"`
	ExamDate        pgtype.Timestamptz `json:"exam_date"`
	StartTime       pgtype.Timestamptz `json:"start_time"`
	EndTime         pgtype.Timestamptz `json:"end_time"`
	Venue           string             `json:"venue"`
	SessionID       pgtype.UUID        `json:"session_id"`
	SemesterID      pgtype.UUID        `json:"semester_id"`
	HasConflict     bool               `json:"has_conflict"`
	ConflictDetails []byte             `json:"conflict_details"`
	CreatedBy       pgtype.UUID        `json:"created_by"`
	DayOfWeek       *int32             `json:"day_of_week"`
	Level           *int32             `json:"level"`
	EntryType       string             `json:"entry_type"`
	ClassType       *string            `json:"class_type"`
	ExamType        *string            `json:"exam_type"`
	LecturerID      pgtype.UUID        `json:"lecturer_id"`
	Invigilators    *string            `json:"invigilators"`
	IsPublished     bool               `json:"is_published"`
}

func (q *Queries) CreateTimetableEntry(ctx context.Context, arg CreateTimetableEntryParams) (Timetable, error) {
	row := q.db.QueryRow(ctx, createTimetableEntry,
		arg.CourseID,
		arg.ExamDate,
		arg.StartTime,
		arg.EndTime,
		arg.Venue,
		arg.SessionID,
		arg.SemesterID,
		arg.HasConflict,
		arg.ConflictDetails,
		arg.CreatedBy,
		arg.DayOfWeek,
		arg.Level,
		arg.EntryType,
		arg.ClassType,
		arg.ExamType,
		arg.LecturerID,
		arg.Invigilators,
		arg.IsPublished,
	)
	var i Timetable
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.ExamDate,
		&i.StartTime,
		&i.EndTime,
		&i.Venue,
		&i.SessionID,
		&i.SemesterID,
		&i.HasConflict,
		&i.ConflictDetails,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.DayOfWeek,
		&i.Level,
		&i.EntryType,
		&i.ClassType,
		&i.LecturerID,
		&i.ExamType,
		&i.Invigilators,
		&i.IsPublished,
		&i.PublishedAt,
	)
	return i, err
}

const deleteTimetableEntry = `-- name: DeleteTimetableEntry :exec
DELETE FROM timetable
WHERE id = $1
`

func (q *Queries) DeleteTimetableEntry(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteTimetableEntry, id)
	return err
}

const getTimetableEntry = `-- name: GetTimetableEntry :one
SELECT id, course_id, exam_date, start_time, end_time, venue, session_id, semester_id, has_conflict, conflict_details, created_by, created_at, day_of_week, level, entry_type, class_type, lecturer_id, exam_type, invigilators, is_published, published_at FROM timetable
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetTimetableEntry(ctx context.Context, id uuid.UUID) (Timetable, error) {
	row := q.db.QueryRow(ctx, getTimetableEntry, id)
	var i Timetable
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.ExamDate,
		&i.StartTime,
		&i.EndTime,
		&i.Venue,
		&i.SessionID,
		&i.SemesterID,
		&i.HasConflict,
		&i.ConflictDetails,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.DayOfWeek,
		&i.Level,
		&i.EntryType,
		&i.ClassType,
		&i.LecturerID,
		&i.ExamType,
		&i.Invigilators,
		&i.IsPublished,
		&i.PublishedAt,
	)
	return i, err
}

const listTimetableEntries = `-- name: ListTimetableEntries :many
SELECT id, course_id, exam_date, start_time, end_time, venue, session_id, semester_id, has_conflict, conflict_details, created_by, created_at, day_of_week, level, entry_type, class_type, lecturer_id, exam_type, invigilators, is_published, published_at FROM timetable
WHERE session_id = $1 AND semester_id = $2
ORDER BY exam_date, start_time
`

type ListTimetableEntriesParams struct {
	SessionID  pgtype.UUID `json:"session_id"`
	SemesterID pgtype.UUID `json:"semester_id"`
}

func (q *Queries) ListTimetableEntries(ctx context.Context, arg ListTimetableEntriesParams) ([]Timetable, error) {
	rows, err := q.db.Query(ctx, listTimetableEntries, arg.SessionID, arg.SemesterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Timetable{}
	for rows.Next() {
		var i Timetable
		if err := rows.Scan(
			&i.ID,
			&i.CourseID,
			&i.ExamDate,
			&i.StartTime,
			&i.EndTime,
			&i.Venue,
			&i.SessionID,
			&i.SemesterID,
			&i.HasConflict,
			&i.ConflictDetails,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.DayOfWeek,
			&i.Level,
			&i.EntryType,
			&i.ClassType,
			&i.LecturerID,
			&i.ExamType,
			&i.Invigilators,
			&i.IsPublished,
			&i.PublishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTimetableEntry = `-- name: UpdateTimetableEntry :one
UPDATE timetable
SET 
    exam_date = $2,
    start_time = $3,
    end_time = $4,
    venue = $5,
    has_conflict = $6,
    conflict_details = $7
WHERE id = $1
RETURNING id, course_id, exam_date, start_time, end_time, venue, session_id, semester_id, has_conflict, conflict_details, created_by, created_at, day_of_week, level, entry_type, class_type, lecturer_id, exam_type, invigilators, is_published, published_at
`

type UpdateTimetableEntryParams struct {
	ID              uuid.UUID          `json:"id"`
	ExamDate        pgtype.Timestamptz `json:"exam_date"`
	StartTime       pgtype.Timestamptz `json:"start_time"`
	EndTime         pgtype.Timestamptz `json:"end_time"`
	Venue           string             `json:"venue"`
	HasConflict     bool               `json:"has_conflict"`
	ConflictDetails []byte             `json:"conflict_details"`
}

func (q *Queries) UpdateTimetableEntry(ctx context.Context, arg UpdateTimetableEntryParams) (Timetable, error) {
	row := q.db.QueryRow(ctx, updateTimetableEntry,
		arg.ID,
		arg.ExamDate,
		arg.StartTime,
		arg.EndTime,
		arg.Venue,
		arg.HasConflict,
		arg.ConflictDetails,
	)
	var i Timetable
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.ExamDate,
		&i.StartTime,
		&i.EndTime,
		&i.Venue,
		&i.SessionID,
		&i.SemesterID,
		&i.HasConflict,
		&i.ConflictDetails,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.DayOfWeek,
		&i.Level,
		&i.EntryType,
		&i.ClassType,
		&i.LecturerID,
		&i.ExamType,
		&i.Invigilators,
		&i.IsPublished,
		&i.PublishedAt,
	)
	return i, err
}
