// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const approveUserStatus = `-- name: ApproveUserStatus :one
UPDATE users
SET
    is_approved = $2,
    approved_by = $3,
    approved_at = $4,
    updated_at = NOW()
WHERE id = $1
RETURNING id, email, password_hash, role, full_name, phone, avatar_url, is_active, email_verified, two_factor_enabled, last_login_at, created_at, updated_at, deleted_at, created_by_hod_id, is_approved, approved_by, approved_at, date_of_birth, emergency_contact_name, emergency_contact_phone, home_address
`

type ApproveUserStatusParams struct {
	ID         uuid.UUID          `json:"id"`
	IsApproved bool               `json:"is_approved"`
	ApprovedBy pgtype.UUID        `json:"approved_by"`
	ApprovedAt pgtype.Timestamptz `json:"approved_at"`
}

func (q *Queries) ApproveUserStatus(ctx context.Context, arg ApproveUserStatusParams) (User, error) {
	row := q.db.QueryRow(ctx, approveUserStatus,
		arg.ID,
		arg.IsApproved,
		arg.ApprovedBy,
		arg.ApprovedAt,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.FullName,
		&i.Phone,
		&i.AvatarUrl,
		&i.IsActive,
		&i.EmailVerified,
		&i.TwoFactorEnabled,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CreatedByHodID,
		&i.IsApproved,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.DateOfBirth,
		&i.EmergencyContactName,
		&i.EmergencyContactPhone,
		&i.HomeAddress,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    email, password_hash, role, full_name, phone, avatar_url, created_by_hod_id
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
) RETURNING id, email, password_hash, role, full_name, phone, avatar_url, is_active, email_verified, two_factor_enabled, last_login_at, created_at, updated_at, deleted_at, created_by_hod_id, is_approved, approved_by, approved_at, date_of_birth, emergency_contact_name, emergency_contact_phone, home_address
`

type CreateUserParams struct {
	Email          string      `json:"email"`
	PasswordHash   string      `json:"password_hash"`
	Role           UserRole    `json:"role"`
	FullName       string      `json:"full_name"`
	Phone          *string     `json:"phone"`
	AvatarUrl      *string     `json:"avatar_url"`
	CreatedByHodID pgtype.UUID `json:"created_by_hod_id"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Email,
		arg.PasswordHash,
		arg.Role,
		arg.FullName,
		arg.Phone,
		arg.AvatarUrl,
		arg.CreatedByHodID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.FullName,
		&i.Phone,
		&i.AvatarUrl,
		&i.IsActive,
		&i.EmailVerified,
		&i.TwoFactorEnabled,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CreatedByHodID,
		&i.IsApproved,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.DateOfBirth,
		&i.EmergencyContactName,
		&i.EmergencyContactPhone,
		&i.HomeAddress,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users
WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const getUser = `-- name: GetUser :one
SELECT id, email, password_hash, role, full_name, phone, avatar_url, is_active, email_verified, two_factor_enabled, last_login_at, created_at, updated_at, deleted_at, created_by_hod_id, is_approved, approved_by, approved_at, date_of_birth, emergency_contact_name, emergency_contact_phone, home_address FROM users
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetUser(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.FullName,
		&i.Phone,
		&i.AvatarUrl,
		&i.IsActive,
		&i.EmailVerified,
		&i.TwoFactorEnabled,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CreatedByHodID,
		&i.IsApproved,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.DateOfBirth,
		&i.EmergencyContactName,
		&i.EmergencyContactPhone,
		&i.HomeAddress,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password_hash, role, full_name, phone, avatar_url, is_active, email_verified, two_factor_enabled, last_login_at, created_at, updated_at, deleted_at, created_by_hod_id, is_approved, approved_by, approved_at, date_of_birth, emergency_contact_name, emergency_contact_phone, home_address FROM users
WHERE email = $1 LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.FullName,
		&i.Phone,
		&i.AvatarUrl,
		&i.IsActive,
		&i.EmailVerified,
		&i.TwoFactorEnabled,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CreatedByHodID,
		&i.IsApproved,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.DateOfBirth,
		&i.EmergencyContactName,
		&i.EmergencyContactPhone,
		&i.HomeAddress,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, email, password_hash, role, full_name, phone, avatar_url, is_active, email_verified, two_factor_enabled, last_login_at, created_at, updated_at, deleted_at, created_by_hod_id, is_approved, approved_by, approved_at, date_of_birth, emergency_contact_name, emergency_contact_phone, home_address FROM users
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListUsersParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.PasswordHash,
			&i.Role,
			&i.FullName,
			&i.Phone,
			&i.AvatarUrl,
			&i.IsActive,
			&i.EmailVerified,
			&i.TwoFactorEnabled,
			&i.LastLoginAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.CreatedByHodID,
			&i.IsApproved,
			&i.ApprovedBy,
			&i.ApprovedAt,
			&i.DateOfBirth,
			&i.EmergencyContactName,
			&i.EmergencyContactPhone,
			&i.HomeAddress,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET
    full_name = $2,
    phone = $3,
    avatar_url = $4,
    is_active = $5,
    email_verified = $6,
    two_factor_enabled = $7,
    updated_at = NOW()
WHERE id = $1
RETURNING id, email, password_hash, role, full_name, phone, avatar_url, is_active, email_verified, two_factor_enabled, last_login_at, created_at, updated_at, deleted_at, created_by_hod_id, is_approved, approved_by, approved_at, date_of_birth, emergency_contact_name, emergency_contact_phone, home_address
`

type UpdateUserParams struct {
	ID               uuid.UUID `json:"id"`
	FullName         string    `json:"full_name"`
	Phone            *string   `json:"phone"`
	AvatarUrl        *string   `json:"avatar_url"`
	IsActive         bool      `json:"is_active"`
	EmailVerified    bool      `json:"email_verified"`
	TwoFactorEnabled bool      `json:"two_factor_enabled"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.ID,
		arg.FullName,
		arg.Phone,
		arg.AvatarUrl,
		arg.IsActive,
		arg.EmailVerified,
		arg.TwoFactorEnabled,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.FullName,
		&i.Phone,
		&i.AvatarUrl,
		&i.IsActive,
		&i.EmailVerified,
		&i.TwoFactorEnabled,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CreatedByHodID,
		&i.IsApproved,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.DateOfBirth,
		&i.EmergencyContactName,
		&i.EmergencyContactPhone,
		&i.HomeAddress,
	)
	return i, err
}
