// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: verification_announcements.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const acknowledgeAnnouncement = `-- name: AcknowledgeAnnouncement :exec
INSERT INTO announcement_read_receipts (announcement_id, student_id, read_at, acknowledged_at, device_type)
VALUES ($1, $2, NOW(), NOW(), $3)
ON CONFLICT (announcement_id, student_id)
DO UPDATE SET acknowledged_at = COALESCE(announcement_read_receipts.acknowledged_at, NOW()),
              read_at = COALESCE(announcement_read_receipts.read_at, NOW())
`

type AcknowledgeAnnouncementParams struct {
	AnnouncementID uuid.UUID `json:"announcement_id"`
	StudentID      uuid.UUID `json:"student_id"`
	DeviceType     *string   `json:"device_type"`
}

func (q *Queries) AcknowledgeAnnouncement(ctx context.Context, arg AcknowledgeAnnouncementParams) error {
	_, err := q.db.Exec(ctx, acknowledgeAnnouncement, arg.AnnouncementID, arg.StudentID, arg.DeviceType)
	return err
}

const archiveAnnouncement = `-- name: ArchiveAnnouncement :exec
UPDATE announcements SET status = 'archived', updated_at = NOW()
WHERE id = $1
`

func (q *Queries) ArchiveAnnouncement(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, archiveAnnouncement, id)
	return err
}

const bulkApproveStudentOnboardings = `-- name: BulkApproveStudentOnboardings :exec
UPDATE student_onboardings
SET status = 'approved', reviewed_by = $2, reviewed_at = NOW(), updated_at = NOW()
WHERE id = ANY($1::uuid[]) AND status = 'pending'
`

type BulkApproveStudentOnboardingsParams struct {
	Column1    []uuid.UUID `json:"column_1"`
	ReviewedBy pgtype.UUID `json:"reviewed_by"`
}

func (q *Queries) BulkApproveStudentOnboardings(ctx context.Context, arg BulkApproveStudentOnboardingsParams) error {
	_, err := q.db.Exec(ctx, bulkApproveStudentOnboardings, arg.Column1, arg.ReviewedBy)
	return err
}

const bulkCreateVerificationRecords = `-- name: BulkCreateVerificationRecords :exec
INSERT INTO verification_records (matric_number, full_name, level, entry_session, department, status)
SELECT unnest($1::text[]), unnest($2::text[]), unnest($3::int[]),
       unnest($4::text[]), unnest($5::text[]), unnest($6::text[])
ON CONFLICT (matric_number) DO UPDATE
SET full_name = EXCLUDED.full_name, level = EXCLUDED.level,
    entry_session = EXCLUDED.entry_session, status = EXCLUDED.status,
    updated_at = NOW()
`

type BulkCreateVerificationRecordsParams struct {
	Column1 []string `json:"column_1"`
	Column2 []string `json:"column_2"`
	Column3 []int32  `json:"column_3"`
	Column4 []string `json:"column_4"`
	Column5 []string `json:"column_5"`
	Column6 []string `json:"column_6"`
}

func (q *Queries) BulkCreateVerificationRecords(ctx context.Context, arg BulkCreateVerificationRecordsParams) error {
	_, err := q.db.Exec(ctx, bulkCreateVerificationRecords,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
		arg.Column6,
	)
	return err
}

const countAnnouncementsByStatus = `-- name: CountAnnouncementsByStatus :many
SELECT status, COUNT(*) as count FROM announcements GROUP BY status
`

type CountAnnouncementsByStatusRow struct {
	Status interface{} `json:"status"`
	Count  int64       `json:"count"`
}

func (q *Queries) CountAnnouncementsByStatus(ctx context.Context) ([]CountAnnouncementsByStatusRow, error) {
	rows, err := q.db.Query(ctx, countAnnouncementsByStatus)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountAnnouncementsByStatusRow{}
	for rows.Next() {
		var i CountAnnouncementsByStatusRow
		if err := rows.Scan(&i.Status, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countStudentOnboardingsByStatus = `-- name: CountStudentOnboardingsByStatus :many
SELECT status, COUNT(*) as count
FROM student_onboardings
GROUP BY status
`

type CountStudentOnboardingsByStatusRow struct {
	Status interface{} `json:"status"`
	Count  int64       `json:"count"`
}

func (q *Queries) CountStudentOnboardingsByStatus(ctx context.Context) ([]CountStudentOnboardingsByStatusRow, error) {
	rows, err := q.db.Query(ctx, countStudentOnboardingsByStatus)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountStudentOnboardingsByStatusRow{}
	for rows.Next() {
		var i CountStudentOnboardingsByStatusRow
		if err := rows.Scan(&i.Status, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createAnnouncementComment = `-- name: CreateAnnouncementComment :one

INSERT INTO announcement_comments (announcement_id, author_id, parent_comment_id, content)
VALUES ($1, $2, $3, $4)
RETURNING id, announcement_id, author_id, parent_comment_id, content, is_hidden, created_at, updated_at
`

type CreateAnnouncementCommentParams struct {
	AnnouncementID  uuid.UUID   `json:"announcement_id"`
	AuthorID        uuid.UUID   `json:"author_id"`
	ParentCommentID pgtype.UUID `json:"parent_comment_id"`
	Content         string      `json:"content"`
}

// ==================== ANNOUNCEMENT COMMENTS ====================
func (q *Queries) CreateAnnouncementComment(ctx context.Context, arg CreateAnnouncementCommentParams) (AnnouncementComment, error) {
	row := q.db.QueryRow(ctx, createAnnouncementComment,
		arg.AnnouncementID,
		arg.AuthorID,
		arg.ParentCommentID,
		arg.Content,
	)
	var i AnnouncementComment
	err := row.Scan(
		&i.ID,
		&i.AnnouncementID,
		&i.AuthorID,
		&i.ParentCommentID,
		&i.Content,
		&i.IsHidden,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createAnnouncementTemplate = `-- name: CreateAnnouncementTemplate :one

INSERT INTO announcement_templates (name, default_title, default_body, default_priority, default_category, default_requires_acknowledgment, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, name, default_title, default_body, default_priority, default_category, default_requires_acknowledgment, created_by, created_at, updated_at
`

type CreateAnnouncementTemplateParams struct {
	Name                          string      `json:"name"`
	DefaultTitle                  string      `json:"default_title"`
	DefaultBody                   string      `json:"default_body"`
	DefaultPriority               interface{} `json:"default_priority"`
	DefaultCategory               interface{} `json:"default_category"`
	DefaultRequiresAcknowledgment bool        `json:"default_requires_acknowledgment"`
	CreatedBy                     pgtype.UUID `json:"created_by"`
}

// ==================== ANNOUNCEMENT TEMPLATES ====================
func (q *Queries) CreateAnnouncementTemplate(ctx context.Context, arg CreateAnnouncementTemplateParams) (AnnouncementTemplate, error) {
	row := q.db.QueryRow(ctx, createAnnouncementTemplate,
		arg.Name,
		arg.DefaultTitle,
		arg.DefaultBody,
		arg.DefaultPriority,
		arg.DefaultCategory,
		arg.DefaultRequiresAcknowledgment,
		arg.CreatedBy,
	)
	var i AnnouncementTemplate
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.DefaultTitle,
		&i.DefaultBody,
		&i.DefaultPriority,
		&i.DefaultCategory,
		&i.DefaultRequiresAcknowledgment,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createAnnouncementV2 = `-- name: CreateAnnouncementV2 :one

INSERT INTO announcements (title, content, summary, priority, category, is_pinned,
    target_level, target_audience, target_levels, target_departments, attachments,
    requires_acknowledgment, status, scheduled_for, created_by, pin_order)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16)
RETURNING id, title, content, is_pinned, target_level, target_audience, expires_at, created_by, created_at, summary, priority, category, target_levels, target_departments, attachments, requires_acknowledgment, status, scheduled_for, read_count, acknowledged_count, pin_order, updated_at
`

type CreateAnnouncementV2Params struct {
	Title                  string             `json:"title"`
	Content                string             `json:"content"`
	Summary                *string            `json:"summary"`
	Priority               interface{}        `json:"priority"`
	Category               interface{}        `json:"category"`
	IsPinned               bool               `json:"is_pinned"`
	TargetLevel            *int32             `json:"target_level"`
	TargetAudience         []byte             `json:"target_audience"`
	TargetLevels           []byte             `json:"target_levels"`
	TargetDepartments      []byte             `json:"target_departments"`
	Attachments            []byte             `json:"attachments"`
	RequiresAcknowledgment bool               `json:"requires_acknowledgment"`
	Status                 interface{}        `json:"status"`
	ScheduledFor           pgtype.Timestamptz `json:"scheduled_for"`
	CreatedBy              uuid.UUID          `json:"created_by"`
	PinOrder               *int32             `json:"pin_order"`
}

// ==================== ENHANCED ANNOUNCEMENTS ====================
func (q *Queries) CreateAnnouncementV2(ctx context.Context, arg CreateAnnouncementV2Params) (Announcement, error) {
	row := q.db.QueryRow(ctx, createAnnouncementV2,
		arg.Title,
		arg.Content,
		arg.Summary,
		arg.Priority,
		arg.Category,
		arg.IsPinned,
		arg.TargetLevel,
		arg.TargetAudience,
		arg.TargetLevels,
		arg.TargetDepartments,
		arg.Attachments,
		arg.RequiresAcknowledgment,
		arg.Status,
		arg.ScheduledFor,
		arg.CreatedBy,
		arg.PinOrder,
	)
	var i Announcement
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Content,
		&i.IsPinned,
		&i.TargetLevel,
		&i.TargetAudience,
		&i.ExpiresAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.Summary,
		&i.Priority,
		&i.Category,
		&i.TargetLevels,
		&i.TargetDepartments,
		&i.Attachments,
		&i.RequiresAcknowledgment,
		&i.Status,
		&i.ScheduledFor,
		&i.ReadCount,
		&i.AcknowledgedCount,
		&i.PinOrder,
		&i.UpdatedAt,
	)
	return i, err
}

const createReadReceipt = `-- name: CreateReadReceipt :one

INSERT INTO announcement_read_receipts (announcement_id, student_id, read_at, device_type)
VALUES ($1, $2, NOW(), $3)
ON CONFLICT (announcement_id, student_id)
DO UPDATE SET read_at = COALESCE(announcement_read_receipts.read_at, NOW())
RETURNING id, announcement_id, student_id, read_at, acknowledged_at, device_type, created_at
`

type CreateReadReceiptParams struct {
	AnnouncementID uuid.UUID `json:"announcement_id"`
	StudentID      uuid.UUID `json:"student_id"`
	DeviceType     *string   `json:"device_type"`
}

// ==================== ANNOUNCEMENT READ RECEIPTS ====================
func (q *Queries) CreateReadReceipt(ctx context.Context, arg CreateReadReceiptParams) (AnnouncementReadReceipt, error) {
	row := q.db.QueryRow(ctx, createReadReceipt, arg.AnnouncementID, arg.StudentID, arg.DeviceType)
	var i AnnouncementReadReceipt
	err := row.Scan(
		&i.ID,
		&i.AnnouncementID,
		&i.StudentID,
		&i.ReadAt,
		&i.AcknowledgedAt,
		&i.DeviceType,
		&i.CreatedAt,
	)
	return i, err
}

const createStudentOnboarding = `-- name: CreateStudentOnboarding :one

INSERT INTO student_onboardings (user_id, matric_number, verification_record_id, match_confidence, submitted_email, submitted_phone, status)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, user_id, matric_number, verification_record_id, match_confidence, submitted_email, submitted_phone, status, reviewed_by, reviewed_at, rejection_reason, created_at, updated_at
`

type CreateStudentOnboardingParams struct {
	UserID               uuid.UUID   `json:"user_id"`
	MatricNumber         string      `json:"matric_number"`
	VerificationRecordID pgtype.UUID `json:"verification_record_id"`
	MatchConfidence      *float32    `json:"match_confidence"`
	SubmittedEmail       *string     `json:"submitted_email"`
	SubmittedPhone       *string     `json:"submitted_phone"`
	Status               interface{} `json:"status"`
}

// ==================== STUDENT ONBOARDINGS ====================
func (q *Queries) CreateStudentOnboarding(ctx context.Context, arg CreateStudentOnboardingParams) (StudentOnboarding, error) {
	row := q.db.QueryRow(ctx, createStudentOnboarding,
		arg.UserID,
		arg.MatricNumber,
		arg.VerificationRecordID,
		arg.MatchConfidence,
		arg.SubmittedEmail,
		arg.SubmittedPhone,
		arg.Status,
	)
	var i StudentOnboarding
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.MatricNumber,
		&i.VerificationRecordID,
		&i.MatchConfidence,
		&i.SubmittedEmail,
		&i.SubmittedPhone,
		&i.Status,
		&i.ReviewedBy,
		&i.ReviewedAt,
		&i.RejectionReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createVerificationRecord = `-- name: CreateVerificationRecord :one

INSERT INTO verification_records (matric_number, full_name, level, entry_session, department, status)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, matric_number, full_name, level, entry_session, department, status, imported_at, created_at, updated_at
`

type CreateVerificationRecordParams struct {
	MatricNumber string `json:"matric_number"`
	FullName     string `json:"full_name"`
	Level        int32  `json:"level"`
	EntrySession string `json:"entry_session"`
	Department   string `json:"department"`
	Status       string `json:"status"`
}

// ==================== VERIFICATION RECORDS ====================
func (q *Queries) CreateVerificationRecord(ctx context.Context, arg CreateVerificationRecordParams) (VerificationRecord, error) {
	row := q.db.QueryRow(ctx, createVerificationRecord,
		arg.MatricNumber,
		arg.FullName,
		arg.Level,
		arg.EntrySession,
		arg.Department,
		arg.Status,
	)
	var i VerificationRecord
	err := row.Scan(
		&i.ID,
		&i.MatricNumber,
		&i.FullName,
		&i.Level,
		&i.EntrySession,
		&i.Department,
		&i.Status,
		&i.ImportedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAnnouncementComment = `-- name: DeleteAnnouncementComment :exec
DELETE FROM announcement_comments WHERE id = $1 AND author_id = $2
`

type DeleteAnnouncementCommentParams struct {
	ID       uuid.UUID `json:"id"`
	AuthorID uuid.UUID `json:"author_id"`
}

func (q *Queries) DeleteAnnouncementComment(ctx context.Context, arg DeleteAnnouncementCommentParams) error {
	_, err := q.db.Exec(ctx, deleteAnnouncementComment, arg.ID, arg.AuthorID)
	return err
}

const deleteAnnouncementTemplate = `-- name: DeleteAnnouncementTemplate :exec
DELETE FROM announcement_templates WHERE id = $1
`

func (q *Queries) DeleteAnnouncementTemplate(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteAnnouncementTemplate, id)
	return err
}

const deleteAnnouncementV2 = `-- name: DeleteAnnouncementV2 :exec
DELETE FROM announcements WHERE id = $1
`

func (q *Queries) DeleteAnnouncementV2(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteAnnouncementV2, id)
	return err
}

const getAnnouncementReceiptStats = `-- name: GetAnnouncementReceiptStats :one
SELECT
    COUNT(*) FILTER (WHERE read_at IS NOT NULL) AS read_count,
    COUNT(*) FILTER (WHERE acknowledged_at IS NOT NULL) AS ack_count,
    COUNT(*) AS total_count
FROM announcement_read_receipts
WHERE announcement_id = $1
`

type GetAnnouncementReceiptStatsRow struct {
	ReadCount  int64 `json:"read_count"`
	AckCount   int64 `json:"ack_count"`
	TotalCount int64 `json:"total_count"`
}

func (q *Queries) GetAnnouncementReceiptStats(ctx context.Context, announcementID uuid.UUID) (GetAnnouncementReceiptStatsRow, error) {
	row := q.db.QueryRow(ctx, getAnnouncementReceiptStats, announcementID)
	var i GetAnnouncementReceiptStatsRow
	err := row.Scan(&i.ReadCount, &i.AckCount, &i.TotalCount)
	return i, err
}

const getAnnouncementTemplate = `-- name: GetAnnouncementTemplate :one
SELECT id, name, default_title, default_body, default_priority, default_category, default_requires_acknowledgment, created_by, created_at, updated_at FROM announcement_templates WHERE id = $1
`

func (q *Queries) GetAnnouncementTemplate(ctx context.Context, id uuid.UUID) (AnnouncementTemplate, error) {
	row := q.db.QueryRow(ctx, getAnnouncementTemplate, id)
	var i AnnouncementTemplate
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.DefaultTitle,
		&i.DefaultBody,
		&i.DefaultPriority,
		&i.DefaultCategory,
		&i.DefaultRequiresAcknowledgment,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAnnouncementV2 = `-- name: GetAnnouncementV2 :one
SELECT a.id, a.title, a.content, a.is_pinned, a.target_level, a.target_audience, a.expires_at, a.created_by, a.created_at, a.summary, a.priority, a.category, a.target_levels, a.target_departments, a.attachments, a.requires_acknowledgment, a.status, a.scheduled_for, a.read_count, a.acknowledged_count, a.pin_order, a.updated_at, u.full_name AS author_name
FROM announcements a
JOIN users u ON u.id = a.created_by
WHERE a.id = $1
`

type GetAnnouncementV2Row struct {
	ID                     uuid.UUID          `json:"id"`
	Title                  string             `json:"title"`
	Content                string             `json:"content"`
	IsPinned               bool               `json:"is_pinned"`
	TargetLevel            *int32             `json:"target_level"`
	TargetAudience         []byte             `json:"target_audience"`
	ExpiresAt              pgtype.Timestamptz `json:"expires_at"`
	CreatedBy              uuid.UUID          `json:"created_by"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
	Summary                *string            `json:"summary"`
	Priority               interface{}        `json:"priority"`
	Category               interface{}        `json:"category"`
	TargetLevels           []byte             `json:"target_levels"`
	TargetDepartments      []byte             `json:"target_departments"`
	Attachments            []byte             `json:"attachments"`
	RequiresAcknowledgment bool               `json:"requires_acknowledgment"`
	Status                 interface{}        `json:"status"`
	ScheduledFor           pgtype.Timestamptz `json:"scheduled_for"`
	ReadCount              int32              `json:"read_count"`
	AcknowledgedCount      int32              `json:"acknowledged_count"`
	PinOrder               *int32             `json:"pin_order"`
	UpdatedAt              pgtype.Timestamptz `json:"updated_at"`
	AuthorName             string             `json:"author_name"`
}

func (q *Queries) GetAnnouncementV2(ctx context.Context, id uuid.UUID) (GetAnnouncementV2Row, error) {
	row := q.db.QueryRow(ctx, getAnnouncementV2, id)
	var i GetAnnouncementV2Row
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Content,
		&i.IsPinned,
		&i.TargetLevel,
		&i.TargetAudience,
		&i.ExpiresAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.Summary,
		&i.Priority,
		&i.Category,
		&i.TargetLevels,
		&i.TargetDepartments,
		&i.Attachments,
		&i.RequiresAcknowledgment,
		&i.Status,
		&i.ScheduledFor,
		&i.ReadCount,
		&i.AcknowledgedCount,
		&i.PinOrder,
		&i.UpdatedAt,
		&i.AuthorName,
	)
	return i, err
}

const getReadReceipt = `-- name: GetReadReceipt :one
SELECT id, announcement_id, student_id, read_at, acknowledged_at, device_type, created_at FROM announcement_read_receipts
WHERE announcement_id = $1 AND student_id = $2
`

type GetReadReceiptParams struct {
	AnnouncementID uuid.UUID `json:"announcement_id"`
	StudentID      uuid.UUID `json:"student_id"`
}

func (q *Queries) GetReadReceipt(ctx context.Context, arg GetReadReceiptParams) (AnnouncementReadReceipt, error) {
	row := q.db.QueryRow(ctx, getReadReceipt, arg.AnnouncementID, arg.StudentID)
	var i AnnouncementReadReceipt
	err := row.Scan(
		&i.ID,
		&i.AnnouncementID,
		&i.StudentID,
		&i.ReadAt,
		&i.AcknowledgedAt,
		&i.DeviceType,
		&i.CreatedAt,
	)
	return i, err
}

const getStudentOnboardingByMatric = `-- name: GetStudentOnboardingByMatric :one
SELECT so.id, so.user_id, so.matric_number, so.verification_record_id, so.match_confidence, so.submitted_email, so.submitted_phone, so.status, so.reviewed_by, so.reviewed_at, so.rejection_reason, so.created_at, so.updated_at, vr.full_name AS verified_name, vr.level AS verified_level
FROM student_onboardings so
LEFT JOIN verification_records vr ON vr.id = so.verification_record_id
WHERE so.matric_number = $1
`

type GetStudentOnboardingByMatricRow struct {
	ID                   uuid.UUID          `json:"id"`
	UserID               uuid.UUID          `json:"user_id"`
	MatricNumber         string             `json:"matric_number"`
	VerificationRecordID pgtype.UUID        `json:"verification_record_id"`
	MatchConfidence      *float32           `json:"match_confidence"`
	SubmittedEmail       *string            `json:"submitted_email"`
	SubmittedPhone       *string            `json:"submitted_phone"`
	Status               interface{}        `json:"status"`
	ReviewedBy           pgtype.UUID        `json:"reviewed_by"`
	ReviewedAt           pgtype.Timestamptz `json:"reviewed_at"`
	RejectionReason      *string            `json:"rejection_reason"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
	VerifiedName         *string            `json:"verified_name"`
	VerifiedLevel        *int32             `json:"verified_level"`
}

func (q *Queries) GetStudentOnboardingByMatric(ctx context.Context, matricNumber string) (GetStudentOnboardingByMatricRow, error) {
	row := q.db.QueryRow(ctx, getStudentOnboardingByMatric, matricNumber)
	var i GetStudentOnboardingByMatricRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.MatricNumber,
		&i.VerificationRecordID,
		&i.MatchConfidence,
		&i.SubmittedEmail,
		&i.SubmittedPhone,
		&i.Status,
		&i.ReviewedBy,
		&i.ReviewedAt,
		&i.RejectionReason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.VerifiedName,
		&i.VerifiedLevel,
	)
	return i, err
}

const getStudentOnboardingByUserID = `-- name: GetStudentOnboardingByUserID :one
SELECT so.id, so.user_id, so.matric_number, so.verification_record_id, so.match_confidence, so.submitted_email, so.submitted_phone, so.status, so.reviewed_by, so.reviewed_at, so.rejection_reason, so.created_at, so.updated_at, vr.full_name AS verified_name, vr.level AS verified_level, vr.department AS verified_department
FROM student_onboardings so
LEFT JOIN verification_records vr ON vr.id = so.verification_record_id
WHERE so.user_id = $1
`

type GetStudentOnboardingByUserIDRow struct {
	ID                   uuid.UUID          `json:"id"`
	UserID               uuid.UUID          `json:"user_id"`
	MatricNumber         string             `json:"matric_number"`
	VerificationRecordID pgtype.UUID        `json:"verification_record_id"`
	MatchConfidence      *float32           `json:"match_confidence"`
	SubmittedEmail       *string            `json:"submitted_email"`
	SubmittedPhone       *string            `json:"submitted_phone"`
	Status               interface{}        `json:"status"`
	ReviewedBy           pgtype.UUID        `json:"reviewed_by"`
	ReviewedAt           pgtype.Timestamptz `json:"reviewed_at"`
	RejectionReason      *string            `json:"rejection_reason"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
	VerifiedName         *string            `json:"verified_name"`
	VerifiedLevel        *int32             `json:"verified_level"`
	VerifiedDepartment   *string            `json:"verified_department"`
}

func (q *Queries) GetStudentOnboardingByUserID(ctx context.Context, userID uuid.UUID) (GetStudentOnboardingByUserIDRow, error) {
	row := q.db.QueryRow(ctx, getStudentOnboardingByUserID, userID)
	var i GetStudentOnboardingByUserIDRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.MatricNumber,
		&i.VerificationRecordID,
		&i.MatchConfidence,
		&i.SubmittedEmail,
		&i.SubmittedPhone,
		&i.Status,
		&i.ReviewedBy,
		&i.ReviewedAt,
		&i.RejectionReason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.VerifiedName,
		&i.VerifiedLevel,
		&i.VerifiedDepartment,
	)
	return i, err
}

const getStudentReadAnnouncements = `-- name: GetStudentReadAnnouncements :many
SELECT a.id, a.title, a.content, a.is_pinned, a.target_level, a.target_audience, a.expires_at, a.created_by, a.created_at, a.summary, a.priority, a.category, a.target_levels, a.target_departments, a.attachments, a.requires_acknowledgment, a.status, a.scheduled_for, a.read_count, a.acknowledged_count, a.pin_order, a.updated_at, u.full_name AS author_name, arr.read_at, arr.acknowledged_at
FROM announcements a
JOIN users u ON u.id = a.created_by
JOIN announcement_read_receipts arr ON arr.announcement_id = a.id
WHERE arr.student_id = $1 AND arr.read_at IS NOT NULL
ORDER BY arr.read_at DESC
LIMIT $2 OFFSET $3
`

type GetStudentReadAnnouncementsParams struct {
	StudentID uuid.UUID `json:"student_id"`
	Limit     int32     `json:"limit"`
	Offset    int32     `json:"offset"`
}

type GetStudentReadAnnouncementsRow struct {
	ID                     uuid.UUID          `json:"id"`
	Title                  string             `json:"title"`
	Content                string             `json:"content"`
	IsPinned               bool               `json:"is_pinned"`
	TargetLevel            *int32             `json:"target_level"`
	TargetAudience         []byte             `json:"target_audience"`
	ExpiresAt              pgtype.Timestamptz `json:"expires_at"`
	CreatedBy              uuid.UUID          `json:"created_by"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
	Summary                *string            `json:"summary"`
	Priority               interface{}        `json:"priority"`
	Category               interface{}        `json:"category"`
	TargetLevels           []byte             `json:"target_levels"`
	TargetDepartments      []byte             `json:"target_departments"`
	Attachments            []byte             `json:"attachments"`
	RequiresAcknowledgment bool               `json:"requires_acknowledgment"`
	Status                 interface{}        `json:"status"`
	ScheduledFor           pgtype.Timestamptz `json:"scheduled_for"`
	ReadCount              int32              `json:"read_count"`
	AcknowledgedCount      int32              `json:"acknowledged_count"`
	PinOrder               *int32             `json:"pin_order"`
	UpdatedAt              pgtype.Timestamptz `json:"updated_at"`
	AuthorName             string             `json:"author_name"`
	ReadAt                 pgtype.Timestamptz `json:"read_at"`
	AcknowledgedAt         pgtype.Timestamptz `json:"acknowledged_at"`
}

func (q *Queries) GetStudentReadAnnouncements(ctx context.Context, arg GetStudentReadAnnouncementsParams) ([]GetStudentReadAnnouncementsRow, error) {
	rows, err := q.db.Query(ctx, getStudentReadAnnouncements, arg.StudentID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetStudentReadAnnouncementsRow{}
	for rows.Next() {
		var i GetStudentReadAnnouncementsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Content,
			&i.IsPinned,
			&i.TargetLevel,
			&i.TargetAudience,
			&i.ExpiresAt,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.Summary,
			&i.Priority,
			&i.Category,
			&i.TargetLevels,
			&i.TargetDepartments,
			&i.Attachments,
			&i.RequiresAcknowledgment,
			&i.Status,
			&i.ScheduledFor,
			&i.ReadCount,
			&i.AcknowledgedCount,
			&i.PinOrder,
			&i.UpdatedAt,
			&i.AuthorName,
			&i.ReadAt,
			&i.AcknowledgedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUnverifiedStudents = `-- name: GetUnverifiedStudents :many
SELECT vr.id, vr.matric_number, vr.full_name, vr.level, vr.entry_session, vr.department, vr.status, vr.imported_at, vr.created_at, vr.updated_at
FROM verification_records vr
WHERE NOT EXISTS (
    SELECT 1 FROM student_onboardings so
    WHERE so.verification_record_id = vr.id AND so.status = 'approved'
)
AND vr.status = 'active'
ORDER BY vr.created_at DESC
`

func (q *Queries) GetUnverifiedStudents(ctx context.Context) ([]VerificationRecord, error) {
	rows, err := q.db.Query(ctx, getUnverifiedStudents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VerificationRecord{}
	for rows.Next() {
		var i VerificationRecord
		if err := rows.Scan(
			&i.ID,
			&i.MatricNumber,
			&i.FullName,
			&i.Level,
			&i.EntrySession,
			&i.Department,
			&i.Status,
			&i.ImportedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getVerificationRecordByMatric = `-- name: GetVerificationRecordByMatric :one
SELECT id, matric_number, full_name, level, entry_session, department, status, imported_at, created_at, updated_at FROM verification_records WHERE matric_number = $1
`

func (q *Queries) GetVerificationRecordByMatric(ctx context.Context, matricNumber string) (VerificationRecord, error) {
	row := q.db.QueryRow(ctx, getVerificationRecordByMatric, matricNumber)
	var i VerificationRecord
	err := row.Scan(
		&i.ID,
		&i.MatricNumber,
		&i.FullName,
		&i.Level,
		&i.EntrySession,
		&i.Department,
		&i.Status,
		&i.ImportedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const hasStudentAcknowledgedAnnouncement = `-- name: HasStudentAcknowledgedAnnouncement :one
SELECT EXISTS(
    SELECT 1 FROM announcement_read_receipts
    WHERE announcement_id = $1 AND student_id = $2 AND acknowledged_at IS NOT NULL
)
`

type HasStudentAcknowledgedAnnouncementParams struct {
	AnnouncementID uuid.UUID `json:"announcement_id"`
	StudentID      uuid.UUID `json:"student_id"`
}

func (q *Queries) HasStudentAcknowledgedAnnouncement(ctx context.Context, arg HasStudentAcknowledgedAnnouncementParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasStudentAcknowledgedAnnouncement, arg.AnnouncementID, arg.StudentID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const hasStudentReadAnnouncement = `-- name: HasStudentReadAnnouncement :one
SELECT EXISTS(
    SELECT 1 FROM announcement_read_receipts
    WHERE announcement_id = $1 AND student_id = $2 AND read_at IS NOT NULL
)
`

type HasStudentReadAnnouncementParams struct {
	AnnouncementID uuid.UUID `json:"announcement_id"`
	StudentID      uuid.UUID `json:"student_id"`
}

func (q *Queries) HasStudentReadAnnouncement(ctx context.Context, arg HasStudentReadAnnouncementParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasStudentReadAnnouncement, arg.AnnouncementID, arg.StudentID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const hideAnnouncementComment = `-- name: HideAnnouncementComment :exec
UPDATE announcement_comments SET is_hidden = true WHERE id = $1
`

func (q *Queries) HideAnnouncementComment(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, hideAnnouncementComment, id)
	return err
}

const incrementAnnouncementAckCount = `-- name: IncrementAnnouncementAckCount :exec
UPDATE announcements SET acknowledged_count = acknowledged_count + 1 WHERE id = $1
`

func (q *Queries) IncrementAnnouncementAckCount(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, incrementAnnouncementAckCount, id)
	return err
}

const incrementAnnouncementReadCount = `-- name: IncrementAnnouncementReadCount :exec
UPDATE announcements SET read_count = read_count + 1 WHERE id = $1
`

func (q *Queries) IncrementAnnouncementReadCount(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, incrementAnnouncementReadCount, id)
	return err
}

const listAnnouncementComments = `-- name: ListAnnouncementComments :many
SELECT ac.id, ac.announcement_id, ac.author_id, ac.parent_comment_id, ac.content, ac.is_hidden, ac.created_at, ac.updated_at, u.full_name AS author_name
FROM announcement_comments ac
JOIN users u ON u.id = ac.author_id
WHERE ac.announcement_id = $1 AND ac.is_hidden = false
ORDER BY ac.created_at ASC
`

type ListAnnouncementCommentsRow struct {
	ID              uuid.UUID          `json:"id"`
	AnnouncementID  uuid.UUID          `json:"announcement_id"`
	AuthorID        uuid.UUID          `json:"author_id"`
	ParentCommentID pgtype.UUID        `json:"parent_comment_id"`
	Content         string             `json:"content"`
	IsHidden        bool               `json:"is_hidden"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	AuthorName      string             `json:"author_name"`
}

func (q *Queries) ListAnnouncementComments(ctx context.Context, announcementID uuid.UUID) ([]ListAnnouncementCommentsRow, error) {
	rows, err := q.db.Query(ctx, listAnnouncementComments, announcementID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAnnouncementCommentsRow{}
	for rows.Next() {
		var i ListAnnouncementCommentsRow
		if err := rows.Scan(
			&i.ID,
			&i.AnnouncementID,
			&i.AuthorID,
			&i.ParentCommentID,
			&i.Content,
			&i.IsHidden,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AuthorName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAnnouncementTemplates = `-- name: ListAnnouncementTemplates :many
SELECT id, name, default_title, default_body, default_priority, default_category, default_requires_acknowledgment, created_by, created_at, updated_at FROM announcement_templates ORDER BY name
`

func (q *Queries) ListAnnouncementTemplates(ctx context.Context) ([]AnnouncementTemplate, error) {
	rows, err := q.db.Query(ctx, listAnnouncementTemplates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AnnouncementTemplate{}
	for rows.Next() {
		var i AnnouncementTemplate
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.DefaultTitle,
			&i.DefaultBody,
			&i.DefaultPriority,
			&i.DefaultCategory,
			&i.DefaultRequiresAcknowledgment,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAnnouncementsV2 = `-- name: ListAnnouncementsV2 :many
SELECT a.id, a.title, a.content, a.is_pinned, a.target_level, a.target_audience, a.expires_at, a.created_by, a.created_at, a.summary, a.priority, a.category, a.target_levels, a.target_departments, a.attachments, a.requires_acknowledgment, a.status, a.scheduled_for, a.read_count, a.acknowledged_count, a.pin_order, a.updated_at, u.full_name AS author_name
FROM announcements a
JOIN users u ON u.id = a.created_by
WHERE ($1::announcement_status IS NULL OR a.status = $1)
AND ($2::announcement_priority IS NULL OR a.priority = $2)
AND ($3::announcement_category IS NULL OR a.category = $3)
ORDER BY a.is_pinned DESC, a.pin_order ASC NULLS LAST, a.created_at DESC
LIMIT $4 OFFSET $5
`

type ListAnnouncementsV2Params struct {
	Column1 interface{} `json:"column_1"`
	Column2 interface{} `json:"column_2"`
	Column3 interface{} `json:"column_3"`
	Limit   int32       `json:"limit"`
	Offset  int32       `json:"offset"`
}

type ListAnnouncementsV2Row struct {
	ID                     uuid.UUID          `json:"id"`
	Title                  string             `json:"title"`
	Content                string             `json:"content"`
	IsPinned               bool               `json:"is_pinned"`
	TargetLevel            *int32             `json:"target_level"`
	TargetAudience         []byte             `json:"target_audience"`
	ExpiresAt              pgtype.Timestamptz `json:"expires_at"`
	CreatedBy              uuid.UUID          `json:"created_by"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
	Summary                *string            `json:"summary"`
	Priority               interface{}        `json:"priority"`
	Category               interface{}        `json:"category"`
	TargetLevels           []byte             `json:"target_levels"`
	TargetDepartments      []byte             `json:"target_departments"`
	Attachments            []byte             `json:"attachments"`
	RequiresAcknowledgment bool               `json:"requires_acknowledgment"`
	Status                 interface{}        `json:"status"`
	ScheduledFor           pgtype.Timestamptz `json:"scheduled_for"`
	ReadCount              int32              `json:"read_count"`
	AcknowledgedCount      int32              `json:"acknowledged_count"`
	PinOrder               *int32             `json:"pin_order"`
	UpdatedAt              pgtype.Timestamptz `json:"updated_at"`
	AuthorName             string             `json:"author_name"`
}

func (q *Queries) ListAnnouncementsV2(ctx context.Context, arg ListAnnouncementsV2Params) ([]ListAnnouncementsV2Row, error) {
	rows, err := q.db.Query(ctx, listAnnouncementsV2,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAnnouncementsV2Row{}
	for rows.Next() {
		var i ListAnnouncementsV2Row
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Content,
			&i.IsPinned,
			&i.TargetLevel,
			&i.TargetAudience,
			&i.ExpiresAt,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.Summary,
			&i.Priority,
			&i.Category,
			&i.TargetLevels,
			&i.TargetDepartments,
			&i.Attachments,
			&i.RequiresAcknowledgment,
			&i.Status,
			&i.ScheduledFor,
			&i.ReadCount,
			&i.AcknowledgedCount,
			&i.PinOrder,
			&i.UpdatedAt,
			&i.AuthorName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublishedAnnouncements = `-- name: ListPublishedAnnouncements :many
SELECT a.id, a.title, a.content, a.is_pinned, a.target_level, a.target_audience, a.expires_at, a.created_by, a.created_at, a.summary, a.priority, a.category, a.target_levels, a.target_departments, a.attachments, a.requires_acknowledgment, a.status, a.scheduled_for, a.read_count, a.acknowledged_count, a.pin_order, a.updated_at, u.full_name AS author_name
FROM announcements a
JOIN users u ON u.id = a.created_by
WHERE a.status = 'published'
AND (a.expires_at IS NULL OR a.expires_at > NOW())
AND (a.scheduled_for IS NULL OR a.scheduled_for <= NOW())
ORDER BY a.is_pinned DESC, a.pin_order ASC NULLS LAST, a.created_at DESC
LIMIT $1 OFFSET $2
`

type ListPublishedAnnouncementsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListPublishedAnnouncementsRow struct {
	ID                     uuid.UUID          `json:"id"`
	Title                  string             `json:"title"`
	Content                string             `json:"content"`
	IsPinned               bool               `json:"is_pinned"`
	TargetLevel            *int32             `json:"target_level"`
	TargetAudience         []byte             `json:"target_audience"`
	ExpiresAt              pgtype.Timestamptz `json:"expires_at"`
	CreatedBy              uuid.UUID          `json:"created_by"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
	Summary                *string            `json:"summary"`
	Priority               interface{}        `json:"priority"`
	Category               interface{}        `json:"category"`
	TargetLevels           []byte             `json:"target_levels"`
	TargetDepartments      []byte             `json:"target_departments"`
	Attachments            []byte             `json:"attachments"`
	RequiresAcknowledgment bool               `json:"requires_acknowledgment"`
	Status                 interface{}        `json:"status"`
	ScheduledFor           pgtype.Timestamptz `json:"scheduled_for"`
	ReadCount              int32              `json:"read_count"`
	AcknowledgedCount      int32              `json:"acknowledged_count"`
	PinOrder               *int32             `json:"pin_order"`
	UpdatedAt              pgtype.Timestamptz `json:"updated_at"`
	AuthorName             string             `json:"author_name"`
}

func (q *Queries) ListPublishedAnnouncements(ctx context.Context, arg ListPublishedAnnouncementsParams) ([]ListPublishedAnnouncementsRow, error) {
	rows, err := q.db.Query(ctx, listPublishedAnnouncements, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPublishedAnnouncementsRow{}
	for rows.Next() {
		var i ListPublishedAnnouncementsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Content,
			&i.IsPinned,
			&i.TargetLevel,
			&i.TargetAudience,
			&i.ExpiresAt,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.Summary,
			&i.Priority,
			&i.Category,
			&i.TargetLevels,
			&i.TargetDepartments,
			&i.Attachments,
			&i.RequiresAcknowledgment,
			&i.Status,
			&i.ScheduledFor,
			&i.ReadCount,
			&i.AcknowledgedCount,
			&i.PinOrder,
			&i.UpdatedAt,
			&i.AuthorName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReadReceiptsByAnnouncement = `-- name: ListReadReceiptsByAnnouncement :many
SELECT arr.id, arr.announcement_id, arr.student_id, arr.read_at, arr.acknowledged_at, arr.device_type, arr.created_at, u.full_name AS student_name
FROM announcement_read_receipts arr
JOIN users u ON u.id = arr.student_id
WHERE arr.announcement_id = $1
ORDER BY arr.read_at DESC
`

type ListReadReceiptsByAnnouncementRow struct {
	ID             uuid.UUID          `json:"id"`
	AnnouncementID uuid.UUID          `json:"announcement_id"`
	StudentID      uuid.UUID          `json:"student_id"`
	ReadAt         pgtype.Timestamptz `json:"read_at"`
	AcknowledgedAt pgtype.Timestamptz `json:"acknowledged_at"`
	DeviceType     *string            `json:"device_type"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	StudentName    string             `json:"student_name"`
}

func (q *Queries) ListReadReceiptsByAnnouncement(ctx context.Context, announcementID uuid.UUID) ([]ListReadReceiptsByAnnouncementRow, error) {
	rows, err := q.db.Query(ctx, listReadReceiptsByAnnouncement, announcementID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListReadReceiptsByAnnouncementRow{}
	for rows.Next() {
		var i ListReadReceiptsByAnnouncementRow
		if err := rows.Scan(
			&i.ID,
			&i.AnnouncementID,
			&i.StudentID,
			&i.ReadAt,
			&i.AcknowledgedAt,
			&i.DeviceType,
			&i.CreatedAt,
			&i.StudentName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStudentAnnouncements = `-- name: ListStudentAnnouncements :many
SELECT a.id, a.title, a.content, a.is_pinned, a.target_level, a.target_audience, a.expires_at, a.created_by, a.created_at, a.summary, a.priority, a.category, a.target_levels, a.target_departments, a.attachments, a.requires_acknowledgment, a.status, a.scheduled_for, a.read_count, a.acknowledged_count, a.pin_order, a.updated_at, u.full_name AS author_name
FROM announcements a
JOIN users u ON u.id = a.created_by
WHERE a.status = 'published'
AND (a.expires_at IS NULL OR a.expires_at > NOW())
AND (a.scheduled_for IS NULL OR a.scheduled_for <= NOW())
AND (
    a.target_level IS NULL OR a.target_level = $1
)
AND (
    a.target_audience IS NULL OR a.target_audience = '[]'::jsonb
    OR a.target_audience @> to_jsonb($2::text)
)
ORDER BY a.is_pinned DESC, a.pin_order ASC NULLS LAST, a.created_at DESC
LIMIT $3 OFFSET $4
`

type ListStudentAnnouncementsParams struct {
	TargetLevel *int32 `json:"target_level"`
	Column2     string `json:"column_2"`
	Limit       int32  `json:"limit"`
	Offset      int32  `json:"offset"`
}

type ListStudentAnnouncementsRow struct {
	ID                     uuid.UUID          `json:"id"`
	Title                  string             `json:"title"`
	Content                string             `json:"content"`
	IsPinned               bool               `json:"is_pinned"`
	TargetLevel            *int32             `json:"target_level"`
	TargetAudience         []byte             `json:"target_audience"`
	ExpiresAt              pgtype.Timestamptz `json:"expires_at"`
	CreatedBy              uuid.UUID          `json:"created_by"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
	Summary                *string            `json:"summary"`
	Priority               interface{}        `json:"priority"`
	Category               interface{}        `json:"category"`
	TargetLevels           []byte             `json:"target_levels"`
	TargetDepartments      []byte             `json:"target_departments"`
	Attachments            []byte             `json:"attachments"`
	RequiresAcknowledgment bool               `json:"requires_acknowledgment"`
	Status                 interface{}        `json:"status"`
	ScheduledFor           pgtype.Timestamptz `json:"scheduled_for"`
	ReadCount              int32              `json:"read_count"`
	AcknowledgedCount      int32              `json:"acknowledged_count"`
	PinOrder               *int32             `json:"pin_order"`
	UpdatedAt              pgtype.Timestamptz `json:"updated_at"`
	AuthorName             string             `json:"author_name"`
}

func (q *Queries) ListStudentAnnouncements(ctx context.Context, arg ListStudentAnnouncementsParams) ([]ListStudentAnnouncementsRow, error) {
	rows, err := q.db.Query(ctx, listStudentAnnouncements,
		arg.TargetLevel,
		arg.Column2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListStudentAnnouncementsRow{}
	for rows.Next() {
		var i ListStudentAnnouncementsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Content,
			&i.IsPinned,
			&i.TargetLevel,
			&i.TargetAudience,
			&i.ExpiresAt,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.Summary,
			&i.Priority,
			&i.Category,
			&i.TargetLevels,
			&i.TargetDepartments,
			&i.Attachments,
			&i.RequiresAcknowledgment,
			&i.Status,
			&i.ScheduledFor,
			&i.ReadCount,
			&i.AcknowledgedCount,
			&i.PinOrder,
			&i.UpdatedAt,
			&i.AuthorName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStudentOnboardings = `-- name: ListStudentOnboardings :many
SELECT so.id, so.user_id, so.matric_number, so.verification_record_id, so.match_confidence, so.submitted_email, so.submitted_phone, so.status, so.reviewed_by, so.reviewed_at, so.rejection_reason, so.created_at, so.updated_at, vr.full_name AS verified_name, vr.level AS verified_level, vr.department AS verified_department
FROM student_onboardings so
LEFT JOIN verification_records vr ON vr.id = so.verification_record_id
WHERE ($1::onboarding_status IS NULL OR so.status = $1)
AND ($2::int IS NULL OR vr.level = $2)
ORDER BY so.created_at DESC
LIMIT $3 OFFSET $4
`

type ListStudentOnboardingsParams struct {
	Column1 interface{} `json:"column_1"`
	Column2 int32       `json:"column_2"`
	Limit   int32       `json:"limit"`
	Offset  int32       `json:"offset"`
}

type ListStudentOnboardingsRow struct {
	ID                   uuid.UUID          `json:"id"`
	UserID               uuid.UUID          `json:"user_id"`
	MatricNumber         string             `json:"matric_number"`
	VerificationRecordID pgtype.UUID        `json:"verification_record_id"`
	MatchConfidence      *float32           `json:"match_confidence"`
	SubmittedEmail       *string            `json:"submitted_email"`
	SubmittedPhone       *string            `json:"submitted_phone"`
	Status               interface{}        `json:"status"`
	ReviewedBy           pgtype.UUID        `json:"reviewed_by"`
	ReviewedAt           pgtype.Timestamptz `json:"reviewed_at"`
	RejectionReason      *string            `json:"rejection_reason"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
	VerifiedName         *string            `json:"verified_name"`
	VerifiedLevel        *int32             `json:"verified_level"`
	VerifiedDepartment   *string            `json:"verified_department"`
}

func (q *Queries) ListStudentOnboardings(ctx context.Context, arg ListStudentOnboardingsParams) ([]ListStudentOnboardingsRow, error) {
	rows, err := q.db.Query(ctx, listStudentOnboardings,
		arg.Column1,
		arg.Column2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListStudentOnboardingsRow{}
	for rows.Next() {
		var i ListStudentOnboardingsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.MatricNumber,
			&i.VerificationRecordID,
			&i.MatchConfidence,
			&i.SubmittedEmail,
			&i.SubmittedPhone,
			&i.Status,
			&i.ReviewedBy,
			&i.ReviewedAt,
			&i.RejectionReason,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.VerifiedName,
			&i.VerifiedLevel,
			&i.VerifiedDepartment,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnacknowledgedStudents = `-- name: ListUnacknowledgedStudents :many
SELECT u.id, u.full_name, u.email
FROM users u
JOIN students s ON s.user_id = u.id
WHERE u.is_approved = true AND u.is_active = true
AND NOT EXISTS (
    SELECT 1 FROM announcement_read_receipts arr
    WHERE arr.announcement_id = $1 AND arr.student_id = u.id AND arr.acknowledged_at IS NOT NULL
)
ORDER BY u.full_name
`

type ListUnacknowledgedStudentsRow struct {
	ID       uuid.UUID `json:"id"`
	FullName string    `json:"full_name"`
	Email    string    `json:"email"`
}

func (q *Queries) ListUnacknowledgedStudents(ctx context.Context, announcementID uuid.UUID) ([]ListUnacknowledgedStudentsRow, error) {
	rows, err := q.db.Query(ctx, listUnacknowledgedStudents, announcementID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUnacknowledgedStudentsRow{}
	for rows.Next() {
		var i ListUnacknowledgedStudentsRow
		if err := rows.Scan(&i.ID, &i.FullName, &i.Email); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVerificationRecords = `-- name: ListVerificationRecords :many
SELECT id, matric_number, full_name, level, entry_session, department, status, imported_at, created_at, updated_at FROM verification_records
WHERE ($1::text IS NULL OR matric_number ILIKE '%' || $1 || '%'
       OR full_name ILIKE '%' || $1 || '%')
AND ($2::int IS NULL OR level = $2)
AND ($3::text IS NULL OR status = $3)
ORDER BY created_at DESC
LIMIT $4 OFFSET $5
`

type ListVerificationRecordsParams struct {
	Column1 string `json:"column_1"`
	Column2 int32  `json:"column_2"`
	Column3 string `json:"column_3"`
	Limit   int32  `json:"limit"`
	Offset  int32  `json:"offset"`
}

func (q *Queries) ListVerificationRecords(ctx context.Context, arg ListVerificationRecordsParams) ([]VerificationRecord, error) {
	rows, err := q.db.Query(ctx, listVerificationRecords,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VerificationRecord{}
	for rows.Next() {
		var i VerificationRecord
		if err := rows.Scan(
			&i.ID,
			&i.MatricNumber,
			&i.FullName,
			&i.Level,
			&i.EntrySession,
			&i.Department,
			&i.Status,
			&i.ImportedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAnnouncementRead = `-- name: MarkAnnouncementRead :exec
INSERT INTO announcement_read_receipts (announcement_id, student_id, read_at, device_type)
VALUES ($1, $2, NOW(), $3)
ON CONFLICT (announcement_id, student_id) DO NOTHING
`

type MarkAnnouncementReadParams struct {
	AnnouncementID uuid.UUID `json:"announcement_id"`
	StudentID      uuid.UUID `json:"student_id"`
	DeviceType     *string   `json:"device_type"`
}

func (q *Queries) MarkAnnouncementRead(ctx context.Context, arg MarkAnnouncementReadParams) error {
	_, err := q.db.Exec(ctx, markAnnouncementRead, arg.AnnouncementID, arg.StudentID, arg.DeviceType)
	return err
}

const publishAnnouncement = `-- name: PublishAnnouncement :exec
UPDATE announcements SET status = 'published', updated_at = NOW()
WHERE id = $1
`

func (q *Queries) PublishAnnouncement(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, publishAnnouncement, id)
	return err
}

const searchAnnouncements = `-- name: SearchAnnouncements :many
SELECT a.id, a.title, a.content, a.is_pinned, a.target_level, a.target_audience, a.expires_at, a.created_by, a.created_at, a.summary, a.priority, a.category, a.target_levels, a.target_departments, a.attachments, a.requires_acknowledgment, a.status, a.scheduled_for, a.read_count, a.acknowledged_count, a.pin_order, a.updated_at, u.full_name AS author_name
FROM announcements a
JOIN users u ON u.id = a.created_by
WHERE a.status = 'published'
AND (a.title ILIKE '%' || $1 || '%' OR a.content ILIKE '%' || $1 || '%')
ORDER BY a.created_at DESC
LIMIT $2 OFFSET $3
`

type SearchAnnouncementsParams struct {
	Column1 *string `json:"column_1"`
	Limit   int32   `json:"limit"`
	Offset  int32   `json:"offset"`
}

type SearchAnnouncementsRow struct {
	ID                     uuid.UUID          `json:"id"`
	Title                  string             `json:"title"`
	Content                string             `json:"content"`
	IsPinned               bool               `json:"is_pinned"`
	TargetLevel            *int32             `json:"target_level"`
	TargetAudience         []byte             `json:"target_audience"`
	ExpiresAt              pgtype.Timestamptz `json:"expires_at"`
	CreatedBy              uuid.UUID          `json:"created_by"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
	Summary                *string            `json:"summary"`
	Priority               interface{}        `json:"priority"`
	Category               interface{}        `json:"category"`
	TargetLevels           []byte             `json:"target_levels"`
	TargetDepartments      []byte             `json:"target_departments"`
	Attachments            []byte             `json:"attachments"`
	RequiresAcknowledgment bool               `json:"requires_acknowledgment"`
	Status                 interface{}        `json:"status"`
	ScheduledFor           pgtype.Timestamptz `json:"scheduled_for"`
	ReadCount              int32              `json:"read_count"`
	AcknowledgedCount      int32              `json:"acknowledged_count"`
	PinOrder               *int32             `json:"pin_order"`
	UpdatedAt              pgtype.Timestamptz `json:"updated_at"`
	AuthorName             string             `json:"author_name"`
}

func (q *Queries) SearchAnnouncements(ctx context.Context, arg SearchAnnouncementsParams) ([]SearchAnnouncementsRow, error) {
	rows, err := q.db.Query(ctx, searchAnnouncements, arg.Column1, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchAnnouncementsRow{}
	for rows.Next() {
		var i SearchAnnouncementsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Content,
			&i.IsPinned,
			&i.TargetLevel,
			&i.TargetAudience,
			&i.ExpiresAt,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.Summary,
			&i.Priority,
			&i.Category,
			&i.TargetLevels,
			&i.TargetDepartments,
			&i.Attachments,
			&i.RequiresAcknowledgment,
			&i.Status,
			&i.ScheduledFor,
			&i.ReadCount,
			&i.AcknowledgedCount,
			&i.PinOrder,
			&i.UpdatedAt,
			&i.AuthorName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAnnouncementTemplate = `-- name: UpdateAnnouncementTemplate :exec
UPDATE announcement_templates
SET name = COALESCE($2, name), default_title = COALESCE($3, default_title),
    default_body = COALESCE($4, default_body), default_priority = COALESCE($5, default_priority),
    default_category = COALESCE($6, default_category),
    default_requires_acknowledgment = COALESCE($7, default_requires_acknowledgment),
    updated_at = NOW()
WHERE id = $1
`

type UpdateAnnouncementTemplateParams struct {
	ID                            uuid.UUID   `json:"id"`
	Name                          string      `json:"name"`
	DefaultTitle                  string      `json:"default_title"`
	DefaultBody                   string      `json:"default_body"`
	DefaultPriority               interface{} `json:"default_priority"`
	DefaultCategory               interface{} `json:"default_category"`
	DefaultRequiresAcknowledgment bool        `json:"default_requires_acknowledgment"`
}

func (q *Queries) UpdateAnnouncementTemplate(ctx context.Context, arg UpdateAnnouncementTemplateParams) error {
	_, err := q.db.Exec(ctx, updateAnnouncementTemplate,
		arg.ID,
		arg.Name,
		arg.DefaultTitle,
		arg.DefaultBody,
		arg.DefaultPriority,
		arg.DefaultCategory,
		arg.DefaultRequiresAcknowledgment,
	)
	return err
}

const updateAnnouncementV2 = `-- name: UpdateAnnouncementV2 :exec
UPDATE announcements
SET title = COALESCE($2, title), content = COALESCE($3, content),
    summary = COALESCE($4, summary), priority = COALESCE($5, priority),
    category = COALESCE($6, category), is_pinned = COALESCE($7, is_pinned),
    target_level = COALESCE($8, target_level), target_audience = COALESCE($9, target_audience),
    target_levels = COALESCE($10, target_levels), target_departments = COALESCE($11, target_departments),
    attachments = COALESCE($12, attachments), requires_acknowledgment = COALESCE($13, requires_acknowledgment),
    status = COALESCE($14, status), scheduled_for = COALESCE($15, scheduled_for),
    expires_at = COALESCE($16, expires_at), pin_order = $17, updated_at = NOW()
WHERE id = $1
`

type UpdateAnnouncementV2Params struct {
	ID                     uuid.UUID          `json:"id"`
	Title                  string             `json:"title"`
	Content                string             `json:"content"`
	Summary                *string            `json:"summary"`
	Priority               interface{}        `json:"priority"`
	Category               interface{}        `json:"category"`
	IsPinned               bool               `json:"is_pinned"`
	TargetLevel            *int32             `json:"target_level"`
	TargetAudience         []byte             `json:"target_audience"`
	TargetLevels           []byte             `json:"target_levels"`
	TargetDepartments      []byte             `json:"target_departments"`
	Attachments            []byte             `json:"attachments"`
	RequiresAcknowledgment bool               `json:"requires_acknowledgment"`
	Status                 interface{}        `json:"status"`
	ScheduledFor           pgtype.Timestamptz `json:"scheduled_for"`
	ExpiresAt              pgtype.Timestamptz `json:"expires_at"`
	PinOrder               *int32             `json:"pin_order"`
}

func (q *Queries) UpdateAnnouncementV2(ctx context.Context, arg UpdateAnnouncementV2Params) error {
	_, err := q.db.Exec(ctx, updateAnnouncementV2,
		arg.ID,
		arg.Title,
		arg.Content,
		arg.Summary,
		arg.Priority,
		arg.Category,
		arg.IsPinned,
		arg.TargetLevel,
		arg.TargetAudience,
		arg.TargetLevels,
		arg.TargetDepartments,
		arg.Attachments,
		arg.RequiresAcknowledgment,
		arg.Status,
		arg.ScheduledFor,
		arg.ExpiresAt,
		arg.PinOrder,
	)
	return err
}

const updateStudentOnboardingStatus = `-- name: UpdateStudentOnboardingStatus :exec
UPDATE student_onboardings
SET status = $2, reviewed_by = $3, reviewed_at = NOW(),
    rejection_reason = $4, updated_at = NOW()
WHERE id = $1
`

type UpdateStudentOnboardingStatusParams struct {
	ID              uuid.UUID   `json:"id"`
	Status          interface{} `json:"status"`
	ReviewedBy      pgtype.UUID `json:"reviewed_by"`
	RejectionReason *string     `json:"rejection_reason"`
}

func (q *Queries) UpdateStudentOnboardingStatus(ctx context.Context, arg UpdateStudentOnboardingStatusParams) error {
	_, err := q.db.Exec(ctx, updateStudentOnboardingStatus,
		arg.ID,
		arg.Status,
		arg.ReviewedBy,
		arg.RejectionReason,
	)
	return err
}

const updateUserApproval = `-- name: UpdateUserApproval :exec

UPDATE users SET is_approved = $2, approved_by = $3, approved_at = NOW() WHERE id = $1
`

type UpdateUserApprovalParams struct {
	ID         uuid.UUID   `json:"id"`
	IsApproved bool        `json:"is_approved"`
	ApprovedBy pgtype.UUID `json:"approved_by"`
}

// ==================== LOOKUP QUERIES ====================
func (q *Queries) UpdateUserApproval(ctx context.Context, arg UpdateUserApprovalParams) error {
	_, err := q.db.Exec(ctx, updateUserApproval, arg.ID, arg.IsApproved, arg.ApprovedBy)
	return err
}

const updateVerificationRecord = `-- name: UpdateVerificationRecord :exec
UPDATE verification_records
SET full_name = COALESCE($2, full_name), level = COALESCE($3, level),
    entry_session = COALESCE($4, entry_session), status = COALESCE($5, status),
    updated_at = NOW()
WHERE id = $1
`

type UpdateVerificationRecordParams struct {
	ID           uuid.UUID `json:"id"`
	FullName     string    `json:"full_name"`
	Level        int32     `json:"level"`
	EntrySession string    `json:"entry_session"`
	Status       string    `json:"status"`
}

func (q *Queries) UpdateVerificationRecord(ctx context.Context, arg UpdateVerificationRecordParams) error {
	_, err := q.db.Exec(ctx, updateVerificationRecord,
		arg.ID,
		arg.FullName,
		arg.Level,
		arg.EntrySession,
		arg.Status,
	)
	return err
}
