ALTER TABLE crf_signing_submissions
    DROP COLUMN IF EXISTS placements;

ALTER TABLE crf_signature_assets
    ADD COLUMN IF NOT EXISTS page_number INT NOT NULL DEFAULT 1,
    ADD COLUMN IF NOT EXISTS x_pt NUMERIC NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS y_pt NUMERIC NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS width_pt NUMERIC NOT NULL DEFAULT 100,
    ADD COLUMN IF NOT EXISTS max_height_pt NUMERIC NOT NULL DEFAULT 30,
    ADD COLUMN IF NOT EXISTS show_date BOOLEAN NOT NULL DEFAULT true,
    ADD COLUMN IF NOT EXISTS date_x_pt NUMERIC,
    ADD COLUMN IF NOT EXISTS date_y_pt NUMERIC,
    ADD COLUMN IF NOT EXISTS date_font_size NUMERIC NOT NULL DEFAULT 10;
