ALTER TABLE timetable ADD COLUMN IF NOT EXISTS day_of_week INTEGER;
ALTER TABLE timetable ADD COLUMN IF NOT EXISTS level INTEGER;
ALTER TABLE timetable ALTER COLUMN session_id DROP NOT NULL;
ALTER TABLE timetable ALTER COLUMN semester_id DROP NOT NULL;
ALTER TABLE timetable ALTER COLUMN created_by DROP NOT NULL;
