DROP TABLE IF EXISTS lecturer_performance;
DROP TABLE IF EXISTS lecturer_evaluations;
DROP TABLE IF EXISTS lecturer_leave;
DROP TABLE IF EXISTS lecturer_course_assignments;
DROP TYPE IF EXISTS leave_status;
DROP TYPE IF EXISTS leave_type;
ALTER TABLE payments DROP COLUMN IF EXISTS payment_method;
ALTER TABLE payments DROP COLUMN IF EXISTS bank_reference;
ALTER TABLE payments DROP COLUMN IF EXISTS bank_name;
ALTER TABLE payments DROP COLUMN IF EXISTS receipt_url;
ALTER TABLE payments DROP COLUMN IF EXISTS recorded_by;
ALTER TABLE payments DROP COLUMN IF EXISTS notes;
ALTER TABLE staff DROP COLUMN IF EXISTS title;
ALTER TABLE staff DROP COLUMN IF EXISTS first_name;
ALTER TABLE staff DROP COLUMN IF EXISTS last_name;
ALTER TABLE staff DROP COLUMN IF EXISTS employment_type;
ALTER TABLE staff DROP COLUMN IF EXISTS employment_status;
ALTER TABLE staff DROP COLUMN IF EXISTS qualifications;
ALTER TABLE staff DROP COLUMN IF EXISTS bio;
ALTER TABLE staff DROP COLUMN IF EXISTS office_location;
ALTER TABLE staff DROP COLUMN IF EXISTS office_hours;
ALTER TABLE staff DROP COLUMN IF EXISTS publications;
ALTER TABLE staff DROP COLUMN IF EXISTS date_joined;
ALTER TABLE staff DROP COLUMN IF EXISTS updated_at;
