
INSERT INTO courses (code, title, description, unit, level, semester, course_type, requirement_type) VALUES
-- 100L First Semester
('GST 111', 'Communication in English', NULL, 2, 100, 'first', 'non_departmental', 'core'),
('MTH 111', 'General Mathematics I', NULL, 2, 100, 'first', 'non_departmental', 'core'),
('PHY 111', 'General Physics I', NULL, 2, 100, 'first', 'non_departmental', 'core'),
('PHY 117', 'General Physics Practical I', NULL, 1, 100, 'first', 'non_departmental', 'core'),
('GET 111', 'Engineer in Society', NULL, 1, 100, 'first', 'non_departmental', 'core'),
('CPE 111', 'Introduction to Computer Engineering', 'Practical course', 2, 100, 'first', 'departmental', 'core'),
('CPE 113', 'Discrete Mathematics for Computing', NULL, 3, 100, 'first', 'departmental', 'core'),
('PHY 112', 'General Physics III', NULL, 2, 100, 'first', 'non_departmental', 'core'),
-- 100L Second Semester
('GST 121', 'Nigerian Peoples and Culture', NULL, 2, 100, 'second', 'non_departmental', 'core'),
('MTH 121', 'Elementary Mathematics II: Calculus', NULL, 2, 100, 'second', 'non_departmental', 'core'),
('PHY 121', 'General Physics II (Electricity and Magnetism)', NULL, 2, 100, 'second', 'non_departmental', 'core'),
('PHY 128', 'General Practical Physics II', NULL, 1, 100, 'second', 'non_departmental', 'core'),
('GET 122', 'Engineering Graphics and Solid Modelling', NULL, 2, 100, 'second', 'non_departmental', 'core'),
('MTH 122', 'General Mathematics III', NULL, 2, 100, 'second', 'non_departmental', 'core'),
('STA 121', 'Probability I', NULL, 3, 100, 'second', 'non_departmental', 'core'),
('CPE 122', 'Computer Programming I (Intro to C)', 'Practical course', 2, 100, 'second', 'departmental', 'core'),
-- 200L First Semester
('GST 211', 'Philosophy, Logic and Human Existence', NULL, 2, 200, 'first', 'non_departmental', 'core'),
('GET 211', 'Applied Electricity I', NULL, 3, 200, 'first', 'non_departmental', 'core'),
('GET 212', 'Fundamental of Fluid Mechanics', NULL, 3, 200, 'first', 'non_departmental', 'core'),
('GET 213', 'Engineering Mathematics I', NULL, 3, 200, 'first', 'non_departmental', 'core'),
('GET 214', 'Computing and Software Engineering', 'Practical course', 3, 200, 'first', 'non_departmental', 'core'),
('GET 215', 'Strength of Material', NULL, 3, 200, 'first', 'non_departmental', 'core'),
-- 200L Second Semester
('ENT 221', 'Entrepreneurship and Innovation', NULL, 2, 200, 'second', 'non_departmental', 'core'),
('GET 221', 'Engineering Materials', NULL, 3, 200, 'second', 'non_departmental', 'core'),
('GET 222', 'Engineering Workshop Practice', NULL, 2, 200, 'second', 'non_departmental', 'core'),
('GET 224', 'Engineering Mathematics II', NULL, 3, 200, 'second', 'non_departmental', 'core'),
('GET 225', 'Applied Mechanics', NULL, 3, 200, 'second', 'non_departmental', 'core'),
('GET 227', 'Engineering Graphics and Solid Modeling', NULL, 2, 200, 'second', 'non_departmental', 'core'),
('CPE 221', 'Computing and Software Engineering II', 'Practical course', 2, 200, 'second', 'departmental', 'core'),
-- 300L First Semester
('GST 311', 'Peace and Conflict Resolution', NULL, 2, 300, 'first', 'non_departmental', 'core'),
('GET 311', 'Engineering Mathematics III', NULL, 3, 300, 'first', 'non_departmental', 'core'),
('GET 312', 'Engineering Statistics and Data Analytics', NULL, 3, 300, 'first', 'non_departmental', 'core'),
('CPE 311', 'Computer Organization and Architecture', NULL, 2, 300, 'first', 'departmental', 'core'),
('CPE 312', 'Analogue Electronic Circuits', NULL, 2, 300, 'first', 'departmental', 'core'),
('CPE 313', 'Web Technology', 'Practical course', 2, 300, 'first', 'departmental', 'core'),
('CPE 314', 'Operating Systems', NULL, 2, 300, 'first', 'departmental', 'core'),
-- 300L Second Semester
('ENT 321', 'Venture Creation', NULL, 3, 300, 'second', 'non_departmental', 'core'),
('GET 321', 'Engineering Mathematics IV', NULL, 3, 300, 'second', 'non_departmental', 'core'),
('GET 322', 'Engineering, Communication, Technical Writing and Presentation', NULL, 3, 300, 'second', 'non_departmental', 'core'),
('GET 323', 'Renewable Energy Systems and Technologies', NULL, 3, 300, 'second', 'non_departmental', 'core'),
('GET 324', 'Introduction to Artificial Intelligence, Machine Learning', NULL, 2, 300, 'second', 'non_departmental', 'core'),
('CPE 321', 'Computer IT Hardware, Software & Operational Procedures', 'Practical course', 2, 300, 'second', 'departmental', 'core'),
('CPE 322', 'Digital Electronic Circuits', NULL, 2, 300, 'second', 'departmental', 'core'),
-- 400L First Semester
('GET 411', 'Engineering Project I', NULL, 2, 400, 'first', 'non_departmental', 'core'),
('GET 412', 'Engineering Evaluation and Costing', NULL, 2, 400, 'first', 'non_departmental', 'core'),
('CPE 411', 'Microprocessor and Embedded Systems', 'Practical course', 2, 400, 'first', 'departmental', 'core'),
('CPE 412', 'Control System (Robotics and Automation)', 'Practical course', 2, 400, 'first', 'departmental', 'core'),
('CPE 413', 'Fundamentals of Software Engineering', NULL, 2, 400, 'first', 'departmental', 'core'),
('CPE 414', 'Hardware Design Techniques and Verification', NULL, 2, 400, 'first', 'departmental', 'elective'),
('CPE 415', 'Database System Design and Applications', NULL, 2, 400, 'first', 'departmental', 'core'),
('CPE 416', 'Ubiquitous and Distributed Computing', NULL, 2, 400, 'first', 'departmental', 'core'),
('CPE 417', 'Assembly and Machine Language Programming', NULL, 2, 400, 'first', 'departmental', 'elective'),
('CPE 419', 'Neural Networks and Deep Learning', NULL, 2, 400, 'first', 'departmental', 'core'),
-- SIWES (200L/300L/400L second semester)
('GET 226', 'SIWES I', NULL, 3, 200, 'second', 'non_departmental', 'core'),
('GET 326', 'SIWES II', NULL, 4, 300, 'second', 'non_departmental', 'core'),
('GET 426', 'SIWES III', NULL, 6, 400, 'second', 'non_departmental', 'core'),
('GET 428', 'Engineering Valuation', NULL, 2, 400, 'second', 'non_departmental', 'core'),
-- 500L First Semester
('GET 511', 'Engineering Project Management', NULL, 3, 500, 'first', 'non_departmental', 'core'),
('GET 512', 'Engineering Law', NULL, 2, 500, 'first', 'non_departmental', 'core'),
('CPE 511', 'Data Communication and Networks', NULL, 2, 500, 'first', 'departmental', 'core'),
('CPE 512', 'Digital System Design with VHDL', 'Practical course', 2, 500, 'first', 'departmental', 'core'),
('CPE 513', 'Machine Learning and Applications', NULL, 2, 500, 'first', 'departmental', 'core'),
('CPE 514', 'Digital Forensics and Cyber Law', NULL, 2, 500, 'first', 'departmental', 'core'),
('CPE 515', 'Computer Vision and Robotics', NULL, 2, 500, 'first', 'departmental', 'core'),
('CPE 516', 'Human Computer Interaction', NULL, 2, 500, 'first', 'departmental', 'elective'),
('CPE 517', 'Mobile Application Development', NULL, 2, 500, 'first', 'departmental', 'elective'),
-- 500L Second Semester
('CPE 521', 'Digital Signal Processing', NULL, 2, 500, 'second', 'departmental', 'core'),
('CPE 522', 'Engineering Testing, Reliability and Maintainability', NULL, 2, 500, 'second', 'departmental', 'elective'),
('CPE 523', 'Digital Communication Network', NULL, 3, 500, 'second', 'departmental', 'core'),
('CPE 524', 'Technology, Strategy and Innovations', NULL, 2, 500, 'second', 'departmental', 'core'),
('CPE 525', 'Computer Security and Cryptography', NULL, 2, 500, 'second', 'departmental', 'core'),
('CPE 526', 'Software Project Management', NULL, 2, 500, 'second', 'departmental', 'elective'),
('CPE 529', 'Final Year Project', NULL, 6, 500, 'second', 'departmental', 'core')
ON CONFLICT (code) DO NOTHING;
