import { View, StyleSheet, Pressable } from 'react-native';
import Text from '../../src/components/ui/Text';
import { useRouter, type Href } from 'expo-router';
import { Ionicons } from '@expo/vector-icons';
import Animated, { FadeInDown } from 'react-native-reanimated';
import { useTheme } from '../../src/theme/ThemeProvider';
import { fontFamily, fontSize, radius, spacing } from '../../src/theme/typography';
import Screen from '../../src/components/ui/Screen';
import Card from '../../src/components/ui/Card';

// The class-rep hub, reached from Profile once a user has switched into
// class_rep mode (see RoleSwitcher in app/(tabs)/profile/index.tsx).
// Attendance-taking is its own screen under this stack (app/class-rep/
// attendance.tsx) — deliberately not the shared (tabs)/attendance.tsx tab,
// which always shows the plain student view regardless of active role.
// expo-router's typed routes are generated by the dev server at startup —
// these paths are structurally correct (they match the files under
// app/class-rep/) but the type union in .expo/types/router.d.ts won't
// include them until `expo start` has run at least once, hence the cast.
const links: { icon: keyof typeof Ionicons.glyphMap; label: string; desc: string; href: Href }[] = [
  { icon: 'qr-code-outline', label: 'Take Attendance', desc: 'Open a session and check students in', href: '/class-rep/attendance' as Href },
  { icon: 'people-outline', label: 'Class List', desc: 'Browse students in your level', href: '/class-rep/class-list' as Href },
  { icon: 'checkmark-done-outline', label: 'Pending Requests', desc: 'Verify course forms & new accounts', href: '/class-rep/pending-requests' as Href },
  { icon: 'megaphone-outline', label: 'Notify Classmates', desc: 'Post to the class notice board', href: '/class-rep/notify' as Href },
];

export default function ClassRepHubScreen() {
  const { theme } = useTheme();
  const router = useRouter();

  return (
    <Screen>
      <Pressable style={styles.backRow} onPress={() => router.back()} hitSlop={12}>
        <Ionicons name="chevron-back" size={20} color={theme.primary} />
        <Text style={[styles.backLabel, { color: theme.primary }]}>Profile</Text>
      </Pressable>

      <Text style={[styles.header, { color: theme.text }]}>Class Rep Tools</Text>
      <Text style={{ color: theme.textMuted, fontSize: fontSize.sm, marginBottom: spacing.md }}>
        Tools available while you're in Class Rep mode.
      </Text>

      {links.map((item, i) => (
        <Animated.View key={item.label} entering={FadeInDown.duration(350).delay(i * 40)}>
          <Pressable onPress={() => router.push(item.href)}>
            <Card style={styles.row}>
              <View style={[styles.iconWrap, { backgroundColor: theme.primaryMuted }]}>
                <Ionicons name={item.icon} size={20} color={theme.primary} />
              </View>
              <View style={styles.flex}>
                <Text style={[styles.rowLabel, { color: theme.text }]}>{item.label}</Text>
                <Text style={[styles.rowDesc, { color: theme.textMuted }]}>{item.desc}</Text>
              </View>
              <Ionicons name="chevron-forward" size={18} color={theme.textFaint} />
            </Card>
          </Pressable>
        </Animated.View>
      ))}
    </Screen>
  );
}

const styles = StyleSheet.create({
  flex: { flex: 1 },
  backRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: -spacing.sm,
  },
  backLabel: {
    fontFamily: fontFamily.medium,
    fontSize: fontSize.sm,
    marginLeft: 2,
  },
  header: {
    fontFamily: fontFamily.bold,
    fontSize: fontSize['2xl'],
    marginTop: spacing.sm,
  },
  row: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.md,
  },
  iconWrap: {
    width: 40,
    height: 40,
    borderRadius: radius.md,
    alignItems: 'center',
    justifyContent: 'center',
  },
  rowLabel: {
    fontFamily: fontFamily.semibold,
    fontSize: fontSize.sm,
  },
  rowDesc: {
    fontFamily: fontFamily.regular,
    fontSize: fontSize.xs,
    marginTop: 2,
  },
});
